# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: addon.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'addon.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61\x64\x64on.proto\"\xd8\x01\n\x0b\x41\x64\x64onStatus\x12\x0b\n\x03uid\x18\x01 \x01(\r\x12!\n\tnode_type\x18\x02 \x01(\x0e\x32\x0e.AddonNodeType\x12\x10\n\x08uptime_s\x18\x03 \x01(\r\x12\x14\n\x0c\x64\x65tach_epoch\x18\x04 \x01(\r\x12\x0f\n\x07\x62\x61tt_mv\x18\x05 \x01(\r\x12%\n\x0bmotor_state\x18\x06 \x01(\x0e\x32\x10.AddonMotorState\x12\x12\n\npaired_uid\x18\x07 \x01(\r\x12\x16\n\x0e\x62\x61tt_loaded_mv\x18\x08 \x01(\r\x12\r\n\x05\x66ired\x18\t \x01(\r\"d\n\x0c\x41\x64\x64onCommand\x12\x1e\n\x03\x63md\x18\x01 \x01(\x0e\x32\x11.AddonCommandType\x12\r\n\x05param\x18\x02 \x01(\r\x12\x0f\n\x07src_uid\x18\x03 \x01(\r\x12\x14\n\x0csender_epoch\x18\x04 \x01(\r\"+\n\tAddonTime\x12\r\n\x05\x65poch\x18\x01 \x01(\r\x12\x0f\n\x07src_uid\x18\x02 \x01(\r*U\n\rAddonNodeType\x12\x16\n\x12\x41\x44\x44ON_TYPE_UNKNOWN\x10\x00\x12\x15\n\x11\x41\x44\x44ON_TYPE_DETACH\x10\x01\x12\x15\n\x11\x41\x44\x44ON_TYPE_SATCOM\x10\x02*\xdc\x02\n\x10\x41\x64\x64onCommandType\x12\x11\n\rADDON_CMD_NOP\x10\x00\x12\x1e\n\x1a\x41\x44\x44ON_CMD_SET_DETACH_EPOCH\x10\x01\x12\x18\n\x14\x41\x44\x44ON_CMD_DETACH_NOW\x10\x02\x12\x13\n\x0f\x41\x44\x44ON_CMD_ABORT\x10\x03\x12\x1e\n\x1a\x41\x44\x44ON_CMD_EXTENDED_SESSION\x10\x04\x12\x18\n\x14\x41\x44\x44ON_CMD_ENABLE_BLE\x10\x05\x12\x18\n\x14\x41\x44\x44ON_CMD_ATTACH_NOW\x10\x06\x12\x18\n\x14\x41\x44\x44ON_CMD_MOTOR_STOP\x10\x07\x12\x16\n\x12\x41\x44\x44ON_CMD_SET_MODE\x10\x08\x12\x19\n\x15\x41\x44\x44ON_CMD_SET_CHECKIN\x10\t\x12\x12\n\x0e\x41\x44\x44ON_CMD_PAIR\x10\n\x12\x14\n\x10\x41\x44\x44ON_CMD_UNPAIR\x10\x0b\x12\x1b\n\x17\x41\x44\x44ON_CMD_FACTORY_RESET\x10\x0c*]\n\x0f\x41\x64\x64onMotorState\x12\x14\n\x10\x41\x44\x44ON_MOTOR_IDLE\x10\x00\x12\x19\n\x15\x41\x44\x44ON_MOTOR_DETACHING\x10\x01\x12\x19\n\x15\x41\x44\x44ON_MOTOR_ATTACHING\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'addon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDONNODETYPE']._serialized_start=381
  _globals['_ADDONNODETYPE']._serialized_end=466
  _globals['_ADDONCOMMANDTYPE']._serialized_start=469
  _globals['_ADDONCOMMANDTYPE']._serialized_end=817
  _globals['_ADDONMOTORSTATE']._serialized_start=819
  _globals['_ADDONMOTORSTATE']._serialized_end=912
  _globals['_ADDONSTATUS']._serialized_start=16
  _globals['_ADDONSTATUS']._serialized_end=232
  _globals['_ADDONCOMMAND']._serialized_start=234
  _globals['_ADDONCOMMAND']._serialized_end=334
  _globals['_ADDONTIME']._serialized_start=336
  _globals['_ADDONTIME']._serialized_end=379
# @@protoc_insertion_point(module_scope)
