/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "addon.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AddonStatus, AddonStatus, AUTO)


PB_BIND(AddonCommand, AddonCommand, AUTO)


PB_BIND(AddonTime, AddonTime, AUTO)






