/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "addon.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ADDON_STATUS, addon_status_t, AUTO)


PB_BIND(ADDON_COMMAND, addon_command_t, AUTO)


PB_BIND(ADDON_TIME, addon_time_t, AUTO)






