/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_ADDON_PB_H_INCLUDED
#define PB_ADDON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _AddonNodeType {
    AddonNodeType_ADDON_TYPE_UNKNOWN = 0,
    AddonNodeType_ADDON_TYPE_DETACH = 1, /* detachment mechanism */
    AddonNodeType_ADDON_TYPE_SATCOM = 2 /* reserved */
} AddonNodeType;

typedef enum _AddonCommandType {
    AddonCommandType_ADDON_CMD_NOP = 0,
    AddonCommandType_ADDON_CMD_SET_DETACH_EPOCH = 1, /* param = epoch (UTC s) */
    AddonCommandType_ADDON_CMD_DETACH_NOW = 2, /* param = run timeout s (0 = default) */
    AddonCommandType_ADDON_CMD_ABORT = 3, /* clear armed epoch */
    AddonCommandType_ADDON_CMD_EXTENDED_SESSION = 4, /* param = hold grant, seconds */
    AddonCommandType_ADDON_CMD_ENABLE_BLE = 5, /* reserved DFU hook */
    AddonCommandType_ADDON_CMD_ATTACH_NOW = 6, /* param = run timeout s (0 = default) */
    AddonCommandType_ADDON_CMD_MOTOR_STOP = 7,
    AddonCommandType_ADDON_CMD_SET_MODE = 8, /* param: 0 standalone, 1 linked */
    AddonCommandType_ADDON_CMD_SET_CHECKIN = 9, /* param = cadence seconds (>= 60) */
    AddonCommandType_ADDON_CMD_PAIR = 10 /* param = collar uid (collar stamps) */
} AddonCommandType;

typedef enum _AddonMotorState {
    AddonMotorState_ADDON_MOTOR_IDLE = 0,
    AddonMotorState_ADDON_MOTOR_DETACHING = 1,
    AddonMotorState_ADDON_MOTOR_ATTACHING = 2
} AddonMotorState;

/* Struct definitions */
/* node -> collar, on attach / state change / rate-limited keepalive */
typedef struct _AddonStatus {
    uint32_t uid; /* node die UID */
    AddonNodeType node_type;
    uint32_t uptime_s;
    uint32_t detach_epoch; /* armed, 0 = none */
    uint32_t batt_mv; /* resting; 0 = unknown */
    AddonMotorState motor_state;
    uint32_t paired_uid; /* collar this node serves; 0 = unpaired */
    uint32_t batt_loaded_mv; /* last under-motor-load reading; 0 = none */
    uint32_t fired; /* 1 = scheduled detach already fired */
} AddonStatus;

/* collar -> node */
typedef struct _AddonCommand {
    AddonCommandType cmd;
    uint32_t param;
    uint32_t src_uid; /* sending collar identity (pairing filter) */
    uint32_t sender_epoch; /* optional opportunistic RTC sync (§5.1); 0 = none */
} AddonCommand;

/* collar -> node (explicit time discipline; any AddonCommand.sender_epoch
 also disciplines the clock) */
typedef struct _AddonTime {
    uint32_t epoch; /* UTC seconds; node gates >= 2026-01-01 */
    uint32_t src_uid;
} AddonTime;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _AddonNodeType_MIN AddonNodeType_ADDON_TYPE_UNKNOWN
#define _AddonNodeType_MAX AddonNodeType_ADDON_TYPE_SATCOM
#define _AddonNodeType_ARRAYSIZE ((AddonNodeType)(AddonNodeType_ADDON_TYPE_SATCOM+1))

#define _AddonCommandType_MIN AddonCommandType_ADDON_CMD_NOP
#define _AddonCommandType_MAX AddonCommandType_ADDON_CMD_PAIR
#define _AddonCommandType_ARRAYSIZE ((AddonCommandType)(AddonCommandType_ADDON_CMD_PAIR+1))

#define _AddonMotorState_MIN AddonMotorState_ADDON_MOTOR_IDLE
#define _AddonMotorState_MAX AddonMotorState_ADDON_MOTOR_ATTACHING
#define _AddonMotorState_ARRAYSIZE ((AddonMotorState)(AddonMotorState_ADDON_MOTOR_ATTACHING+1))

#define AddonStatus_node_type_ENUMTYPE AddonNodeType
#define AddonStatus_motor_state_ENUMTYPE AddonMotorState

#define AddonCommand_cmd_ENUMTYPE AddonCommandType



/* Initializer values for message structs */
#define AddonStatus_init_default                 {0, _AddonNodeType_MIN, 0, 0, 0, _AddonMotorState_MIN, 0, 0, 0}
#define AddonCommand_init_default                {_AddonCommandType_MIN, 0, 0, 0}
#define AddonTime_init_default                   {0, 0}
#define AddonStatus_init_zero                    {0, _AddonNodeType_MIN, 0, 0, 0, _AddonMotorState_MIN, 0, 0, 0}
#define AddonCommand_init_zero                   {_AddonCommandType_MIN, 0, 0, 0}
#define AddonTime_init_zero                      {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AddonStatus_uid_tag                      1
#define AddonStatus_node_type_tag                2
#define AddonStatus_uptime_s_tag                 3
#define AddonStatus_detach_epoch_tag             4
#define AddonStatus_batt_mv_tag                  5
#define AddonStatus_motor_state_tag              6
#define AddonStatus_paired_uid_tag               7
#define AddonStatus_batt_loaded_mv_tag           8
#define AddonStatus_fired_tag                    9
#define AddonCommand_cmd_tag                     1
#define AddonCommand_param_tag                   2
#define AddonCommand_src_uid_tag                 3
#define AddonCommand_sender_epoch_tag            4
#define AddonTime_epoch_tag                      1
#define AddonTime_src_uid_tag                    2

/* Struct field encoding specification for nanopb */
#define AddonStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uid,               1) \
X(a, STATIC,   SINGULAR, UENUM,    node_type,         2) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_s,          3) \
X(a, STATIC,   SINGULAR, UINT32,   detach_epoch,      4) \
X(a, STATIC,   SINGULAR, UINT32,   batt_mv,           5) \
X(a, STATIC,   SINGULAR, UENUM,    motor_state,       6) \
X(a, STATIC,   SINGULAR, UINT32,   paired_uid,        7) \
X(a, STATIC,   SINGULAR, UINT32,   batt_loaded_mv,    8) \
X(a, STATIC,   SINGULAR, UINT32,   fired,             9)
#define AddonStatus_CALLBACK NULL
#define AddonStatus_DEFAULT NULL

#define AddonCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    cmd,               1) \
X(a, STATIC,   SINGULAR, UINT32,   param,             2) \
X(a, STATIC,   SINGULAR, UINT32,   src_uid,           3) \
X(a, STATIC,   SINGULAR, UINT32,   sender_epoch,      4)
#define AddonCommand_CALLBACK NULL
#define AddonCommand_DEFAULT NULL

#define AddonTime_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   epoch,             1) \
X(a, STATIC,   SINGULAR, UINT32,   src_uid,           2)
#define AddonTime_CALLBACK NULL
#define AddonTime_DEFAULT NULL

extern const pb_msgdesc_t AddonStatus_msg;
extern const pb_msgdesc_t AddonCommand_msg;
extern const pb_msgdesc_t AddonTime_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AddonStatus_fields &AddonStatus_msg
#define AddonCommand_fields &AddonCommand_msg
#define AddonTime_fields &AddonTime_msg

/* Maximum encoded size of messages (where known) */
#define AddonCommand_size                        20
#define AddonStatus_size                         46
#define AddonTime_size                           12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
