/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_BLE_PB_H_INCLUDED
#define PB_BLE_PB_H_INCLUDED
#include <pb.h>
#include "common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum radio_region {
    RADIO_REGION_REGION_US915 = 0,
    RADIO_REGION_REGION_AU915 = 1,
    RADIO_REGION_REGION_EU868 = 2
} radio_region_t;

typedef enum radio_auth {
    RADIO_AUTH_AUTH_OTAA = 0,
    RADIO_AUTH_AUTH_ABP = 1
} radio_auth_t;

typedef enum radio_spreading_factor {
    RADIO_SPREADING_FACTOR_SF7 = 0,
    RADIO_SPREADING_FACTOR_SF8 = 1,
    RADIO_SPREADING_FACTOR_SF9 = 2,
    RADIO_SPREADING_FACTOR_SF10 = 3,
    RADIO_SPREADING_FACTOR_SF11 = 4,
    RADIO_SPREADING_FACTOR_SF12 = 5
} radio_spreading_factor_t;

typedef enum radio_bandwidth {
    RADIO_BANDWIDTH_BW_125 = 0,
    RADIO_BANDWIDTH_BW_250 = 1,
    RADIO_BANDWIDTH_BW_500 = 2
} radio_bandwidth_t;

typedef enum radio_coding_rate {
    RADIO_CODING_RATE_CR_4_5 = 0,
    RADIO_CODING_RATE_CR_4_6 = 1,
    RADIO_CODING_RATE_CR_4_7 = 2,
    RADIO_CODING_RATE_CR_4_8 = 3
} radio_coding_rate_t;

typedef enum accel_sample_rate {
    ACCEL_SAMPLE_RATE_ACCEL_25_HZ = 0,
    ACCEL_SAMPLE_RATE_ACCEL_50_HZ = 1
} accel_sample_rate_t;

typedef enum accel_sensitivity {
    ACCEL_SENSITIVITY_ACCEL_2_G = 0,
    ACCEL_SENSITIVITY_ACCEL_4_G = 1,
    ACCEL_SENSITIVITY_ACCEL_8_G = 2
} accel_sensitivity_t;

typedef enum peripheral_type {
    PERIPHERAL_TYPE_PERIPHERAL_SATCOM = 0,
    PERIPHERAL_TYPE_PERIPHERAL_DETACHMENT = 1
} peripheral_type_t;

/* Struct definitions */
/* ================== SCHEDULING / CONFIG ================== */
typedef struct time_window { /* 2 bytes */
    uint32_t start_hour; /* 0 to 23 (inclusive) */
    uint32_t end_hour; /* 0 to 23 (inclusive) */
} time_window_t;

/* Enabled/disabled and sample interval for each sensor */
typedef struct sampling_config {
    bool enabled;
    uint32_t sample_interval_min; /* minutes */
} sampling_config_t;

typedef struct gps_config {
    bool enabled;
    uint32_t sample_interval_min;
    uint32_t accuracy; /* 1 to 10 */
    bool dynamic_sampling_mode;
    uint32_t medium_motion_vedba_threshold_x100;
    uint32_t medium_motion_gps_interval_min;
    uint32_t high_motion_vedba_threshold_x100;
    uint32_t high_motion_gps_interval_min;
    bool lorawan_tx_on_gps_fix;
    bool lora_tx_on_gps_fix;
} gps_config_t;

typedef struct radio_otaa {
    pb_byte_t dev_eui[8]; /* 8, fixed_length */
    pb_byte_t join_eui[8]; /* 8, fixed_length */
    pb_byte_t app_key[16]; /* 16, fixed_length */
    pb_byte_t nwk_key[16]; /* 16, fixed_length */
} radio_otaa_t;

typedef struct radio_abp {
    pb_byte_t dev_addr[4]; /* 4,  fixed_length */
    pb_byte_t nwk_s_key[16]; /* 16, fixed_length */
    pb_byte_t app_s_key[16]; /* 16, fixed_length */
    pb_byte_t f_nwk_s_int_key[16]; /* 16, fixed_length */
    pb_byte_t s_nwk_s_int_key[16]; /* 16, fixed_length */
} radio_abp_t;

typedef struct lo_ra_wan_config {
    radio_region_t region;
    radio_auth_t auth;
    pb_size_t which_credentials;
    union {
        radio_otaa_t otaa;
        radio_abp_t abp;
    } credentials;
    uint32_t transmit_interval_min;
    bool tx_only_on_new_gps_fix;
    int32_t tx_power_dbm;
} lo_ra_wan_config_t;

typedef struct lo_ra_config {
    radio_spreading_factor_t radio_spreading_factor;
    radio_bandwidth_t radio_bandwidth;
    radio_coding_rate_t radio_coding_rate;
    int32_t tx_power_dbm;
    uint32_t sync_word; /* byte value */
    uint32_t frequency;
} lo_ra_config_t;

typedef struct lost_mode_config {
    uint32_t activation_epoch;
    uint32_t transmit_interval_min;
    int32_t tx_power_dbm;
} lost_mode_config_t;

/* Mortality detection (P5). When the collar's accelerometer activity
 (VeDBA) stays below a fixed firmware threshold for trigger_duration_hours,
 it flags every uplink and additionally transmits every
 transmit_interval_min. Alert-only: the configured schedule is unchanged,
 and the state clears by itself if the animal moves again.

 Detection rides the accelerometer windows the schedule already provides
 (the accel is powered down outside them), so this does nothing useful
 unless at least one schedule enables the accelerometer. The near-zero
 VeDBA threshold is deliberately NOT exposed: it is the easiest value to
 get wrong and is tuned in firmware. */
typedef struct mortality_config {
    uint32_t trigger_duration_hours; /* 0 = firmware default (48) */
    uint32_t transmit_interval_min; /* 0 = firmware default (240) */
} mortality_config_t;

typedef struct radio_config_packet {
    bool has_lo_ra_wan_config;
    lo_ra_wan_config_t lo_ra_wan_config;
    bool has_lo_ra_config;
    lo_ra_config_t lo_ra_config;
    bool lost_mode_enabled;
    bool has_lost_mode_config;
    lost_mode_config_t lost_mode_config;
    bool mortality_enabled;
    bool has_mortality_config;
    mortality_config_t mortality_config;
} radio_config_packet_t;

typedef struct microphone_config {
    bool enabled;
    bool continuous_mode; /* on if true */
    uint32_t sample_length_min;
    uint32_t sample_window_min;
} microphone_config_t;

typedef struct accelerometer_config {
    bool enabled;
    accel_sample_rate_t sample_rate;
    accel_sensitivity_t sensitivity;
} accelerometer_config_t;

typedef struct magnetometer_config {
    bool enabled;
    uint32_t sample_interval_s; /* in seconds */
} magnetometer_config_t;

/* schedule that is applied during each TimeWindow */
typedef struct schedule_config {
    bool has_window;
    time_window_t window;
    bool has_light;
    sampling_config_t light;
    bool has_environmental;
    sampling_config_t environmental;
    bool has_particulate;
    sampling_config_t particulate;
    bool has_gps;
    gps_config_t gps;
    bool has_microphone;
    microphone_config_t microphone;
    bool has_accelerometer;
    accelerometer_config_t accelerometer;
    /* LoRaWAN behavior within this schedule */
    bool lorawan_enabled;
    uint32_t lorawan_send_interval_min;
    bool lora_enabled;
    uint32_t lora_send_interval_min;
    bool has_magnetometer;
    magnetometer_config_t magnetometer;
} schedule_config_t;

/* can include multiple schedules */
typedef struct schedule_config_packet {
    bool engaged;
    pb_size_t schedules_count;
    schedule_config_t schedules[5]; /* capped to 5 schedules in options */
    uint32_t special_mode;
} schedule_config_packet_t;

typedef struct simple_sensor_reading {
    uint32_t index;
    float temperature;
    float humidity;
    float pressure;
    float gas;
    float pm2_5;
    uint32_t light;
    activity_t activity;
    uint32_t steps;
    bool particulate_static_obstructed;
    bool particulate_dynamic_obstructed;
    bool particulate_outside_detection_limits;
} simple_sensor_reading_t;

typedef struct system_state_packet {
    bool engage_state; /* engaged/disengaged */
    bool has_battery;
    battery_state_t battery;
    bool has_sdcard;
    sd_card_state_t sdcard;
    bool has_gps_data;
    gps_data_t gps_data;
    bool has_sensors;
    simple_sensor_reading_t sensors;
    char firmware_version[16];
    /* Boot hardware-diagnostic bitmask (HW_RunDiagnostics, hw_diag.h).
 Bit SET = FAULT: 0 accelerometer, 1 magnetometer, 2 light sensor,
 3 BME688, 4 GPS, 5 particulate, 6 LoRa radio. Bit 7 = diagnostics
 ran (validity). Same layout mirrored into Deployment.errorFlags.flag
 on LoRaWAN uplinks. Absent on older firmware. */
    bool has_hw_diag;
    uint32_t hw_diag;
} system_state_packet_t;

typedef struct peripheral_packet {
    pb_byte_t mac_address[6]; /* 6 bytes, fixed-length in options */
    peripheral_type_t type;
} peripheral_packet_t;

typedef struct peripheral_info {
    pb_callback_t device_uids;
} peripheral_info_t;

/* ================== WRAPPER ================== */
typedef struct ble_packet {
    bool has_header;
    packet_header_t header;
    pb_size_t which_payload;
    union {
        schedule_config_packet_t schedule_config_packet;
        system_state_packet_t system_state_packet;
        radio_config_packet_t radio_config_packet;
        peripheral_packet_t peripheral_packet;
        peripheral_info_t peripheral_info;
    } payload;
} ble_packet_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _RADIO_REGION_MIN RADIO_REGION_REGION_US915
#define _RADIO_REGION_MAX RADIO_REGION_REGION_EU868
#define _RADIO_REGION_ARRAYSIZE ((radio_region_t)(RADIO_REGION_REGION_EU868+1))

#define _RADIO_AUTH_MIN RADIO_AUTH_AUTH_OTAA
#define _RADIO_AUTH_MAX RADIO_AUTH_AUTH_ABP
#define _RADIO_AUTH_ARRAYSIZE ((radio_auth_t)(RADIO_AUTH_AUTH_ABP+1))

#define _RADIO_SPREADING_FACTOR_MIN RADIO_SPREADING_FACTOR_SF7
#define _RADIO_SPREADING_FACTOR_MAX RADIO_SPREADING_FACTOR_SF12
#define _RADIO_SPREADING_FACTOR_ARRAYSIZE ((radio_spreading_factor_t)(RADIO_SPREADING_FACTOR_SF12+1))

#define _RADIO_BANDWIDTH_MIN RADIO_BANDWIDTH_BW_125
#define _RADIO_BANDWIDTH_MAX RADIO_BANDWIDTH_BW_500
#define _RADIO_BANDWIDTH_ARRAYSIZE ((radio_bandwidth_t)(RADIO_BANDWIDTH_BW_500+1))

#define _RADIO_CODING_RATE_MIN RADIO_CODING_RATE_CR_4_5
#define _RADIO_CODING_RATE_MAX RADIO_CODING_RATE_CR_4_8
#define _RADIO_CODING_RATE_ARRAYSIZE ((radio_coding_rate_t)(RADIO_CODING_RATE_CR_4_8+1))

#define _ACCEL_SAMPLE_RATE_MIN ACCEL_SAMPLE_RATE_ACCEL_25_HZ
#define _ACCEL_SAMPLE_RATE_MAX ACCEL_SAMPLE_RATE_ACCEL_50_HZ
#define _ACCEL_SAMPLE_RATE_ARRAYSIZE ((accel_sample_rate_t)(ACCEL_SAMPLE_RATE_ACCEL_50_HZ+1))

#define _ACCEL_SENSITIVITY_MIN ACCEL_SENSITIVITY_ACCEL_2_G
#define _ACCEL_SENSITIVITY_MAX ACCEL_SENSITIVITY_ACCEL_8_G
#define _ACCEL_SENSITIVITY_ARRAYSIZE ((accel_sensitivity_t)(ACCEL_SENSITIVITY_ACCEL_8_G+1))

#define _PERIPHERAL_TYPE_MIN PERIPHERAL_TYPE_PERIPHERAL_SATCOM
#define _PERIPHERAL_TYPE_MAX PERIPHERAL_TYPE_PERIPHERAL_DETACHMENT
#define _PERIPHERAL_TYPE_ARRAYSIZE ((peripheral_type_t)(PERIPHERAL_TYPE_PERIPHERAL_DETACHMENT+1))






#define lo_ra_wan_config_t_region_ENUMTYPE radio_region_t
#define lo_ra_wan_config_t_auth_ENUMTYPE radio_auth_t

#define lo_ra_config_t_radio_spreading_factor_ENUMTYPE radio_spreading_factor_t
#define lo_ra_config_t_radio_bandwidth_ENUMTYPE radio_bandwidth_t
#define lo_ra_config_t_radio_coding_rate_ENUMTYPE radio_coding_rate_t





#define accelerometer_config_t_sample_rate_ENUMTYPE accel_sample_rate_t
#define accelerometer_config_t_sensitivity_ENUMTYPE accel_sensitivity_t




#define simple_sensor_reading_t_activity_ENUMTYPE activity_t


#define peripheral_packet_t_type_ENUMTYPE peripheral_type_t




/* Initializer values for message structs */
#define TIME_WINDOW_INIT_DEFAULT                 {0, 0}
#define SAMPLING_CONFIG_INIT_DEFAULT             {0, 0}
#define GPS_CONFIG_INIT_DEFAULT                  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define RADIO_OTAA_INIT_DEFAULT                  {{0}, {0}, {0}, {0}}
#define RADIO_ABP_INIT_DEFAULT                   {{0}, {0}, {0}, {0}, {0}}
#define LO_RA_WAN_CONFIG_INIT_DEFAULT            {_RADIO_REGION_MIN, _RADIO_AUTH_MIN, 0, {RADIO_OTAA_INIT_DEFAULT}, 0, 0, 0}
#define LO_RA_CONFIG_INIT_DEFAULT                {_RADIO_SPREADING_FACTOR_MIN, _RADIO_BANDWIDTH_MIN, _RADIO_CODING_RATE_MIN, 0, 0, 0}
#define LOST_MODE_CONFIG_INIT_DEFAULT            {0, 0, 0}
#define MORTALITY_CONFIG_INIT_DEFAULT            {0, 0}
#define RADIO_CONFIG_PACKET_INIT_DEFAULT         {false, LO_RA_WAN_CONFIG_INIT_DEFAULT, false, LO_RA_CONFIG_INIT_DEFAULT, 0, false, LOST_MODE_CONFIG_INIT_DEFAULT, 0, false, MORTALITY_CONFIG_INIT_DEFAULT}
#define MICROPHONE_CONFIG_INIT_DEFAULT           {0, 0, 0, 0}
#define ACCELEROMETER_CONFIG_INIT_DEFAULT        {0, _ACCEL_SAMPLE_RATE_MIN, _ACCEL_SENSITIVITY_MIN}
#define MAGNETOMETER_CONFIG_INIT_DEFAULT         {0, 0}
#define SCHEDULE_CONFIG_INIT_DEFAULT             {false, TIME_WINDOW_INIT_DEFAULT, false, SAMPLING_CONFIG_INIT_DEFAULT, false, SAMPLING_CONFIG_INIT_DEFAULT, false, SAMPLING_CONFIG_INIT_DEFAULT, false, GPS_CONFIG_INIT_DEFAULT, false, MICROPHONE_CONFIG_INIT_DEFAULT, false, ACCELEROMETER_CONFIG_INIT_DEFAULT, 0, 0, 0, 0, false, MAGNETOMETER_CONFIG_INIT_DEFAULT}
#define SCHEDULE_CONFIG_PACKET_INIT_DEFAULT      {0, 0, {SCHEDULE_CONFIG_INIT_DEFAULT, SCHEDULE_CONFIG_INIT_DEFAULT, SCHEDULE_CONFIG_INIT_DEFAULT, SCHEDULE_CONFIG_INIT_DEFAULT, SCHEDULE_CONFIG_INIT_DEFAULT}, 0}
#define SIMPLE_SENSOR_READING_INIT_DEFAULT       {0, 0, 0, 0, 0, 0, 0, _ACTIVITY_MIN, 0, 0, 0, 0}
#define SYSTEM_STATE_PACKET_INIT_DEFAULT         {0, false, BATTERY_STATE_INIT_DEFAULT, false, SD_CARD_STATE_INIT_DEFAULT, false, GPS_DATA_INIT_DEFAULT, false, SIMPLE_SENSOR_READING_INIT_DEFAULT, "", false, 0}
#define PERIPHERAL_PACKET_INIT_DEFAULT           {{0}, _PERIPHERAL_TYPE_MIN}
#define PERIPHERAL_INFO_INIT_DEFAULT             {{{NULL}, NULL}}
#define BLE_PACKET_INIT_DEFAULT                  {false, PACKET_HEADER_INIT_DEFAULT, 0, {SCHEDULE_CONFIG_PACKET_INIT_DEFAULT}}
#define TIME_WINDOW_INIT_ZERO                    {0, 0}
#define SAMPLING_CONFIG_INIT_ZERO                {0, 0}
#define GPS_CONFIG_INIT_ZERO                     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define RADIO_OTAA_INIT_ZERO                     {{0}, {0}, {0}, {0}}
#define RADIO_ABP_INIT_ZERO                      {{0}, {0}, {0}, {0}, {0}}
#define LO_RA_WAN_CONFIG_INIT_ZERO               {_RADIO_REGION_MIN, _RADIO_AUTH_MIN, 0, {RADIO_OTAA_INIT_ZERO}, 0, 0, 0}
#define LO_RA_CONFIG_INIT_ZERO                   {_RADIO_SPREADING_FACTOR_MIN, _RADIO_BANDWIDTH_MIN, _RADIO_CODING_RATE_MIN, 0, 0, 0}
#define LOST_MODE_CONFIG_INIT_ZERO               {0, 0, 0}
#define MORTALITY_CONFIG_INIT_ZERO               {0, 0}
#define RADIO_CONFIG_PACKET_INIT_ZERO            {false, LO_RA_WAN_CONFIG_INIT_ZERO, false, LO_RA_CONFIG_INIT_ZERO, 0, false, LOST_MODE_CONFIG_INIT_ZERO, 0, false, MORTALITY_CONFIG_INIT_ZERO}
#define MICROPHONE_CONFIG_INIT_ZERO              {0, 0, 0, 0}
#define ACCELEROMETER_CONFIG_INIT_ZERO           {0, _ACCEL_SAMPLE_RATE_MIN, _ACCEL_SENSITIVITY_MIN}
#define MAGNETOMETER_CONFIG_INIT_ZERO            {0, 0}
#define SCHEDULE_CONFIG_INIT_ZERO                {false, TIME_WINDOW_INIT_ZERO, false, SAMPLING_CONFIG_INIT_ZERO, false, SAMPLING_CONFIG_INIT_ZERO, false, SAMPLING_CONFIG_INIT_ZERO, false, GPS_CONFIG_INIT_ZERO, false, MICROPHONE_CONFIG_INIT_ZERO, false, ACCELEROMETER_CONFIG_INIT_ZERO, 0, 0, 0, 0, false, MAGNETOMETER_CONFIG_INIT_ZERO}
#define SCHEDULE_CONFIG_PACKET_INIT_ZERO         {0, 0, {SCHEDULE_CONFIG_INIT_ZERO, SCHEDULE_CONFIG_INIT_ZERO, SCHEDULE_CONFIG_INIT_ZERO, SCHEDULE_CONFIG_INIT_ZERO, SCHEDULE_CONFIG_INIT_ZERO}, 0}
#define SIMPLE_SENSOR_READING_INIT_ZERO          {0, 0, 0, 0, 0, 0, 0, _ACTIVITY_MIN, 0, 0, 0, 0}
#define SYSTEM_STATE_PACKET_INIT_ZERO            {0, false, BATTERY_STATE_INIT_ZERO, false, SD_CARD_STATE_INIT_ZERO, false, GPS_DATA_INIT_ZERO, false, SIMPLE_SENSOR_READING_INIT_ZERO, "", false, 0}
#define PERIPHERAL_PACKET_INIT_ZERO              {{0}, _PERIPHERAL_TYPE_MIN}
#define PERIPHERAL_INFO_INIT_ZERO                {{{NULL}, NULL}}
#define BLE_PACKET_INIT_ZERO                     {false, PACKET_HEADER_INIT_ZERO, 0, {SCHEDULE_CONFIG_PACKET_INIT_ZERO}}

/* Field tags (for use in manual encoding/decoding) */
#define TIME_WINDOW_START_HOUR_TAG               1
#define TIME_WINDOW_END_HOUR_TAG                 2
#define SAMPLING_CONFIG_ENABLED_TAG              1
#define SAMPLING_CONFIG_SAMPLE_INTERVAL_MIN_TAG  2
#define GPS_CONFIG_ENABLED_TAG                   1
#define GPS_CONFIG_SAMPLE_INTERVAL_MIN_TAG       2
#define GPS_CONFIG_ACCURACY_TAG                  3
#define GPS_CONFIG_DYNAMIC_SAMPLING_MODE_TAG     4
#define GPS_CONFIG_MEDIUM_MOTION_VEDBA_THRESHOLD_X100_TAG 5
#define GPS_CONFIG_MEDIUM_MOTION_GPS_INTERVAL_MIN_TAG 6
#define GPS_CONFIG_HIGH_MOTION_VEDBA_THRESHOLD_X100_TAG 7
#define GPS_CONFIG_HIGH_MOTION_GPS_INTERVAL_MIN_TAG 8
#define GPS_CONFIG_LORAWAN_TX_ON_GPS_FIX_TAG     9
#define GPS_CONFIG_LORA_TX_ON_GPS_FIX_TAG        10
#define RADIO_OTAA_DEV_EUI_TAG                   1
#define RADIO_OTAA_JOIN_EUI_TAG                  2
#define RADIO_OTAA_APP_KEY_TAG                   3
#define RADIO_OTAA_NWK_KEY_TAG                   4
#define RADIO_ABP_DEV_ADDR_TAG                   1
#define RADIO_ABP_NWK_S_KEY_TAG                  2
#define RADIO_ABP_APP_S_KEY_TAG                  3
#define RADIO_ABP_F_NWK_S_INT_KEY_TAG            4
#define RADIO_ABP_S_NWK_S_INT_KEY_TAG            5
#define LO_RA_WAN_CONFIG_REGION_TAG              1
#define LO_RA_WAN_CONFIG_AUTH_TAG                2
#define LO_RA_WAN_CONFIG_OTAA_TAG                3
#define LO_RA_WAN_CONFIG_ABP_TAG                 4
#define LO_RA_WAN_CONFIG_TRANSMIT_INTERVAL_MIN_TAG 5
#define LO_RA_WAN_CONFIG_TX_ONLY_ON_NEW_GPS_FIX_TAG 6
#define LO_RA_WAN_CONFIG_TX_POWER_DBM_TAG        7
#define LO_RA_CONFIG_RADIO_SPREADING_FACTOR_TAG  1
#define LO_RA_CONFIG_RADIO_BANDWIDTH_TAG         2
#define LO_RA_CONFIG_RADIO_CODING_RATE_TAG       3
#define LO_RA_CONFIG_TX_POWER_DBM_TAG            4
#define LO_RA_CONFIG_SYNC_WORD_TAG               5
#define LO_RA_CONFIG_FREQUENCY_TAG               6
#define LOST_MODE_CONFIG_ACTIVATION_EPOCH_TAG    1
#define LOST_MODE_CONFIG_TRANSMIT_INTERVAL_MIN_TAG 2
#define LOST_MODE_CONFIG_TX_POWER_DBM_TAG        3
#define MORTALITY_CONFIG_TRIGGER_DURATION_HOURS_TAG 1
#define MORTALITY_CONFIG_TRANSMIT_INTERVAL_MIN_TAG 2
#define RADIO_CONFIG_PACKET_LO_RA_WAN_CONFIG_TAG 1
#define RADIO_CONFIG_PACKET_LO_RA_CONFIG_TAG     2
#define RADIO_CONFIG_PACKET_LOST_MODE_ENABLED_TAG 3
#define RADIO_CONFIG_PACKET_LOST_MODE_CONFIG_TAG 4
#define RADIO_CONFIG_PACKET_MORTALITY_ENABLED_TAG 5
#define RADIO_CONFIG_PACKET_MORTALITY_CONFIG_TAG 6
#define MICROPHONE_CONFIG_ENABLED_TAG            1
#define MICROPHONE_CONFIG_CONTINUOUS_MODE_TAG    2
#define MICROPHONE_CONFIG_SAMPLE_LENGTH_MIN_TAG  3
#define MICROPHONE_CONFIG_SAMPLE_WINDOW_MIN_TAG  4
#define ACCELEROMETER_CONFIG_ENABLED_TAG         1
#define ACCELEROMETER_CONFIG_SAMPLE_RATE_TAG     2
#define ACCELEROMETER_CONFIG_SENSITIVITY_TAG     3
#define MAGNETOMETER_CONFIG_ENABLED_TAG          1
#define MAGNETOMETER_CONFIG_SAMPLE_INTERVAL_S_TAG 2
#define SCHEDULE_CONFIG_WINDOW_TAG               1
#define SCHEDULE_CONFIG_LIGHT_TAG                2
#define SCHEDULE_CONFIG_ENVIRONMENTAL_TAG        3
#define SCHEDULE_CONFIG_PARTICULATE_TAG          4
#define SCHEDULE_CONFIG_GPS_TAG                  5
#define SCHEDULE_CONFIG_MICROPHONE_TAG           6
#define SCHEDULE_CONFIG_ACCELEROMETER_TAG        7
#define SCHEDULE_CONFIG_LORAWAN_ENABLED_TAG      8
#define SCHEDULE_CONFIG_LORAWAN_SEND_INTERVAL_MIN_TAG 9
#define SCHEDULE_CONFIG_LORA_ENABLED_TAG         10
#define SCHEDULE_CONFIG_LORA_SEND_INTERVAL_MIN_TAG 11
#define SCHEDULE_CONFIG_MAGNETOMETER_TAG         12
#define SCHEDULE_CONFIG_PACKET_ENGAGED_TAG       1
#define SCHEDULE_CONFIG_PACKET_SCHEDULES_TAG     2
#define SCHEDULE_CONFIG_PACKET_SPECIAL_MODE_TAG  3
#define SIMPLE_SENSOR_READING_INDEX_TAG          1
#define SIMPLE_SENSOR_READING_TEMPERATURE_TAG    2
#define SIMPLE_SENSOR_READING_HUMIDITY_TAG       3
#define SIMPLE_SENSOR_READING_PRESSURE_TAG       4
#define SIMPLE_SENSOR_READING_GAS_TAG            5
#define SIMPLE_SENSOR_READING_PM2_5_TAG          6
#define SIMPLE_SENSOR_READING_LIGHT_TAG          7
#define SIMPLE_SENSOR_READING_ACTIVITY_TAG       8
#define SIMPLE_SENSOR_READING_STEPS_TAG          9
#define SIMPLE_SENSOR_READING_PARTICULATE_STATIC_OBSTRUCTED_TAG 10
#define SIMPLE_SENSOR_READING_PARTICULATE_DYNAMIC_OBSTRUCTED_TAG 11
#define SIMPLE_SENSOR_READING_PARTICULATE_OUTSIDE_DETECTION_LIMITS_TAG 12
#define SYSTEM_STATE_PACKET_ENGAGE_STATE_TAG     1
#define SYSTEM_STATE_PACKET_BATTERY_TAG          2
#define SYSTEM_STATE_PACKET_SDCARD_TAG           3
#define SYSTEM_STATE_PACKET_GPS_DATA_TAG         4
#define SYSTEM_STATE_PACKET_SENSORS_TAG          5
#define SYSTEM_STATE_PACKET_FIRMWARE_VERSION_TAG 6
#define SYSTEM_STATE_PACKET_HW_DIAG_TAG          7
#define PERIPHERAL_PACKET_MAC_ADDRESS_TAG        1
#define PERIPHERAL_PACKET_TYPE_TAG               2
#define PERIPHERAL_INFO_DEVICE_UIDS_TAG          1
#define BLE_PACKET_HEADER_TAG                    1
#define BLE_PACKET_SCHEDULE_CONFIG_PACKET_TAG    2
#define BLE_PACKET_SYSTEM_STATE_PACKET_TAG       3
#define BLE_PACKET_RADIO_CONFIG_PACKET_TAG       4
#define BLE_PACKET_PERIPHERAL_PACKET_TAG         5
#define BLE_PACKET_PERIPHERAL_INFO_TAG           6

/* Struct field encoding specification for nanopb */
#define TIME_WINDOW_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   start_hour,        1) \
X(a, STATIC,   SINGULAR, UINT32,   end_hour,          2)
#define TIME_WINDOW_CALLBACK NULL
#define TIME_WINDOW_DEFAULT NULL

#define SAMPLING_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, UINT32,   sample_interval_min,   2)
#define SAMPLING_CONFIG_CALLBACK NULL
#define SAMPLING_CONFIG_DEFAULT NULL

#define GPS_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, UINT32,   sample_interval_min,   2) \
X(a, STATIC,   SINGULAR, UINT32,   accuracy,          3) \
X(a, STATIC,   SINGULAR, BOOL,     dynamic_sampling_mode,   4) \
X(a, STATIC,   SINGULAR, UINT32,   medium_motion_vedba_threshold_x100,   5) \
X(a, STATIC,   SINGULAR, UINT32,   medium_motion_gps_interval_min,   6) \
X(a, STATIC,   SINGULAR, UINT32,   high_motion_vedba_threshold_x100,   7) \
X(a, STATIC,   SINGULAR, UINT32,   high_motion_gps_interval_min,   8) \
X(a, STATIC,   SINGULAR, BOOL,     lorawan_tx_on_gps_fix,   9) \
X(a, STATIC,   SINGULAR, BOOL,     lora_tx_on_gps_fix,  10)
#define GPS_CONFIG_CALLBACK NULL
#define GPS_CONFIG_DEFAULT NULL

#define RADIO_OTAA_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, dev_eui,           1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, join_eui,          2) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, app_key,           3) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, nwk_key,           4)
#define RADIO_OTAA_CALLBACK NULL
#define RADIO_OTAA_DEFAULT NULL

#define RADIO_ABP_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, dev_addr,          1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, nwk_s_key,         2) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, app_s_key,         3) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, f_nwk_s_int_key,   4) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, s_nwk_s_int_key,   5)
#define RADIO_ABP_CALLBACK NULL
#define RADIO_ABP_DEFAULT NULL

#define LO_RA_WAN_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    region,            1) \
X(a, STATIC,   SINGULAR, UENUM,    auth,              2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (credentials,otaa,credentials.otaa),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (credentials,abp,credentials.abp),   4) \
X(a, STATIC,   SINGULAR, UINT32,   transmit_interval_min,   5) \
X(a, STATIC,   SINGULAR, BOOL,     tx_only_on_new_gps_fix,   6) \
X(a, STATIC,   SINGULAR, INT32,    tx_power_dbm,      7)
#define LO_RA_WAN_CONFIG_CALLBACK NULL
#define LO_RA_WAN_CONFIG_DEFAULT NULL
#define lo_ra_wan_config_t_credentials_otaa_MSGTYPE radio_otaa_t
#define lo_ra_wan_config_t_credentials_abp_MSGTYPE radio_abp_t

#define LO_RA_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    radio_spreading_factor,   1) \
X(a, STATIC,   SINGULAR, UENUM,    radio_bandwidth,   2) \
X(a, STATIC,   SINGULAR, UENUM,    radio_coding_rate,   3) \
X(a, STATIC,   SINGULAR, INT32,    tx_power_dbm,      4) \
X(a, STATIC,   SINGULAR, UINT32,   sync_word,         5) \
X(a, STATIC,   SINGULAR, UINT32,   frequency,         6)
#define LO_RA_CONFIG_CALLBACK NULL
#define LO_RA_CONFIG_DEFAULT NULL

#define LOST_MODE_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   activation_epoch,   1) \
X(a, STATIC,   SINGULAR, UINT32,   transmit_interval_min,   2) \
X(a, STATIC,   SINGULAR, INT32,    tx_power_dbm,      3)
#define LOST_MODE_CONFIG_CALLBACK NULL
#define LOST_MODE_CONFIG_DEFAULT NULL

#define MORTALITY_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   trigger_duration_hours,   1) \
X(a, STATIC,   SINGULAR, UINT32,   transmit_interval_min,   2)
#define MORTALITY_CONFIG_CALLBACK NULL
#define MORTALITY_CONFIG_DEFAULT NULL

#define RADIO_CONFIG_PACKET_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  lo_ra_wan_config,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  lo_ra_config,      2) \
X(a, STATIC,   SINGULAR, BOOL,     lost_mode_enabled,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  lost_mode_config,   4) \
X(a, STATIC,   SINGULAR, BOOL,     mortality_enabled,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mortality_config,   6)
#define RADIO_CONFIG_PACKET_CALLBACK NULL
#define RADIO_CONFIG_PACKET_DEFAULT NULL
#define radio_config_packet_t_lo_ra_wan_config_MSGTYPE lo_ra_wan_config_t
#define radio_config_packet_t_lo_ra_config_MSGTYPE lo_ra_config_t
#define radio_config_packet_t_lost_mode_config_MSGTYPE lost_mode_config_t
#define radio_config_packet_t_mortality_config_MSGTYPE mortality_config_t

#define MICROPHONE_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, BOOL,     continuous_mode,   2) \
X(a, STATIC,   SINGULAR, UINT32,   sample_length_min,   3) \
X(a, STATIC,   SINGULAR, UINT32,   sample_window_min,   4)
#define MICROPHONE_CONFIG_CALLBACK NULL
#define MICROPHONE_CONFIG_DEFAULT NULL

#define ACCELEROMETER_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, UENUM,    sample_rate,       2) \
X(a, STATIC,   SINGULAR, UENUM,    sensitivity,       3)
#define ACCELEROMETER_CONFIG_CALLBACK NULL
#define ACCELEROMETER_CONFIG_DEFAULT NULL

#define MAGNETOMETER_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, UINT32,   sample_interval_s,   2)
#define MAGNETOMETER_CONFIG_CALLBACK NULL
#define MAGNETOMETER_CONFIG_DEFAULT NULL

#define SCHEDULE_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  window,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  light,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  environmental,     3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  particulate,       4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gps,               5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  microphone,        6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  accelerometer,     7) \
X(a, STATIC,   SINGULAR, BOOL,     lorawan_enabled,   8) \
X(a, STATIC,   SINGULAR, UINT32,   lorawan_send_interval_min,   9) \
X(a, STATIC,   SINGULAR, BOOL,     lora_enabled,     10) \
X(a, STATIC,   SINGULAR, UINT32,   lora_send_interval_min,  11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  magnetometer,     12)
#define SCHEDULE_CONFIG_CALLBACK NULL
#define SCHEDULE_CONFIG_DEFAULT NULL
#define schedule_config_t_window_MSGTYPE time_window_t
#define schedule_config_t_light_MSGTYPE sampling_config_t
#define schedule_config_t_environmental_MSGTYPE sampling_config_t
#define schedule_config_t_particulate_MSGTYPE sampling_config_t
#define schedule_config_t_gps_MSGTYPE gps_config_t
#define schedule_config_t_microphone_MSGTYPE microphone_config_t
#define schedule_config_t_accelerometer_MSGTYPE accelerometer_config_t
#define schedule_config_t_magnetometer_MSGTYPE magnetometer_config_t

#define SCHEDULE_CONFIG_PACKET_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     engaged,           1) \
X(a, STATIC,   REPEATED, MESSAGE,  schedules,         2) \
X(a, STATIC,   SINGULAR, UINT32,   special_mode,      3)
#define SCHEDULE_CONFIG_PACKET_CALLBACK NULL
#define SCHEDULE_CONFIG_PACKET_DEFAULT NULL
#define schedule_config_packet_t_schedules_MSGTYPE schedule_config_t

#define SIMPLE_SENSOR_READING_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   index,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          3) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure,          4) \
X(a, STATIC,   SINGULAR, FLOAT,    gas,               5) \
X(a, STATIC,   SINGULAR, FLOAT,    pm2_5,             6) \
X(a, STATIC,   SINGULAR, UINT32,   light,             7) \
X(a, STATIC,   SINGULAR, UENUM,    activity,          8) \
X(a, STATIC,   SINGULAR, UINT32,   steps,             9) \
X(a, STATIC,   SINGULAR, BOOL,     particulate_static_obstructed,  10) \
X(a, STATIC,   SINGULAR, BOOL,     particulate_dynamic_obstructed,  11) \
X(a, STATIC,   SINGULAR, BOOL,     particulate_outside_detection_limits,  12)
#define SIMPLE_SENSOR_READING_CALLBACK NULL
#define SIMPLE_SENSOR_READING_DEFAULT NULL

#define SYSTEM_STATE_PACKET_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     engage_state,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  battery,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sdcard,            3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gps_data,          4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sensors,           5) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   6) \
X(a, STATIC,   OPTIONAL, UINT32,   hw_diag,           7)
#define SYSTEM_STATE_PACKET_CALLBACK NULL
#define SYSTEM_STATE_PACKET_DEFAULT NULL
#define system_state_packet_t_battery_MSGTYPE battery_state_t
#define system_state_packet_t_sdcard_MSGTYPE sd_card_state_t
#define system_state_packet_t_gps_data_MSGTYPE gps_data_t
#define system_state_packet_t_sensors_MSGTYPE simple_sensor_reading_t

#define PERIPHERAL_PACKET_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, mac_address,       1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2)
#define PERIPHERAL_PACKET_CALLBACK NULL
#define PERIPHERAL_PACKET_DEFAULT NULL

#define PERIPHERAL_INFO_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   device_uids,       1)
#define PERIPHERAL_INFO_CALLBACK pb_default_field_callback
#define PERIPHERAL_INFO_DEFAULT NULL

#define BLE_PACKET_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,schedule_config_packet,payload.schedule_config_packet),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,system_state_packet,payload.system_state_packet),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,radio_config_packet,payload.radio_config_packet),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,peripheral_packet,payload.peripheral_packet),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,peripheral_info,payload.peripheral_info),   6)
#define BLE_PACKET_CALLBACK NULL
#define BLE_PACKET_DEFAULT NULL
#define ble_packet_t_header_MSGTYPE packet_header_t
#define ble_packet_t_payload_schedule_config_packet_MSGTYPE schedule_config_packet_t
#define ble_packet_t_payload_system_state_packet_MSGTYPE system_state_packet_t
#define ble_packet_t_payload_radio_config_packet_MSGTYPE radio_config_packet_t
#define ble_packet_t_payload_peripheral_packet_MSGTYPE peripheral_packet_t
#define ble_packet_t_payload_peripheral_info_MSGTYPE peripheral_info_t

extern const pb_msgdesc_t time_window_t_msg;
extern const pb_msgdesc_t sampling_config_t_msg;
extern const pb_msgdesc_t gps_config_t_msg;
extern const pb_msgdesc_t radio_otaa_t_msg;
extern const pb_msgdesc_t radio_abp_t_msg;
extern const pb_msgdesc_t lo_ra_wan_config_t_msg;
extern const pb_msgdesc_t lo_ra_config_t_msg;
extern const pb_msgdesc_t lost_mode_config_t_msg;
extern const pb_msgdesc_t mortality_config_t_msg;
extern const pb_msgdesc_t radio_config_packet_t_msg;
extern const pb_msgdesc_t microphone_config_t_msg;
extern const pb_msgdesc_t accelerometer_config_t_msg;
extern const pb_msgdesc_t magnetometer_config_t_msg;
extern const pb_msgdesc_t schedule_config_t_msg;
extern const pb_msgdesc_t schedule_config_packet_t_msg;
extern const pb_msgdesc_t simple_sensor_reading_t_msg;
extern const pb_msgdesc_t system_state_packet_t_msg;
extern const pb_msgdesc_t peripheral_packet_t_msg;
extern const pb_msgdesc_t peripheral_info_t_msg;
extern const pb_msgdesc_t ble_packet_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TIME_WINDOW_FIELDS &time_window_t_msg
#define SAMPLING_CONFIG_FIELDS &sampling_config_t_msg
#define GPS_CONFIG_FIELDS &gps_config_t_msg
#define RADIO_OTAA_FIELDS &radio_otaa_t_msg
#define RADIO_ABP_FIELDS &radio_abp_t_msg
#define LO_RA_WAN_CONFIG_FIELDS &lo_ra_wan_config_t_msg
#define LO_RA_CONFIG_FIELDS &lo_ra_config_t_msg
#define LOST_MODE_CONFIG_FIELDS &lost_mode_config_t_msg
#define MORTALITY_CONFIG_FIELDS &mortality_config_t_msg
#define RADIO_CONFIG_PACKET_FIELDS &radio_config_packet_t_msg
#define MICROPHONE_CONFIG_FIELDS &microphone_config_t_msg
#define ACCELEROMETER_CONFIG_FIELDS &accelerometer_config_t_msg
#define MAGNETOMETER_CONFIG_FIELDS &magnetometer_config_t_msg
#define SCHEDULE_CONFIG_FIELDS &schedule_config_t_msg
#define SCHEDULE_CONFIG_PACKET_FIELDS &schedule_config_packet_t_msg
#define SIMPLE_SENSOR_READING_FIELDS &simple_sensor_reading_t_msg
#define SYSTEM_STATE_PACKET_FIELDS &system_state_packet_t_msg
#define PERIPHERAL_PACKET_FIELDS &peripheral_packet_t_msg
#define PERIPHERAL_INFO_FIELDS &peripheral_info_t_msg
#define BLE_PACKET_FIELDS &ble_packet_t_msg

/* Maximum encoded size of messages (where known) */
/* PeripheralInfo_size depends on runtime parameters */
/* BlePacket_size depends on runtime parameters */
#define ACCELEROMETER_CONFIG_SIZE                6
#define GPS_CONFIG_SIZE                          44
#define LOST_MODE_CONFIG_SIZE                    23
#define LO_RA_CONFIG_SIZE                        29
#define LO_RA_WAN_CONFIG_SIZE                    103
#define MAGNETOMETER_CONFIG_SIZE                 8
#define MICROPHONE_CONFIG_SIZE                   16
#define MORTALITY_CONFIG_SIZE                    12
#define PERIPHERAL_PACKET_SIZE                   10
#define RADIO_ABP_SIZE                           78
#define RADIO_CONFIG_PACKET_SIZE                 179
#define RADIO_OTAA_SIZE                          56
#define SAMPLING_CONFIG_SIZE                     8
#define SCHEDULE_CONFIG_PACKET_SIZE              733
#define SCHEDULE_CONFIG_SIZE                     142
#define SIMPLE_SENSOR_READING_SIZE               51
#define SYSTEM_STATE_PACKET_SIZE                 145
#define TIME_WINDOW_SIZE                         12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
