// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ble.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum RadioRegion: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case regionUs915 // = 0
  case regionAu915 // = 1
  case regionEu868 // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .regionUs915
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .regionUs915
    case 1: self = .regionAu915
    case 2: self = .regionEu868
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .regionUs915: return 0
    case .regionAu915: return 1
    case .regionEu868: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [RadioRegion] = [
    .regionUs915,
    .regionAu915,
    .regionEu868,
  ]

}

enum RadioAuth: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case authOtaa // = 0
  case authAbp // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .authOtaa
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .authOtaa
    case 1: self = .authAbp
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .authOtaa: return 0
    case .authAbp: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [RadioAuth] = [
    .authOtaa,
    .authAbp,
  ]

}

enum RadioSpreadingFactor: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case sf7 // = 0
  case sf8 // = 1
  case sf9 // = 2
  case sf10 // = 3
  case sf11 // = 4
  case sf12 // = 5
  case UNRECOGNIZED(Int)

  init() {
    self = .sf7
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .sf7
    case 1: self = .sf8
    case 2: self = .sf9
    case 3: self = .sf10
    case 4: self = .sf11
    case 5: self = .sf12
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .sf7: return 0
    case .sf8: return 1
    case .sf9: return 2
    case .sf10: return 3
    case .sf11: return 4
    case .sf12: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [RadioSpreadingFactor] = [
    .sf7,
    .sf8,
    .sf9,
    .sf10,
    .sf11,
    .sf12,
  ]

}

enum RadioBandwidth: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case bw125 // = 0
  case bw250 // = 1
  case bw500 // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .bw125
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .bw125
    case 1: self = .bw250
    case 2: self = .bw500
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .bw125: return 0
    case .bw250: return 1
    case .bw500: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [RadioBandwidth] = [
    .bw125,
    .bw250,
    .bw500,
  ]

}

enum RadioCodingRate: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case cr45 // = 0
  case cr46 // = 1
  case cr47 // = 2
  case cr48 // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .cr45
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .cr45
    case 1: self = .cr46
    case 2: self = .cr47
    case 3: self = .cr48
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .cr45: return 0
    case .cr46: return 1
    case .cr47: return 2
    case .cr48: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [RadioCodingRate] = [
    .cr45,
    .cr46,
    .cr47,
    .cr48,
  ]

}

enum AccelSampleRate: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case accel25Hz // = 0
  case accel50Hz // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .accel25Hz
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .accel25Hz
    case 1: self = .accel50Hz
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .accel25Hz: return 0
    case .accel50Hz: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [AccelSampleRate] = [
    .accel25Hz,
    .accel50Hz,
  ]

}

enum AccelSensitivity: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case accel2G // = 0
  case accel4G // = 1
  case accel8G // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .accel2G
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .accel2G
    case 1: self = .accel4G
    case 2: self = .accel8G
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .accel2G: return 0
    case .accel4G: return 1
    case .accel8G: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [AccelSensitivity] = [
    .accel2G,
    .accel4G,
    .accel8G,
  ]

}

enum PeripheralType: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case peripheralSatcom // = 0
  case peripheralDetachment // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .peripheralSatcom
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .peripheralSatcom
    case 1: self = .peripheralDetachment
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .peripheralSatcom: return 0
    case .peripheralDetachment: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [PeripheralType] = [
    .peripheralSatcom,
    .peripheralDetachment,
  ]

}

/// ================== SCHEDULING / CONFIG ==================
struct TimeWindow: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 0 to 23 (inclusive)
  var startHour: UInt32 = 0

  /// 0 to 23 (inclusive)
  var endHour: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Enabled/disabled and sample interval for each sensor
struct SamplingConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var enabled: Bool = false

  /// minutes
  var sampleIntervalMin: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct GPSConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var enabled: Bool = false

  var sampleIntervalMin: UInt32 = 0

  /// 1 to 10
  var accuracy: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct RadioOTAA: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 8, fixed_length
  var devEui: Data = Data()

  /// 8, fixed_length
  var joinEui: Data = Data()

  /// 16, fixed_length
  var appKey: Data = Data()

  /// 16, fixed_length
  var nwkKey: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct RadioABP: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 4,  fixed_length
  var devAddr: Data = Data()

  /// 16, fixed_length
  var nwkSKey: Data = Data()

  /// 16, fixed_length
  var appSKey: Data = Data()

  /// 16, fixed_length
  var fNwkSIntKey: Data = Data()

  /// 16, fixed_length
  var sNwkSIntKey: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct LoRaWANConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var region: RadioRegion = .regionUs915

  var auth: RadioAuth = .authOtaa

  var credentials: LoRaWANConfig.OneOf_Credentials? = nil

  var otaa: RadioOTAA {
    get {
      if case .otaa(let v)? = credentials {return v}
      return RadioOTAA()
    }
    set {credentials = .otaa(newValue)}
  }

  var abp: RadioABP {
    get {
      if case .abp(let v)? = credentials {return v}
      return RadioABP()
    }
    set {credentials = .abp(newValue)}
  }

  var transmitIntervalMin: UInt32 = 0

  var txOnlyOnNewGpsFix: Bool = false

  var txPowerDbm: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Credentials: Equatable, Sendable {
    case otaa(RadioOTAA)
    case abp(RadioABP)

  }

  init() {}
}

struct LoRaConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var radioSpreadingFactor: RadioSpreadingFactor = .sf7

  var radioBandwidth: RadioBandwidth = .bw125

  var radioCodingRate: RadioCodingRate = .cr45

  var txPowerDbm: Int32 = 0

  ///byte value
  var syncWord: UInt32 = 0

  var frequency: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct LostMode_config: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var activationEpoch: UInt32 = 0

  var transmitIntervalMin: UInt32 = 0

  var txPowerDbm: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct RadioConfigPacket: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var loRaWanConfig: LoRaWANConfig {
    get {return _storage._loRaWanConfig ?? LoRaWANConfig()}
    set {_uniqueStorage()._loRaWanConfig = newValue}
  }
  /// Returns true if `loRaWanConfig` has been explicitly set.
  var hasLoRaWanConfig: Bool {return _storage._loRaWanConfig != nil}
  /// Clears the value of `loRaWanConfig`. Subsequent reads from it will return its default value.
  mutating func clearLoRaWanConfig() {_uniqueStorage()._loRaWanConfig = nil}

  var loRaConfig: LoRaConfig {
    get {return _storage._loRaConfig ?? LoRaConfig()}
    set {_uniqueStorage()._loRaConfig = newValue}
  }
  /// Returns true if `loRaConfig` has been explicitly set.
  var hasLoRaConfig: Bool {return _storage._loRaConfig != nil}
  /// Clears the value of `loRaConfig`. Subsequent reads from it will return its default value.
  mutating func clearLoRaConfig() {_uniqueStorage()._loRaConfig = nil}

  var lostModeEnabled: Bool {
    get {return _storage._lostModeEnabled}
    set {_uniqueStorage()._lostModeEnabled = newValue}
  }

  var lostModeConfig: LostMode_config {
    get {return _storage._lostModeConfig ?? LostMode_config()}
    set {_uniqueStorage()._lostModeConfig = newValue}
  }
  /// Returns true if `lostModeConfig` has been explicitly set.
  var hasLostModeConfig: Bool {return _storage._lostModeConfig != nil}
  /// Clears the value of `lostModeConfig`. Subsequent reads from it will return its default value.
  mutating func clearLostModeConfig() {_uniqueStorage()._lostModeConfig = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct MicrophoneConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var enabled: Bool = false

  /// on if true
  var continuousMode: Bool = false

  var sampleLengthMin: UInt32 = 0

  var sampleWindowMin: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct AccelerometerConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var enabled: Bool = false

  var sampleRate: AccelSampleRate = .accel25Hz

  var sensitivity: AccelSensitivity = .accel2G

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct MagnetometerConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var enabled: Bool = false

  /// in seconds
  var sampleIntervalS: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// schedule that is applied during each TimeWindow
struct ScheduleConfig: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var window: TimeWindow {
    get {return _storage._window ?? TimeWindow()}
    set {_uniqueStorage()._window = newValue}
  }
  /// Returns true if `window` has been explicitly set.
  var hasWindow: Bool {return _storage._window != nil}
  /// Clears the value of `window`. Subsequent reads from it will return its default value.
  mutating func clearWindow() {_uniqueStorage()._window = nil}

  var light: SamplingConfig {
    get {return _storage._light ?? SamplingConfig()}
    set {_uniqueStorage()._light = newValue}
  }
  /// Returns true if `light` has been explicitly set.
  var hasLight: Bool {return _storage._light != nil}
  /// Clears the value of `light`. Subsequent reads from it will return its default value.
  mutating func clearLight() {_uniqueStorage()._light = nil}

  var environmental: SamplingConfig {
    get {return _storage._environmental ?? SamplingConfig()}
    set {_uniqueStorage()._environmental = newValue}
  }
  /// Returns true if `environmental` has been explicitly set.
  var hasEnvironmental: Bool {return _storage._environmental != nil}
  /// Clears the value of `environmental`. Subsequent reads from it will return its default value.
  mutating func clearEnvironmental() {_uniqueStorage()._environmental = nil}

  var particulate: SamplingConfig {
    get {return _storage._particulate ?? SamplingConfig()}
    set {_uniqueStorage()._particulate = newValue}
  }
  /// Returns true if `particulate` has been explicitly set.
  var hasParticulate: Bool {return _storage._particulate != nil}
  /// Clears the value of `particulate`. Subsequent reads from it will return its default value.
  mutating func clearParticulate() {_uniqueStorage()._particulate = nil}

  var gps: GPSConfig {
    get {return _storage._gps ?? GPSConfig()}
    set {_uniqueStorage()._gps = newValue}
  }
  /// Returns true if `gps` has been explicitly set.
  var hasGps: Bool {return _storage._gps != nil}
  /// Clears the value of `gps`. Subsequent reads from it will return its default value.
  mutating func clearGps() {_uniqueStorage()._gps = nil}

  var microphone: MicrophoneConfig {
    get {return _storage._microphone ?? MicrophoneConfig()}
    set {_uniqueStorage()._microphone = newValue}
  }
  /// Returns true if `microphone` has been explicitly set.
  var hasMicrophone: Bool {return _storage._microphone != nil}
  /// Clears the value of `microphone`. Subsequent reads from it will return its default value.
  mutating func clearMicrophone() {_uniqueStorage()._microphone = nil}

  var accelerometer: AccelerometerConfig {
    get {return _storage._accelerometer ?? AccelerometerConfig()}
    set {_uniqueStorage()._accelerometer = newValue}
  }
  /// Returns true if `accelerometer` has been explicitly set.
  var hasAccelerometer: Bool {return _storage._accelerometer != nil}
  /// Clears the value of `accelerometer`. Subsequent reads from it will return its default value.
  mutating func clearAccelerometer() {_uniqueStorage()._accelerometer = nil}

  /// LoRaWAN behavior within this schedule
  var lorawanEnabled: Bool {
    get {return _storage._lorawanEnabled}
    set {_uniqueStorage()._lorawanEnabled = newValue}
  }

  var lorawanSendIntervalMin: UInt32 {
    get {return _storage._lorawanSendIntervalMin}
    set {_uniqueStorage()._lorawanSendIntervalMin = newValue}
  }

  var loraEnabled: Bool {
    get {return _storage._loraEnabled}
    set {_uniqueStorage()._loraEnabled = newValue}
  }

  var loraSendIntervalMin: UInt32 {
    get {return _storage._loraSendIntervalMin}
    set {_uniqueStorage()._loraSendIntervalMin = newValue}
  }

  var magnetometer: MagnetometerConfig {
    get {return _storage._magnetometer ?? MagnetometerConfig()}
    set {_uniqueStorage()._magnetometer = newValue}
  }
  /// Returns true if `magnetometer` has been explicitly set.
  var hasMagnetometer: Bool {return _storage._magnetometer != nil}
  /// Clears the value of `magnetometer`. Subsequent reads from it will return its default value.
  mutating func clearMagnetometer() {_uniqueStorage()._magnetometer = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// can include multiple schedules
struct ScheduleConfigPacket: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var engaged: Bool = false

  /// capped to 5 schedules in options
  var schedules: [ScheduleConfig] = []

  var specialMode: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct SimpleSensorReading: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var index: UInt32 = 0

  var temperature: Float = 0

  var humidity: Float = 0

  var pressure: Float = 0

  var gas: Float = 0

  var pm25: Float = 0

  var light: UInt32 = 0

  var activity: Activity = .still

  var steps: UInt32 = 0

  var particulateStaticObstructed: Bool = false

  var particulateDynamicObstructed: Bool = false

  var particulateOutsideDetectionLimits: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct SystemStatePacket: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// engaged/disengaged
  var engageState: Bool {
    get {return _storage._engageState}
    set {_uniqueStorage()._engageState = newValue}
  }

  var battery: BatteryState {
    get {return _storage._battery ?? BatteryState()}
    set {_uniqueStorage()._battery = newValue}
  }
  /// Returns true if `battery` has been explicitly set.
  var hasBattery: Bool {return _storage._battery != nil}
  /// Clears the value of `battery`. Subsequent reads from it will return its default value.
  mutating func clearBattery() {_uniqueStorage()._battery = nil}

  var sdcard: SDCardState {
    get {return _storage._sdcard ?? SDCardState()}
    set {_uniqueStorage()._sdcard = newValue}
  }
  /// Returns true if `sdcard` has been explicitly set.
  var hasSdcard: Bool {return _storage._sdcard != nil}
  /// Clears the value of `sdcard`. Subsequent reads from it will return its default value.
  mutating func clearSdcard() {_uniqueStorage()._sdcard = nil}

  var gpsData: GPSData {
    get {return _storage._gpsData ?? GPSData()}
    set {_uniqueStorage()._gpsData = newValue}
  }
  /// Returns true if `gpsData` has been explicitly set.
  var hasGpsData: Bool {return _storage._gpsData != nil}
  /// Clears the value of `gpsData`. Subsequent reads from it will return its default value.
  mutating func clearGpsData() {_uniqueStorage()._gpsData = nil}

  var sensors: SimpleSensorReading {
    get {return _storage._sensors ?? SimpleSensorReading()}
    set {_uniqueStorage()._sensors = newValue}
  }
  /// Returns true if `sensors` has been explicitly set.
  var hasSensors: Bool {return _storage._sensors != nil}
  /// Clears the value of `sensors`. Subsequent reads from it will return its default value.
  mutating func clearSensors() {_uniqueStorage()._sensors = nil}

  var firmwareVersion: String {
    get {return _storage._firmwareVersion}
    set {_uniqueStorage()._firmwareVersion = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct PeripheralPacket: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 6 bytes, fixed-length in options
  var macAddress: Data = Data()

  var type: PeripheralType = .peripheralSatcom

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct PeripheralInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var deviceUids: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// ================== WRAPPER ==================
struct BlePacket: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var header: PacketHeader {
    get {return _header ?? PacketHeader()}
    set {_header = newValue}
  }
  /// Returns true if `header` has been explicitly set.
  var hasHeader: Bool {return self._header != nil}
  /// Clears the value of `header`. Subsequent reads from it will return its default value.
  mutating func clearHeader() {self._header = nil}

  var payload: BlePacket.OneOf_Payload? = nil

  var scheduleConfigPacket: ScheduleConfigPacket {
    get {
      if case .scheduleConfigPacket(let v)? = payload {return v}
      return ScheduleConfigPacket()
    }
    set {payload = .scheduleConfigPacket(newValue)}
  }

  var systemStatePacket: SystemStatePacket {
    get {
      if case .systemStatePacket(let v)? = payload {return v}
      return SystemStatePacket()
    }
    set {payload = .systemStatePacket(newValue)}
  }

  var radioConfigPacket: RadioConfigPacket {
    get {
      if case .radioConfigPacket(let v)? = payload {return v}
      return RadioConfigPacket()
    }
    set {payload = .radioConfigPacket(newValue)}
  }

  var peripheralPacket: PeripheralPacket {
    get {
      if case .peripheralPacket(let v)? = payload {return v}
      return PeripheralPacket()
    }
    set {payload = .peripheralPacket(newValue)}
  }

  var peripheralInfo: PeripheralInfo {
    get {
      if case .peripheralInfo(let v)? = payload {return v}
      return PeripheralInfo()
    }
    set {payload = .peripheralInfo(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Payload: Equatable, Sendable {
    case scheduleConfigPacket(ScheduleConfigPacket)
    case systemStatePacket(SystemStatePacket)
    case radioConfigPacket(RadioConfigPacket)
    case peripheralPacket(PeripheralPacket)
    case peripheralInfo(PeripheralInfo)

  }

  init() {}

  fileprivate var _header: PacketHeader? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension RadioRegion: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "REGION_US915"),
    1: .same(proto: "REGION_AU915"),
    2: .same(proto: "REGION_EU868"),
  ]
}

extension RadioAuth: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "AUTH_OTAA"),
    1: .same(proto: "AUTH_ABP"),
  ]
}

extension RadioSpreadingFactor: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "SF7"),
    1: .same(proto: "SF8"),
    2: .same(proto: "SF9"),
    3: .same(proto: "SF10"),
    4: .same(proto: "SF11"),
    5: .same(proto: "SF12"),
  ]
}

extension RadioBandwidth: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "bw_125"),
    1: .same(proto: "bw_250"),
    2: .same(proto: "bw_500"),
  ]
}

extension RadioCodingRate: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "cr_4_5"),
    1: .same(proto: "cr_4_6"),
    2: .same(proto: "cr_4_7"),
    3: .same(proto: "cr_4_8"),
  ]
}

extension AccelSampleRate: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "ACCEL_25HZ"),
    1: .same(proto: "ACCEL_50HZ"),
  ]
}

extension AccelSensitivity: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "ACCEL_2G"),
    1: .same(proto: "ACCEL_4G"),
    2: .same(proto: "ACCEL_8G"),
  ]
}

extension PeripheralType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "PERIPHERAL_SATCOM"),
    1: .same(proto: "PERIPHERAL_DETACHMENT"),
  ]
}

extension TimeWindow: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "TimeWindow"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "start_hour"),
    2: .standard(proto: "end_hour"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.startHour) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.endHour) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.startHour != 0 {
      try visitor.visitSingularUInt32Field(value: self.startHour, fieldNumber: 1)
    }
    if self.endHour != 0 {
      try visitor.visitSingularUInt32Field(value: self.endHour, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TimeWindow, rhs: TimeWindow) -> Bool {
    if lhs.startHour != rhs.startHour {return false}
    if lhs.endHour != rhs.endHour {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SamplingConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SamplingConfig"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "enabled"),
    2: .standard(proto: "sample_interval_min"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.enabled) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.sampleIntervalMin) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.enabled != false {
      try visitor.visitSingularBoolField(value: self.enabled, fieldNumber: 1)
    }
    if self.sampleIntervalMin != 0 {
      try visitor.visitSingularUInt32Field(value: self.sampleIntervalMin, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SamplingConfig, rhs: SamplingConfig) -> Bool {
    if lhs.enabled != rhs.enabled {return false}
    if lhs.sampleIntervalMin != rhs.sampleIntervalMin {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension GPSConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "GPSConfig"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "enabled"),
    2: .standard(proto: "sample_interval_min"),
    3: .same(proto: "accuracy"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.enabled) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.sampleIntervalMin) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.accuracy) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.enabled != false {
      try visitor.visitSingularBoolField(value: self.enabled, fieldNumber: 1)
    }
    if self.sampleIntervalMin != 0 {
      try visitor.visitSingularUInt32Field(value: self.sampleIntervalMin, fieldNumber: 2)
    }
    if self.accuracy != 0 {
      try visitor.visitSingularUInt32Field(value: self.accuracy, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: GPSConfig, rhs: GPSConfig) -> Bool {
    if lhs.enabled != rhs.enabled {return false}
    if lhs.sampleIntervalMin != rhs.sampleIntervalMin {return false}
    if lhs.accuracy != rhs.accuracy {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RadioOTAA: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "RadioOTAA"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "dev_eui"),
    2: .standard(proto: "join_eui"),
    3: .standard(proto: "app_key"),
    4: .standard(proto: "nwk_key"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.devEui) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.joinEui) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.appKey) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.nwkKey) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.devEui.isEmpty {
      try visitor.visitSingularBytesField(value: self.devEui, fieldNumber: 1)
    }
    if !self.joinEui.isEmpty {
      try visitor.visitSingularBytesField(value: self.joinEui, fieldNumber: 2)
    }
    if !self.appKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.appKey, fieldNumber: 3)
    }
    if !self.nwkKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.nwkKey, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RadioOTAA, rhs: RadioOTAA) -> Bool {
    if lhs.devEui != rhs.devEui {return false}
    if lhs.joinEui != rhs.joinEui {return false}
    if lhs.appKey != rhs.appKey {return false}
    if lhs.nwkKey != rhs.nwkKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RadioABP: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "RadioABP"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "dev_addr"),
    2: .standard(proto: "nwk_s_key"),
    3: .standard(proto: "app_s_key"),
    4: .standard(proto: "f_nwk_s_int_key"),
    5: .standard(proto: "s_nwk_s_int_key"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.devAddr) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.nwkSKey) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.appSKey) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.fNwkSIntKey) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.sNwkSIntKey) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.devAddr.isEmpty {
      try visitor.visitSingularBytesField(value: self.devAddr, fieldNumber: 1)
    }
    if !self.nwkSKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.nwkSKey, fieldNumber: 2)
    }
    if !self.appSKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.appSKey, fieldNumber: 3)
    }
    if !self.fNwkSIntKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.fNwkSIntKey, fieldNumber: 4)
    }
    if !self.sNwkSIntKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.sNwkSIntKey, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RadioABP, rhs: RadioABP) -> Bool {
    if lhs.devAddr != rhs.devAddr {return false}
    if lhs.nwkSKey != rhs.nwkSKey {return false}
    if lhs.appSKey != rhs.appSKey {return false}
    if lhs.fNwkSIntKey != rhs.fNwkSIntKey {return false}
    if lhs.sNwkSIntKey != rhs.sNwkSIntKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension LoRaWANConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "LoRaWANConfig"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "region"),
    2: .same(proto: "auth"),
    3: .same(proto: "otaa"),
    4: .same(proto: "abp"),
    5: .standard(proto: "transmit_interval_min"),
    6: .standard(proto: "tx_only_on_new_gps_fix"),
    7: .standard(proto: "tx_power_dbm"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.region) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.auth) }()
      case 3: try {
        var v: RadioOTAA?
        var hadOneofValue = false
        if let current = self.credentials {
          hadOneofValue = true
          if case .otaa(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.credentials = .otaa(v)
        }
      }()
      case 4: try {
        var v: RadioABP?
        var hadOneofValue = false
        if let current = self.credentials {
          hadOneofValue = true
          if case .abp(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.credentials = .abp(v)
        }
      }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.transmitIntervalMin) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.txOnlyOnNewGpsFix) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.txPowerDbm) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.region != .regionUs915 {
      try visitor.visitSingularEnumField(value: self.region, fieldNumber: 1)
    }
    if self.auth != .authOtaa {
      try visitor.visitSingularEnumField(value: self.auth, fieldNumber: 2)
    }
    switch self.credentials {
    case .otaa?: try {
      guard case .otaa(let v)? = self.credentials else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .abp?: try {
      guard case .abp(let v)? = self.credentials else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    if self.transmitIntervalMin != 0 {
      try visitor.visitSingularUInt32Field(value: self.transmitIntervalMin, fieldNumber: 5)
    }
    if self.txOnlyOnNewGpsFix != false {
      try visitor.visitSingularBoolField(value: self.txOnlyOnNewGpsFix, fieldNumber: 6)
    }
    if self.txPowerDbm != 0 {
      try visitor.visitSingularInt32Field(value: self.txPowerDbm, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: LoRaWANConfig, rhs: LoRaWANConfig) -> Bool {
    if lhs.region != rhs.region {return false}
    if lhs.auth != rhs.auth {return false}
    if lhs.credentials != rhs.credentials {return false}
    if lhs.transmitIntervalMin != rhs.transmitIntervalMin {return false}
    if lhs.txOnlyOnNewGpsFix != rhs.txOnlyOnNewGpsFix {return false}
    if lhs.txPowerDbm != rhs.txPowerDbm {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension LoRaConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "LoRaConfig"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "radioSpreadingFactor"),
    2: .same(proto: "radioBandwidth"),
    3: .same(proto: "radioCodingRate"),
    4: .standard(proto: "tx_power_dbm"),
    5: .standard(proto: "sync_word"),
    6: .same(proto: "frequency"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.radioSpreadingFactor) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.radioBandwidth) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.radioCodingRate) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.txPowerDbm) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.syncWord) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.frequency) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.radioSpreadingFactor != .sf7 {
      try visitor.visitSingularEnumField(value: self.radioSpreadingFactor, fieldNumber: 1)
    }
    if self.radioBandwidth != .bw125 {
      try visitor.visitSingularEnumField(value: self.radioBandwidth, fieldNumber: 2)
    }
    if self.radioCodingRate != .cr45 {
      try visitor.visitSingularEnumField(value: self.radioCodingRate, fieldNumber: 3)
    }
    if self.txPowerDbm != 0 {
      try visitor.visitSingularInt32Field(value: self.txPowerDbm, fieldNumber: 4)
    }
    if self.syncWord != 0 {
      try visitor.visitSingularUInt32Field(value: self.syncWord, fieldNumber: 5)
    }
    if self.frequency != 0 {
      try visitor.visitSingularUInt32Field(value: self.frequency, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: LoRaConfig, rhs: LoRaConfig) -> Bool {
    if lhs.radioSpreadingFactor != rhs.radioSpreadingFactor {return false}
    if lhs.radioBandwidth != rhs.radioBandwidth {return false}
    if lhs.radioCodingRate != rhs.radioCodingRate {return false}
    if lhs.txPowerDbm != rhs.txPowerDbm {return false}
    if lhs.syncWord != rhs.syncWord {return false}
    if lhs.frequency != rhs.frequency {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension LostMode_config: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "LostMode_config"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "activation_epoch"),
    2: .standard(proto: "transmit_interval_min"),
    3: .standard(proto: "tx_power_dbm"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.activationEpoch) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.transmitIntervalMin) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.txPowerDbm) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.activationEpoch != 0 {
      try visitor.visitSingularUInt32Field(value: self.activationEpoch, fieldNumber: 1)
    }
    if self.transmitIntervalMin != 0 {
      try visitor.visitSingularUInt32Field(value: self.transmitIntervalMin, fieldNumber: 2)
    }
    if self.txPowerDbm != 0 {
      try visitor.visitSingularInt32Field(value: self.txPowerDbm, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: LostMode_config, rhs: LostMode_config) -> Bool {
    if lhs.activationEpoch != rhs.activationEpoch {return false}
    if lhs.transmitIntervalMin != rhs.transmitIntervalMin {return false}
    if lhs.txPowerDbm != rhs.txPowerDbm {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RadioConfigPacket: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "RadioConfigPacket"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "loRaWAN_config"),
    2: .standard(proto: "loRa_config"),
    3: .standard(proto: "lostMode_enabled"),
    4: .standard(proto: "lostMode_config"),
  ]

  fileprivate class _StorageClass {
    var _loRaWanConfig: LoRaWANConfig? = nil
    var _loRaConfig: LoRaConfig? = nil
    var _lostModeEnabled: Bool = false
    var _lostModeConfig: LostMode_config? = nil

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _loRaWanConfig = source._loRaWanConfig
      _loRaConfig = source._loRaConfig
      _lostModeEnabled = source._lostModeEnabled
      _lostModeConfig = source._lostModeConfig
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._loRaWanConfig) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._loRaConfig) }()
        case 3: try { try decoder.decodeSingularBoolField(value: &_storage._lostModeEnabled) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._lostModeConfig) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._loRaWanConfig {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._loRaConfig {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if _storage._lostModeEnabled != false {
        try visitor.visitSingularBoolField(value: _storage._lostModeEnabled, fieldNumber: 3)
      }
      try { if let v = _storage._lostModeConfig {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RadioConfigPacket, rhs: RadioConfigPacket) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._loRaWanConfig != rhs_storage._loRaWanConfig {return false}
        if _storage._loRaConfig != rhs_storage._loRaConfig {return false}
        if _storage._lostModeEnabled != rhs_storage._lostModeEnabled {return false}
        if _storage._lostModeConfig != rhs_storage._lostModeConfig {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension MicrophoneConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "MicrophoneConfig"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "enabled"),
    2: .standard(proto: "continuous_mode"),
    3: .standard(proto: "sample_length_min"),
    4: .standard(proto: "sample_window_min"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.enabled) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.continuousMode) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.sampleLengthMin) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.sampleWindowMin) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.enabled != false {
      try visitor.visitSingularBoolField(value: self.enabled, fieldNumber: 1)
    }
    if self.continuousMode != false {
      try visitor.visitSingularBoolField(value: self.continuousMode, fieldNumber: 2)
    }
    if self.sampleLengthMin != 0 {
      try visitor.visitSingularUInt32Field(value: self.sampleLengthMin, fieldNumber: 3)
    }
    if self.sampleWindowMin != 0 {
      try visitor.visitSingularUInt32Field(value: self.sampleWindowMin, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: MicrophoneConfig, rhs: MicrophoneConfig) -> Bool {
    if lhs.enabled != rhs.enabled {return false}
    if lhs.continuousMode != rhs.continuousMode {return false}
    if lhs.sampleLengthMin != rhs.sampleLengthMin {return false}
    if lhs.sampleWindowMin != rhs.sampleWindowMin {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AccelerometerConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "AccelerometerConfig"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "enabled"),
    2: .standard(proto: "sample_rate"),
    3: .same(proto: "sensitivity"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.enabled) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.sampleRate) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.sensitivity) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.enabled != false {
      try visitor.visitSingularBoolField(value: self.enabled, fieldNumber: 1)
    }
    if self.sampleRate != .accel25Hz {
      try visitor.visitSingularEnumField(value: self.sampleRate, fieldNumber: 2)
    }
    if self.sensitivity != .accel2G {
      try visitor.visitSingularEnumField(value: self.sensitivity, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: AccelerometerConfig, rhs: AccelerometerConfig) -> Bool {
    if lhs.enabled != rhs.enabled {return false}
    if lhs.sampleRate != rhs.sampleRate {return false}
    if lhs.sensitivity != rhs.sensitivity {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension MagnetometerConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "MagnetometerConfig"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "enabled"),
    2: .standard(proto: "sample_interval_s"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.enabled) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.sampleIntervalS) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.enabled != false {
      try visitor.visitSingularBoolField(value: self.enabled, fieldNumber: 1)
    }
    if self.sampleIntervalS != 0 {
      try visitor.visitSingularUInt32Field(value: self.sampleIntervalS, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: MagnetometerConfig, rhs: MagnetometerConfig) -> Bool {
    if lhs.enabled != rhs.enabled {return false}
    if lhs.sampleIntervalS != rhs.sampleIntervalS {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ScheduleConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ScheduleConfig"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "window"),
    2: .same(proto: "light"),
    3: .same(proto: "environmental"),
    4: .same(proto: "particulate"),
    5: .same(proto: "gps"),
    6: .same(proto: "microphone"),
    7: .same(proto: "accelerometer"),
    8: .standard(proto: "lorawan_enabled"),
    9: .standard(proto: "lorawan_send_interval_min"),
    10: .standard(proto: "lora_enabled"),
    11: .standard(proto: "lora_send_interval_min"),
    12: .same(proto: "magnetometer"),
  ]

  fileprivate class _StorageClass {
    var _window: TimeWindow? = nil
    var _light: SamplingConfig? = nil
    var _environmental: SamplingConfig? = nil
    var _particulate: SamplingConfig? = nil
    var _gps: GPSConfig? = nil
    var _microphone: MicrophoneConfig? = nil
    var _accelerometer: AccelerometerConfig? = nil
    var _lorawanEnabled: Bool = false
    var _lorawanSendIntervalMin: UInt32 = 0
    var _loraEnabled: Bool = false
    var _loraSendIntervalMin: UInt32 = 0
    var _magnetometer: MagnetometerConfig? = nil

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _window = source._window
      _light = source._light
      _environmental = source._environmental
      _particulate = source._particulate
      _gps = source._gps
      _microphone = source._microphone
      _accelerometer = source._accelerometer
      _lorawanEnabled = source._lorawanEnabled
      _lorawanSendIntervalMin = source._lorawanSendIntervalMin
      _loraEnabled = source._loraEnabled
      _loraSendIntervalMin = source._loraSendIntervalMin
      _magnetometer = source._magnetometer
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._window) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._light) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._environmental) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._particulate) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._gps) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._microphone) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._accelerometer) }()
        case 8: try { try decoder.decodeSingularBoolField(value: &_storage._lorawanEnabled) }()
        case 9: try { try decoder.decodeSingularUInt32Field(value: &_storage._lorawanSendIntervalMin) }()
        case 10: try { try decoder.decodeSingularBoolField(value: &_storage._loraEnabled) }()
        case 11: try { try decoder.decodeSingularUInt32Field(value: &_storage._loraSendIntervalMin) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._magnetometer) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._window {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._light {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._environmental {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._particulate {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._gps {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._microphone {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._accelerometer {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      if _storage._lorawanEnabled != false {
        try visitor.visitSingularBoolField(value: _storage._lorawanEnabled, fieldNumber: 8)
      }
      if _storage._lorawanSendIntervalMin != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._lorawanSendIntervalMin, fieldNumber: 9)
      }
      if _storage._loraEnabled != false {
        try visitor.visitSingularBoolField(value: _storage._loraEnabled, fieldNumber: 10)
      }
      if _storage._loraSendIntervalMin != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._loraSendIntervalMin, fieldNumber: 11)
      }
      try { if let v = _storage._magnetometer {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ScheduleConfig, rhs: ScheduleConfig) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._window != rhs_storage._window {return false}
        if _storage._light != rhs_storage._light {return false}
        if _storage._environmental != rhs_storage._environmental {return false}
        if _storage._particulate != rhs_storage._particulate {return false}
        if _storage._gps != rhs_storage._gps {return false}
        if _storage._microphone != rhs_storage._microphone {return false}
        if _storage._accelerometer != rhs_storage._accelerometer {return false}
        if _storage._lorawanEnabled != rhs_storage._lorawanEnabled {return false}
        if _storage._lorawanSendIntervalMin != rhs_storage._lorawanSendIntervalMin {return false}
        if _storage._loraEnabled != rhs_storage._loraEnabled {return false}
        if _storage._loraSendIntervalMin != rhs_storage._loraSendIntervalMin {return false}
        if _storage._magnetometer != rhs_storage._magnetometer {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ScheduleConfigPacket: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ScheduleConfigPacket"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "engaged"),
    2: .same(proto: "schedules"),
    3: .standard(proto: "special_mode"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.engaged) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.schedules) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.specialMode) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.engaged != false {
      try visitor.visitSingularBoolField(value: self.engaged, fieldNumber: 1)
    }
    if !self.schedules.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.schedules, fieldNumber: 2)
    }
    if self.specialMode != 0 {
      try visitor.visitSingularUInt32Field(value: self.specialMode, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ScheduleConfigPacket, rhs: ScheduleConfigPacket) -> Bool {
    if lhs.engaged != rhs.engaged {return false}
    if lhs.schedules != rhs.schedules {return false}
    if lhs.specialMode != rhs.specialMode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SimpleSensorReading: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SimpleSensorReading"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "index"),
    2: .same(proto: "temperature"),
    3: .same(proto: "humidity"),
    4: .same(proto: "pressure"),
    5: .same(proto: "gas"),
    6: .standard(proto: "pm2_5"),
    7: .same(proto: "light"),
    8: .same(proto: "activity"),
    9: .same(proto: "steps"),
    10: .standard(proto: "particulate_static_obstructed"),
    11: .standard(proto: "particulate_dynamic_obstructed"),
    12: .standard(proto: "particulate_outside_detection_limits"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.index) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.temperature) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.humidity) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.pressure) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self.gas) }()
      case 6: try { try decoder.decodeSingularFloatField(value: &self.pm25) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self.light) }()
      case 8: try { try decoder.decodeSingularEnumField(value: &self.activity) }()
      case 9: try { try decoder.decodeSingularUInt32Field(value: &self.steps) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self.particulateStaticObstructed) }()
      case 11: try { try decoder.decodeSingularBoolField(value: &self.particulateDynamicObstructed) }()
      case 12: try { try decoder.decodeSingularBoolField(value: &self.particulateOutsideDetectionLimits) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.index != 0 {
      try visitor.visitSingularUInt32Field(value: self.index, fieldNumber: 1)
    }
    if self.temperature.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.temperature, fieldNumber: 2)
    }
    if self.humidity.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.humidity, fieldNumber: 3)
    }
    if self.pressure.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.pressure, fieldNumber: 4)
    }
    if self.gas.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.gas, fieldNumber: 5)
    }
    if self.pm25.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.pm25, fieldNumber: 6)
    }
    if self.light != 0 {
      try visitor.visitSingularUInt32Field(value: self.light, fieldNumber: 7)
    }
    if self.activity != .still {
      try visitor.visitSingularEnumField(value: self.activity, fieldNumber: 8)
    }
    if self.steps != 0 {
      try visitor.visitSingularUInt32Field(value: self.steps, fieldNumber: 9)
    }
    if self.particulateStaticObstructed != false {
      try visitor.visitSingularBoolField(value: self.particulateStaticObstructed, fieldNumber: 10)
    }
    if self.particulateDynamicObstructed != false {
      try visitor.visitSingularBoolField(value: self.particulateDynamicObstructed, fieldNumber: 11)
    }
    if self.particulateOutsideDetectionLimits != false {
      try visitor.visitSingularBoolField(value: self.particulateOutsideDetectionLimits, fieldNumber: 12)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SimpleSensorReading, rhs: SimpleSensorReading) -> Bool {
    if lhs.index != rhs.index {return false}
    if lhs.temperature != rhs.temperature {return false}
    if lhs.humidity != rhs.humidity {return false}
    if lhs.pressure != rhs.pressure {return false}
    if lhs.gas != rhs.gas {return false}
    if lhs.pm25 != rhs.pm25 {return false}
    if lhs.light != rhs.light {return false}
    if lhs.activity != rhs.activity {return false}
    if lhs.steps != rhs.steps {return false}
    if lhs.particulateStaticObstructed != rhs.particulateStaticObstructed {return false}
    if lhs.particulateDynamicObstructed != rhs.particulateDynamicObstructed {return false}
    if lhs.particulateOutsideDetectionLimits != rhs.particulateOutsideDetectionLimits {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SystemStatePacket: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SystemStatePacket"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "engage_state"),
    2: .same(proto: "battery"),
    3: .same(proto: "sdcard"),
    4: .standard(proto: "gps_data"),
    5: .same(proto: "sensors"),
    6: .standard(proto: "firmware_version"),
  ]

  fileprivate class _StorageClass {
    var _engageState: Bool = false
    var _battery: BatteryState? = nil
    var _sdcard: SDCardState? = nil
    var _gpsData: GPSData? = nil
    var _sensors: SimpleSensorReading? = nil
    var _firmwareVersion: String = String()

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _engageState = source._engageState
      _battery = source._battery
      _sdcard = source._sdcard
      _gpsData = source._gpsData
      _sensors = source._sensors
      _firmwareVersion = source._firmwareVersion
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularBoolField(value: &_storage._engageState) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._battery) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._sdcard) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._gpsData) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._sensors) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._firmwareVersion) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._engageState != false {
        try visitor.visitSingularBoolField(value: _storage._engageState, fieldNumber: 1)
      }
      try { if let v = _storage._battery {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._sdcard {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._gpsData {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._sensors {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      if !_storage._firmwareVersion.isEmpty {
        try visitor.visitSingularStringField(value: _storage._firmwareVersion, fieldNumber: 6)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SystemStatePacket, rhs: SystemStatePacket) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._engageState != rhs_storage._engageState {return false}
        if _storage._battery != rhs_storage._battery {return false}
        if _storage._sdcard != rhs_storage._sdcard {return false}
        if _storage._gpsData != rhs_storage._gpsData {return false}
        if _storage._sensors != rhs_storage._sensors {return false}
        if _storage._firmwareVersion != rhs_storage._firmwareVersion {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PeripheralPacket: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "PeripheralPacket"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "mac_address"),
    2: .same(proto: "type"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.macAddress) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.macAddress.isEmpty {
      try visitor.visitSingularBytesField(value: self.macAddress, fieldNumber: 1)
    }
    if self.type != .peripheralSatcom {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PeripheralPacket, rhs: PeripheralPacket) -> Bool {
    if lhs.macAddress != rhs.macAddress {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PeripheralInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "PeripheralInfo"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "device_uids"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.deviceUids) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.deviceUids.isEmpty {
      try visitor.visitRepeatedStringField(value: self.deviceUids, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PeripheralInfo, rhs: PeripheralInfo) -> Bool {
    if lhs.deviceUids != rhs.deviceUids {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlePacket: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "BlePacket"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "header"),
    2: .standard(proto: "schedule_config_packet"),
    3: .standard(proto: "system_state_packet"),
    4: .standard(proto: "radio_config_packet"),
    5: .standard(proto: "peripheral_packet"),
    6: .standard(proto: "peripheral_info"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._header) }()
      case 2: try {
        var v: ScheduleConfigPacket?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .scheduleConfigPacket(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .scheduleConfigPacket(v)
        }
      }()
      case 3: try {
        var v: SystemStatePacket?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .systemStatePacket(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .systemStatePacket(v)
        }
      }()
      case 4: try {
        var v: RadioConfigPacket?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .radioConfigPacket(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .radioConfigPacket(v)
        }
      }()
      case 5: try {
        var v: PeripheralPacket?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .peripheralPacket(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .peripheralPacket(v)
        }
      }()
      case 6: try {
        var v: PeripheralInfo?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .peripheralInfo(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .peripheralInfo(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._header {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    switch self.payload {
    case .scheduleConfigPacket?: try {
      guard case .scheduleConfigPacket(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .systemStatePacket?: try {
      guard case .systemStatePacket(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .radioConfigPacket?: try {
      guard case .radioConfigPacket(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .peripheralPacket?: try {
      guard case .peripheralPacket(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .peripheralInfo?: try {
      guard case .peripheralInfo(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BlePacket, rhs: BlePacket) -> Bool {
    if lhs._header != rhs._header {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
