/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "ble.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TIME_WINDOW, time_window_t, AUTO)


PB_BIND(SAMPLING_CONFIG, sampling_config_t, AUTO)


PB_BIND(GPS_CONFIG, gps_config_t, AUTO)


PB_BIND(RADIO_OTAA, radio_otaa_t, AUTO)


PB_BIND(RADIO_ABP, radio_abp_t, AUTO)


PB_BIND(LO_RA_WAN_CONFIG, lo_ra_wan_config_t, AUTO)


PB_BIND(LO_RA_CONFIG, lo_ra_config_t, AUTO)


PB_BIND(LOST_MODE_CONFIG, lost_mode_config_t, AUTO)


PB_BIND(MORTALITY_CONFIG, mortality_config_t, AUTO)


PB_BIND(RADIO_CONFIG_PACKET, radio_config_packet_t, AUTO)


PB_BIND(MICROPHONE_CONFIG, microphone_config_t, AUTO)


PB_BIND(ACCELEROMETER_CONFIG, accelerometer_config_t, AUTO)


PB_BIND(MAGNETOMETER_CONFIG, magnetometer_config_t, AUTO)


PB_BIND(SCHEDULE_CONFIG, schedule_config_t, AUTO)


PB_BIND(SCHEDULE_CONFIG_PACKET, schedule_config_packet_t, 2)


PB_BIND(SIMPLE_SENSOR_READING, simple_sensor_reading_t, AUTO)


PB_BIND(SYSTEM_STATE_PACKET, system_state_packet_t, AUTO)


PB_BIND(PERIPHERAL_PACKET, peripheral_packet_t, AUTO)


PB_BIND(PERIPHERAL_INFO, peripheral_info_t, AUTO)


PB_BIND(BLE_PACKET, ble_packet_t, 2)











