/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_BLE_PB_H_INCLUDED
#define PB_BLE_PB_H_INCLUDED
#include <pb.h>
#include "common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum radio_region {
    RADIO_REGION_REGION_US915 = 0,
    RADIO_REGION_REGION_AU915 = 1,
    RADIO_REGION_REGION_EU868 = 2
} radio_region_t;

typedef enum radio_auth {
    RADIO_AUTH_AUTH_OTAA = 0,
    RADIO_AUTH_AUTH_ABP = 1
} radio_auth_t;

typedef enum radio_spreading_factor {
    RADIO_SPREADING_FACTOR_SF7 = 0,
    RADIO_SPREADING_FACTOR_SF8 = 1,
    RADIO_SPREADING_FACTOR_SF9 = 2,
    RADIO_SPREADING_FACTOR_SF10 = 3,
    RADIO_SPREADING_FACTOR_SF11 = 4,
    RADIO_SPREADING_FACTOR_SF12 = 5
} radio_spreading_factor_t;

typedef enum radio_bandwidth {
    RADIO_BANDWIDTH_BW_125 = 0,
    RADIO_BANDWIDTH_BW_250 = 1,
    RADIO_BANDWIDTH_BW_500 = 2
} radio_bandwidth_t;

typedef enum radio_coding_rate {
    RADIO_CODING_RATE_CR_4_5 = 0,
    RADIO_CODING_RATE_CR_4_6 = 1,
    RADIO_CODING_RATE_CR_4_7 = 2,
    RADIO_CODING_RATE_CR_4_8 = 3
} radio_coding_rate_t;

/* Microphone acquisition format.

 These are enums, not raw Hz/bit counts, because the ADF can only produce
 rates of 3.072 MHz / (decimation x 4 x 4) and each one needs its own
 bench-calibrated filter gain (the SINC5 CIC's DC gain scales as
 decimation^5). A rate is therefore a firmware-supported format, not a free
 parameter — adding one means adding a calibrated table entry, so it also
 means adding an enum value here.

 Value 0 is the historical behaviour on purpose. Collars, configs, and
 clients predating these fields decode as 16 kHz / 16-bit, which is exactly
 what every deployed unit already records. */
typedef enum mic_sample_rate {
    MIC_SAMPLE_RATE_MIC_RATE_16_KHZ = 0, /* legacy default: divider 4, decimation 12 (mic in low-power mode) */
    MIC_SAMPLE_RATE_MIC_RATE_8_KHZ = 1, /* divider 4, decimation 24 (low-power mode) */
    /* fw 341+. All three are exact integer divisions of the 3.072 MHz ADF
 kernel clock; the divider moves the microphone between its clock-selected
 modes (Knowles SPH0641LU4H-1). */
    MIC_SAMPLE_RATE_MIC_RATE_48_KHZ = 2, /* divider 2, decimation 8 (standard mode) */
    MIC_SAMPLE_RATE_MIC_RATE_96_KHZ = 3, /* divider 1, decimation 8 (ultrasonic mode, two-step bring-up) */
    MIC_SAMPLE_RATE_MIC_RATE_192_KHZ = 4 /* divider 1, decimation 16, reshape filter OFF */
} mic_sample_rate_t;

typedef enum mic_bit_depth {
    MIC_BIT_DEPTH_MIC_DEPTH_16_BIT = 0, /* legacy default: signed 16-bit PCM */
    MIC_BIT_DEPTH_MIC_DEPTH_8_BIT = 1 /* unsigned 8-bit PCM (WAV stores 8-bit as offset binary) */
} mic_bit_depth_t;

/* Digital gain boost over the per-rate calibrated baseline, in the ADF's
 ~3 dB steps: +0 / +6 / +12 dB. Value 0 is the historical calibration, so
 collars and clients predating the field are unchanged. Firmware clamps the
 summed gain to the MDF's +24 ceiling (fw 349+). */
typedef enum mic_sensitivity {
    MIC_SENSITIVITY_MIC_SENS_LOW = 0, /* the calibrated baseline */
    MIC_SENSITIVITY_MIC_SENS_MEDIUM = 1, /* +6 dB */
    MIC_SENSITIVITY_MIC_SENS_HIGH = 2 /* +12 dB */
} mic_sensitivity_t;

/* How a recording is stored on the card. Value 0 is the historical behaviour:
 collars, configs and clients predating the field record plain WAV.

 FLAC is lossless: the decoded samples are bit for bit what the WAV would have
 held, in roughly 30 % of the space on collar recordings (measured 28 % over
 299 field files). The encoder is a fixed-predictor FLAC subset that any FLAC
 decoder reads. Firmware only honours it where it has been shown to keep up:
 16-bit at 8 or 16 kHz. Anything else records WAV and says so in the log. */
typedef enum mic_codec {
    MIC_CODEC_MIC_CODEC_WAV = 0, /* legacy default: uncompressed PCM in a WAV file */
    MIC_CODEC_MIC_CODEC_FLAC = 1 /* lossless FLAC, 16-bit at 8/16 kHz only */
} mic_codec_t;

typedef enum accel_sample_rate {
    ACCEL_SAMPLE_RATE_ACCEL_25_HZ = 0,
    ACCEL_SAMPLE_RATE_ACCEL_50_HZ = 1
} accel_sample_rate_t;

typedef enum accel_sensitivity {
    ACCEL_SENSITIVITY_ACCEL_2_G = 0,
    ACCEL_SENSITIVITY_ACCEL_4_G = 1,
    ACCEL_SENSITIVITY_ACCEL_8_G = 2
} accel_sensitivity_t;

/* ---- Magnetometer calibration report (CfgEchoPacket.mag_cal) ----
 The calibration is in force exactly when state == DONE and verdict is
 GOOD or FAIR. Every other outcome leaves the previous calibration in force. */
typedef enum mag_cal_state {
    MAG_CAL_STATE_MAG_CAL_STATE_IDLE = 0, /* zero value only: mag_cal is absent until a run starts */
    MAG_CAL_STATE_MAG_CAL_STATE_COLLECTING = 1, /* capturing; progress_pct climbs as the sphere fills */
    MAG_CAL_STATE_MAG_CAL_STATE_FITTING = 2, /* capture over, fit running */
    MAG_CAL_STATE_MAG_CAL_STATE_DONE = 3, /* a fit was made and judged; verdict says whether it is in force */
    /* No fit could be made or kept: verdict RETRY, reason TIMEOUT,
 NOT_ENOUGH_ROTATION, SENSOR_FAULT or STORAGE. */
    MAG_CAL_STATE_MAG_CAL_STATE_FAILED = 4,
    MAG_CAL_STATE_MAG_CAL_STATE_ABORTED = 5 /* CMD_MAG_CALIBRATE_ABORT, or the Bluetooth session ended */
} mag_cal_state_t;

typedef enum mag_cal_verdict {
    MAG_CAL_VERDICT_MAG_CAL_VERDICT_NONE = 0, /* run still going, or aborted */
    MAG_CAL_VERDICT_MAG_CAL_VERDICT_GOOD = 1, /* in force */
    MAG_CAL_VERDICT_MAG_CAL_VERDICT_FAIR = 2, /* in force; repeating it away from metal may do better */
    MAG_CAL_VERDICT_MAG_CAL_VERDICT_RETRY = 3 /* not in force; turn the collar through the sequence again */
} mag_cal_verdict_t;

/* The limiting factor behind a FAIR or RETRY verdict; NONE with GOOD, while
 the run is going, and after an abort. */
typedef enum mag_cal_reason {
    MAG_CAL_REASON_MAG_CAL_REASON_NONE = 0,
    MAG_CAL_REASON_MAG_CAL_REASON_TIMEOUT = 1, /* time limit reached before the coverage target */
    MAG_CAL_REASON_MAG_CAL_REASON_NOT_ENOUGH_ROTATION = 2, /* samples too flat for a unique fit (turned about one axis) */
    MAG_CAL_REASON_MAG_CAL_REASON_SENSOR_FAULT = 3, /* magnetometer not answering, or its readings stuck */
    MAG_CAL_REASON_MAG_CAL_REASON_FIELD_OUT_OF_RANGE = 4, /* fitted field outside the Earth's ~20-70 uT: metal, magnet or electronics nearby */
    MAG_CAL_REASON_MAG_CAL_REASON_RESIDUAL_HIGH = 5, /* samples scatter too far from the fit: disturbance during the capture */
    MAG_CAL_REASON_MAG_CAL_REASON_STORAGE = 6 /* fit made but MAGCAL.CSV could not be written, so it is not in force */
} mag_cal_reason_t;

/* ---- Lost-mode beacon key report (CfgEchoPacket.beacon_key) ----
 What the collar puts on air in lost mode (beacon/README.md). Reports the
 beacon slot; a command key (BeaconKeySlot, downlink.proto) will get its
 own field when that firmware lands. */
typedef enum beacon_key_state {
    BEACON_KEY_STATE_BEACON_KEY_STATE_NONE = 0, /* no key held: the plaintext 0x4C frame, byte for byte what an unkeyed collar always sent */
    BEACON_KEY_STATE_BEACON_KEY_STATE_KEYED = 1, /* key held and usable: the AES-128-CCM 0x4D frame */
    /* A key is held but cannot be used, so the collar sends 0x4C and has
 logged it: the store record failed to read (torn write, ECC) or the
 24-bit sequence is exhausted. A set with a higher gen clears it. */
    BEACON_KEY_STATE_BEACON_KEY_STATE_FALLBACK = 2
} beacon_key_state_t;

/* Outcome of the most recent key command since boot; NONE until one arrives. */
typedef enum beacon_key_result {
    BEACON_KEY_RESULT_BEACON_KEY_RESULT_NONE = 0,
    BEACON_KEY_RESULT_BEACON_KEY_RESULT_APPLIED = 1, /* stored; in force from the next beacon */
    BEACON_KEY_RESULT_BEACON_KEY_RESULT_CLEARED = 2, /* erased, counter kept (also when nothing was held) */
    BEACON_KEY_RESULT_BEACON_KEY_RESULT_REJECTED_GEN = 3, /* gen not above the collar's current generation; nothing changed */
    BEACON_KEY_RESULT_BEACON_KEY_RESULT_REJECTED_ARG = 4, /* gen 0 or above 255, all-zero key, or a slot this build does not hold; nothing changed */
    BEACON_KEY_RESULT_BEACON_KEY_RESULT_STORE_ERROR = 5 /* the flash store could not be written; the previous state stands */
} beacon_key_result_t;

typedef enum peripheral_type {
    PERIPHERAL_TYPE_PERIPHERAL_SATCOM = 0,
    PERIPHERAL_TYPE_PERIPHERAL_DETACHMENT = 1
} peripheral_type_t;

/* Struct definitions */
/* ================== SCHEDULING / CONFIG ================== */
typedef struct time_window { /* 2 bytes for a plain daily window */
    uint32_t start_hour; /* 0 to 23 (inclusive) */
    uint32_t end_hour; /* 0 to 23 (inclusive) */
    /* Calendar filters (fw 357+, DESIGN_calendar_schedules.md). A window
 applies at an hour only when ALL of hour, day and date match; the
 scheduler is still first-match over the slot list, so a narrower
 calendar placed ABOVE a broader one takes priority for the hours they
 share. Zero means unbounded, so every legacy config decodes to the
 every-day behavior it always had. Days and epochs are UTC, like hours.
 Dates are DAY NUMBERS (UTC days since 1970-01-01 = epoch / 86400), not
 epoch seconds: a 3-byte varint instead of 5, which is what keeps a
 window fragment plus its downlink wrapper under the 33 B RX2 floor.
 A window that runs past midnight belongs to the day it STARTS on: its
 hours after midnight are judged against the previous calendar day, so
 "Saturday 20-05" runs into Sunday morning and "until Nov 15" includes
 the night of Nov 15. */
    uint32_t day_mask; /* bit 0 = Monday .. bit 6 = Sunday; 0 = every day */
    uint32_t start_day; /* first day the window applies; 0 = no start bound */
    uint32_t end_day; /* first day it NO LONGER applies (exclusive); 0 = none */
} time_window_t;

/* Enabled/disabled and sample interval for each sensor */
typedef struct sampling_config {
    bool enabled;
    uint32_t sample_interval_min; /* minutes */
} sampling_config_t;

typedef struct gps_config {
    bool enabled;
    uint32_t sample_interval_min;
    uint32_t accuracy; /* 1 to 10 */
    bool dynamic_sampling_mode;
    uint32_t medium_motion_vedba_threshold_x100;
    uint32_t medium_motion_gps_interval_min;
    uint32_t high_motion_vedba_threshold_x100;
    uint32_t high_motion_gps_interval_min;
    bool lorawan_tx_on_gps_fix;
    bool lora_tx_on_gps_fix;
} gps_config_t;

typedef struct radio_otaa {
    pb_byte_t dev_eui[8]; /* 8, fixed_length */
    pb_byte_t join_eui[8]; /* 8, fixed_length */
    pb_byte_t app_key[16]; /* 16, fixed_length */
    pb_byte_t nwk_key[16]; /* 16, fixed_length */
} radio_otaa_t;

typedef struct radio_abp {
    pb_byte_t dev_addr[4]; /* 4,  fixed_length */
    pb_byte_t nwk_s_key[16]; /* 16, fixed_length */
    pb_byte_t app_s_key[16]; /* 16, fixed_length */
    pb_byte_t f_nwk_s_int_key[16]; /* 16, fixed_length */
    pb_byte_t s_nwk_s_int_key[16]; /* 16, fixed_length */
} radio_abp_t;

typedef struct lo_ra_wan_config {
    radio_region_t region;
    radio_auth_t auth;
    pb_size_t which_credentials;
    union {
        radio_otaa_t otaa;
        radio_abp_t abp;
    } credentials;
    uint32_t transmit_interval_min;
    bool tx_only_on_new_gps_fix;
    int32_t tx_power_dbm;
} lo_ra_wan_config_t;

typedef struct lo_ra_config {
    radio_spreading_factor_t radio_spreading_factor;
    radio_bandwidth_t radio_bandwidth;
    radio_coding_rate_t radio_coding_rate;
    int32_t tx_power_dbm;
    uint32_t sync_word; /* byte value */
    uint32_t frequency;
    /* Post-TX receive window ("rx listen"). When true, the collar opens a
 short RX window immediately after every raw-LoRa transmission (both the
 deployment packet and the lost-mode beacon) so a nearby handheld can
 answer it — the raw-LoRa analogue of a LoRaWAN Class A RX slot. The
 radio still never listens at any other time; the cost is bounded by the
 window (~250 ms per TX). proto3 default false = OFF, so every existing
 config, CSV, and fielded collar keeps today's TX-then-sleep behavior. */
    bool rx_listen;
} lo_ra_config_t;

typedef struct lost_mode_config {
    uint32_t activation_epoch;
    uint32_t transmit_interval_min;
    int32_t tx_power_dbm;
} lost_mode_config_t;

/* Mortality detection (P5). When the collar's accelerometer activity
 (VeDBA) stays below a fixed firmware threshold for trigger_duration_hours,
 it flags every uplink and additionally transmits every
 transmit_interval_min. Alert-only: the configured schedule is unchanged,
 and the state clears by itself if the animal moves again.

 Detection rides the accelerometer windows the schedule already provides
 (the accel is powered down outside them), so this does nothing useful
 unless at least one schedule enables the accelerometer. The near-zero
 VeDBA threshold is deliberately NOT exposed: it is the easiest value to
 get wrong and is tuned in firmware. */
typedef struct mortality_config {
    uint32_t trigger_duration_hours; /* 0 = firmware default (48) */
    uint32_t transmit_interval_min; /* 0 = firmware default (240) */
} mortality_config_t;

typedef struct radio_config_packet {
    bool has_lo_ra_wan_config;
    lo_ra_wan_config_t lo_ra_wan_config;
    bool has_lo_ra_config;
    lo_ra_config_t lo_ra_config;
    bool lost_mode_enabled;
    bool has_lost_mode_config;
    lost_mode_config_t lost_mode_config;
    bool mortality_enabled;
    bool has_mortality_config;
    mortality_config_t mortality_config;
} radio_config_packet_t;

typedef struct microphone_config {
    bool enabled;
    bool continuous_mode; /* on if true */
    uint32_t sample_length_min;
    uint32_t sample_window_min;
    mic_sample_rate_t sample_rate; /* 0 = 16 kHz (pre-field default) */
    mic_bit_depth_t bit_depth; /* 0 = 16-bit (pre-field default) */
    mic_sensitivity_t sensitivity; /* 0 = calibrated baseline (fw 349+) */
    mic_codec_t codec; /* 0 = WAV (pre-field default) */
    /* Low bits removed from every sample before it is stored, 0 to 4. 0 keeps
 the recording exactly as captured. Each bit dropped is about 6 dB of the
 noise floor given up and makes FLAC files markedly smaller (2 bits: about
 6:1 instead of 3.5:1 on collar recordings). Lossy and not reversible, so
 it is a separate knob from the codec. Ignored by firmware that predates it. */
    uint32_t lsb_drop;
} microphone_config_t;

typedef struct accelerometer_config {
    bool enabled;
    accel_sample_rate_t sample_rate;
    accel_sensitivity_t sensitivity;
} accelerometer_config_t;

typedef struct magnetometer_config {
    bool enabled;
    uint32_t sample_interval_s; /* in seconds */
    /* Rate mode (MAG-1, docs/DESIGN_magnetometer_rate.md; fw gate: firmware
 main build 425, merge c345dea 2026-09-25). Non-zero:
 the magnetometer streams X/Y/Z at this rate, paced by the 32.768 kHz
 crystal, into a 3-channel WAV with a time-anchor sidecar, and
 sample_interval_s is ignored. Allowed values are 1, 2, 4, 8 and 16 Hz;
 firmware treats any other value as 0, never a rounded guess.
 0 = interval mode: one mag,x,y,z row per sample_interval_s, exactly as
 before the field. proto3 does not encode a zero scalar, so a config that
 leaves this at 0 is byte-identical on the wire to one written before the
 field existed, and SchedSync_Crc, which hashes that encoding, is
 unchanged for every legacy config. Read only when enabled is true.
 Firmware that predates the field skips it and stays in interval mode,
 so clients gate the control on the reported build. */
    uint32_t sample_rate_hz;
} magnetometer_config_t;

/* schedule that is applied during each TimeWindow */
typedef struct schedule_config {
    bool has_window;
    time_window_t window;
    bool has_light;
    sampling_config_t light;
    bool has_environmental;
    sampling_config_t environmental;
    bool has_particulate;
    sampling_config_t particulate;
    bool has_gps;
    gps_config_t gps;
    bool has_microphone;
    microphone_config_t microphone;
    bool has_accelerometer;
    accelerometer_config_t accelerometer;
    /* LoRaWAN behavior within this schedule */
    bool lorawan_enabled;
    uint32_t lorawan_send_interval_min;
    bool lora_enabled;
    uint32_t lora_send_interval_min;
    bool has_magnetometer;
    magnetometer_config_t magnetometer;
} schedule_config_t;

typedef struct mag_cal_report {
    mag_cal_state_t state;
    /* Runs since boot: +1 each time CMD_MAG_CALIBRATE starts one, also when it
 fails at once. A client notes the run its start produced and ignores
 reports of older runs. Never 0 while mag_cal is present. */
    uint32_t run;
    /* Coverage toward the target, 0-100; 100 = target met, the capture ends
 and the fit starts. Frozen at its last value once the capture ends. */
    uint32_t progress_pct;
    uint32_t sectors_hit; /* of the 26 sphere sectors, those holding enough samples */
    mag_cal_verdict_t verdict; /* set when the run ends by itself (DONE or FAILED) */
    mag_cal_reason_t reason;
    /* From the fit, 0 until one exists: the total field |B| in 0.1 uT (the
 Earth's field reads roughly 250-650), and the RMS distance of the
 corrected samples from that sphere in per-mille of |B|, saturating at
 1000. */
    uint32_t field_ut_x10;
    uint32_t residual_permille;
} mag_cal_report_t;

typedef PB_BYTES_ARRAY_T(3) beacon_key_report_kcv_t;
typedef struct beacon_key_report {
    beacon_key_state_t state;
    /* The collar's current provision generation: the top byte of its transmit
 counter, which a clear and a factory reset keep. It is the key's own gen
 while KEYED, and at all times the floor a new key set must exceed. 0 =
 never provisioned (also after a mass erase, which loses the counter). */
    uint32_t gen;
    /* Key check value, AES-128(key, sixteen zero bytes)[0..2]: 3 bytes while a
 key is held, empty otherwise. Identifies the key without revealing it;
 provisioning tools display it and compare it with the server's record. */
    beacon_key_report_kcv_t kcv;
    beacon_key_result_t result;
    /* The transmit counter as it stands: [31:24] gen, [23:0] the sequence that
 never rewinds. Cleartext on every 0x4D frame anyway; here so a bench
 check sees it survive resets, and so an exhausted sequence (0xFFFFFF)
 explains a FALLBACK. */
    uint32_t tx_counter;
} beacon_key_report_t;

typedef PB_BYTES_ARRAY_T(88) cfg_echo_packet_fence_report_t;
typedef PB_BYTES_ARRAY_T(128) cfg_echo_packet_slot_report_t;
/* The BLE tunnel echo body. fence_report (ble_query=2 responses) is a
 version-tagged fixed binary record, NOT ConfigFragment framing: GeoPoint
 coordinates are plain int32, so a negative (western/southern) coordinate
 encodes as a 10-byte varint and a fragment-framed 8-vertex fence (~330 B)
 would blow the 350 B characteristic cap the deployed WB chips enforce.
 Layout (little-endian): [0]=0x01 format version, then
   [1]=fence_id [2]=action [3]=zone_slot [4]=confirm_fixes [5]=min_dwell_min
   [6]=max_hacc_m [7]=n_verts [8]=flags(bit0=consumed)
   [9..12]=start_epoch [13..16]=expiry_epoch
   then n_verts × (int32 lat_e7, int32 lon_e7) pairs = 8 B/vertex. */
typedef struct cfg_echo_packet {
    uint32_t txn_id; /* echoes DownlinkPacket.cfg_txn_id */
    uint32_t ack_status; /* ConfigAckStatus values (message.proto) */
    uint32_t missing_mask; /* missing-fragment bitmask / rails reason code */
    uint32_t fence_used_mask; /* bit N: fence slot N holds a definition */
    uint32_t fence_active_mask; /* bit N: collar is currently inside fence N+1 */
    uint32_t fence_fired_mask; /* bit N: detach fence N+1 has fired (consumed) */
    uint32_t sched_crc; /* current config identity (schedule+mortality+fences) */
    cfg_echo_packet_fence_report_t fence_report; /* one fence slot, binary record above (max 88 B) */
    /* Bumps on every echo push. The webapp paces the tunnel on it: each frame
 is written only after the previous frame's echo shows a new echo_seq —
 the settings blob is a single mailbox, so an unpaced second write would
 overwrite a frame the collar hadn't drained yet. */
    uint32_t echo_seq;
    /* CMD_FACTORY_RESET outcome, so the webapp reports what actually happened
 instead of assuming the command's delivery meant success:
 0 none, 1 contents deleted, 2 error, 3 SD not mounted, 4 timed out,
 5 card reformatted (the clean outcome). */
    uint32_t wipe_status;
    uint32_t wipe_removed; /* files/directories removed on the delete path */
    /* fw 358: schedule read-back. slot_report answers ble_query 3|(N<<8) with
 slot N as a nanopb-encoded ScheduleConfig (lean: ~60-100 B, max 128);
 schedule_count and engaged ride on EVERY echo so the webapp knows how
 many slots to ask for and the collar's engaged state without ever
 reading the resting blob. */
    cfg_echo_packet_slot_report_t slot_report;
    uint32_t schedule_count;
    bool engaged;
    /* Lost-mode beacon key status (CMD_BEACON_KEY_SET / _CLEAR, downlink.proto;
 DESIGN_radio_security.md section 4.3; fw gate: firmware main build TBD,
 set at merge). Present on EVERY echo that carries neither fence_report
 nor slot_report, from the first boot of firmware that has the key store,
 keyed or not: an unkeyed collar sends it empty (2 B on the wire), which
 is how a client tells "no key" (present, state NONE) from "not
 supported" (absent). Pushed after a key command and answered to
 ble_query = 1, which is how a client reads it back: the pre-flight check
 compares gen and kcv with the server's record. At most 20 B on the wire.
 Carries the generation and the 3-byte key check value, never the key. */
    bool has_beacon_key;
    beacon_key_report_t beacon_key;
    /* Magnetometer calibration (CMD_MAG_CALIBRATE, downlink.proto). Present on
 every echo that carries neither fence_report nor slot_report, once a run
 has started since boot. Absent before that, and always on firmware that
 predates calibration: that is how a client tells "never run" and "not
 supported" apart from a real state. The collar pushes no echo of its
 own during a run: an unsolicited push could overwrite a frame the client
 just wrote before the collar drains it (the settings blob is a single
 mailbox). So the client polls with ble_query = 1 about every 2 s and
 reads progress, then the outcome, from here. At most 26 B on the wire
 (about 20 B for a finished run); kept off the report echoes because a
 large slot_report already fills the 182 B read. */
    bool has_mag_cal;
    mag_cal_report_t mag_cal;
} cfg_echo_packet_t;

typedef PB_BYTES_ARRAY_T(96) schedule_config_packet_cfg_downlink_t;
/* can include multiple schedules */
typedef struct schedule_config_packet {
    bool engaged;
    pb_size_t schedules_count;
    schedule_config_t schedules[5]; /* capped to 5 schedules in options */
    uint32_t special_mode;
    /* ---- BLE config tunnel (fw 305+) ----
 Carries one serialized DownlinkPacket (downlink.proto) over the BLE
 settings characteristic, giving collars WITHOUT LoRaWAN the full remote
 config vocabulary (config transactions, geofences, CMD_TEST_FIX) through
 the same rails/verification engine as the radio path.

 Deliberately `bytes`, not a typed import: ble.proto stays self-contained
 (the Swift/WB toolchains never see downlink.proto), and both deployed WB
 chips (WB5M + frozen WB15) tag-gate writes on THIS payload arm before
 storing the raw blob — riding the schedule arm is what makes the tunnel
 work with zero WB firmware changes. Their stale schemas skip these
 unknown fields by standard protobuf rules.

 Receiver contract: when cfg_downlink is non-empty, `schedules`/`engaged`
 are IGNORED (this packet is a tunnel frame, not a schedule write).
 Old firmware (< 305) would misread a tunnel frame as an empty schedule,
 so the webapp hard-gates tunnel writes on the reported fw build. */
    schedule_config_packet_cfg_downlink_t cfg_downlink; /* one serialized DownlinkPacket (max 96 B) */
    /* BLE-native read-back requests (no radio involved). The collar answers by
 pushing an echo packet (cfg_echo below) into the settings blob for the
 webapp to poll.
   0        = none
   1        = echo status only (masks, last verdict)
   2|(N<<8) = echo geofence slot N (0..3) as a binary record
   3|(N<<8) = echo schedule slot N (0..4) as a ScheduleConfig message
              (fw 358): slot-by-slot read-back for schedules too large for
              the resting blob to survive the radios (one Bluetooth read
              carries 182 B; both radios cast the blob length to a byte) */
    uint32_t ble_query;
    /* Collar -> webapp echo. Pushed after a tunnel frame that produced a
 verdict, and after every ble_query. Deliberately a FIELD on this message,
 not its own BlePacket arm: the WB chips refresh the readable
 characteristic value only for blobs that decode to the schedule arm
 (system_schedule_updated is set inside their tag check) — an unknown arm
 would reach the blob store but never the characteristic. The collar
 re-pushes the canonical schedule blob ~10 s later so the resting value
 an old webapp reads is always a real schedule. */
    bool has_cfg_echo;
    cfg_echo_packet_t cfg_echo;
    /* Highest schedule-schema revision the WRITER of this packet understands
 (fw 357+). A writer that predates a field cannot round-trip it: it decodes
 a collar's schedule with its old schema, drops the unknown fields, and
 writes the flattened result back. For the calendar fields that silently
 turns a first-placed "weekends only" slot into an every-day slot. So the
 collar refuses a schedule write whose writer_version is below the
 revision of any feature RESIDENT in its current config, re-pushes the
 resident schedule, and logs it. 0 = legacy writer (never saw this field).
   1 = knows TimeWindow.day_mask / start_day / end_day */
    uint32_t writer_version;
} schedule_config_packet_t;

typedef struct simple_sensor_reading {
    uint32_t index;
    float temperature;
    float humidity;
    float pressure;
    float gas;
    float pm2_5;
    uint32_t light;
    activity_t activity;
    uint32_t steps;
    bool particulate_static_obstructed;
    bool particulate_dynamic_obstructed;
    bool particulate_outside_detection_limits;
} simple_sensor_reading_t;

typedef struct system_state_packet {
    bool engage_state; /* engaged/disengaged */
    bool has_battery;
    battery_state_t battery;
    bool has_sdcard;
    sd_card_state_t sdcard;
    bool has_gps_data;
    gps_data_t gps_data;
    bool has_sensors;
    simple_sensor_reading_t sensors;
    char firmware_version[16];
    /* Boot hardware-diagnostic bitmask (HW_RunDiagnostics, hw_diag.h).
 Bit SET = FAULT: 0 accelerometer, 1 magnetometer, 2 light sensor,
 3 BME688, 4 GPS, 5 particulate, 6 LoRa radio, 8 microphone (PDM
 capture flat/silent — bit 7 was already the validity flag when the
 mic check arrived, so mic jumps over it). Bit 7 = diagnostics ran
 (validity). Bits 0-7 are mirrored into Deployment.errorFlags.flag on
 LoRaWAN uplinks; the microphone fault is NOT mirrored on bit 8 (that
 position is mortality there), it rides ErrorFlags bit 10. Absent on
 older firmware. */
    bool has_hw_diag;
    uint32_t hw_diag;
} system_state_packet_t;

typedef struct peripheral_packet {
    pb_byte_t mac_address[6]; /* 6 bytes, fixed-length in options */
    peripheral_type_t type;
} peripheral_packet_t;

typedef struct peripheral_info {
    pb_callback_t device_uids;
} peripheral_info_t;

/* ================== WRAPPER ================== */
typedef struct ble_packet {
    bool has_header;
    packet_header_t header;
    pb_size_t which_payload;
    union {
        schedule_config_packet_t schedule_config_packet;
        system_state_packet_t system_state_packet;
        radio_config_packet_t radio_config_packet;
        peripheral_packet_t peripheral_packet;
        peripheral_info_t peripheral_info;
    } payload;
} ble_packet_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _RADIO_REGION_MIN RADIO_REGION_REGION_US915
#define _RADIO_REGION_MAX RADIO_REGION_REGION_EU868
#define _RADIO_REGION_ARRAYSIZE ((radio_region_t)(RADIO_REGION_REGION_EU868+1))

#define _RADIO_AUTH_MIN RADIO_AUTH_AUTH_OTAA
#define _RADIO_AUTH_MAX RADIO_AUTH_AUTH_ABP
#define _RADIO_AUTH_ARRAYSIZE ((radio_auth_t)(RADIO_AUTH_AUTH_ABP+1))

#define _RADIO_SPREADING_FACTOR_MIN RADIO_SPREADING_FACTOR_SF7
#define _RADIO_SPREADING_FACTOR_MAX RADIO_SPREADING_FACTOR_SF12
#define _RADIO_SPREADING_FACTOR_ARRAYSIZE ((radio_spreading_factor_t)(RADIO_SPREADING_FACTOR_SF12+1))

#define _RADIO_BANDWIDTH_MIN RADIO_BANDWIDTH_BW_125
#define _RADIO_BANDWIDTH_MAX RADIO_BANDWIDTH_BW_500
#define _RADIO_BANDWIDTH_ARRAYSIZE ((radio_bandwidth_t)(RADIO_BANDWIDTH_BW_500+1))

#define _RADIO_CODING_RATE_MIN RADIO_CODING_RATE_CR_4_5
#define _RADIO_CODING_RATE_MAX RADIO_CODING_RATE_CR_4_8
#define _RADIO_CODING_RATE_ARRAYSIZE ((radio_coding_rate_t)(RADIO_CODING_RATE_CR_4_8+1))

#define _MIC_SAMPLE_RATE_MIN MIC_SAMPLE_RATE_MIC_RATE_16_KHZ
#define _MIC_SAMPLE_RATE_MAX MIC_SAMPLE_RATE_MIC_RATE_192_KHZ
#define _MIC_SAMPLE_RATE_ARRAYSIZE ((mic_sample_rate_t)(MIC_SAMPLE_RATE_MIC_RATE_192_KHZ+1))

#define _MIC_BIT_DEPTH_MIN MIC_BIT_DEPTH_MIC_DEPTH_16_BIT
#define _MIC_BIT_DEPTH_MAX MIC_BIT_DEPTH_MIC_DEPTH_8_BIT
#define _MIC_BIT_DEPTH_ARRAYSIZE ((mic_bit_depth_t)(MIC_BIT_DEPTH_MIC_DEPTH_8_BIT+1))

#define _MIC_SENSITIVITY_MIN MIC_SENSITIVITY_MIC_SENS_LOW
#define _MIC_SENSITIVITY_MAX MIC_SENSITIVITY_MIC_SENS_HIGH
#define _MIC_SENSITIVITY_ARRAYSIZE ((mic_sensitivity_t)(MIC_SENSITIVITY_MIC_SENS_HIGH+1))

#define _MIC_CODEC_MIN MIC_CODEC_MIC_CODEC_WAV
#define _MIC_CODEC_MAX MIC_CODEC_MIC_CODEC_FLAC
#define _MIC_CODEC_ARRAYSIZE ((mic_codec_t)(MIC_CODEC_MIC_CODEC_FLAC+1))

#define _ACCEL_SAMPLE_RATE_MIN ACCEL_SAMPLE_RATE_ACCEL_25_HZ
#define _ACCEL_SAMPLE_RATE_MAX ACCEL_SAMPLE_RATE_ACCEL_50_HZ
#define _ACCEL_SAMPLE_RATE_ARRAYSIZE ((accel_sample_rate_t)(ACCEL_SAMPLE_RATE_ACCEL_50_HZ+1))

#define _ACCEL_SENSITIVITY_MIN ACCEL_SENSITIVITY_ACCEL_2_G
#define _ACCEL_SENSITIVITY_MAX ACCEL_SENSITIVITY_ACCEL_8_G
#define _ACCEL_SENSITIVITY_ARRAYSIZE ((accel_sensitivity_t)(ACCEL_SENSITIVITY_ACCEL_8_G+1))

#define _MAG_CAL_STATE_MIN MAG_CAL_STATE_MAG_CAL_STATE_IDLE
#define _MAG_CAL_STATE_MAX MAG_CAL_STATE_MAG_CAL_STATE_ABORTED
#define _MAG_CAL_STATE_ARRAYSIZE ((mag_cal_state_t)(MAG_CAL_STATE_MAG_CAL_STATE_ABORTED+1))

#define _MAG_CAL_VERDICT_MIN MAG_CAL_VERDICT_MAG_CAL_VERDICT_NONE
#define _MAG_CAL_VERDICT_MAX MAG_CAL_VERDICT_MAG_CAL_VERDICT_RETRY
#define _MAG_CAL_VERDICT_ARRAYSIZE ((mag_cal_verdict_t)(MAG_CAL_VERDICT_MAG_CAL_VERDICT_RETRY+1))

#define _MAG_CAL_REASON_MIN MAG_CAL_REASON_MAG_CAL_REASON_NONE
#define _MAG_CAL_REASON_MAX MAG_CAL_REASON_MAG_CAL_REASON_STORAGE
#define _MAG_CAL_REASON_ARRAYSIZE ((mag_cal_reason_t)(MAG_CAL_REASON_MAG_CAL_REASON_STORAGE+1))

#define _BEACON_KEY_STATE_MIN BEACON_KEY_STATE_BEACON_KEY_STATE_NONE
#define _BEACON_KEY_STATE_MAX BEACON_KEY_STATE_BEACON_KEY_STATE_FALLBACK
#define _BEACON_KEY_STATE_ARRAYSIZE ((beacon_key_state_t)(BEACON_KEY_STATE_BEACON_KEY_STATE_FALLBACK+1))

#define _BEACON_KEY_RESULT_MIN BEACON_KEY_RESULT_BEACON_KEY_RESULT_NONE
#define _BEACON_KEY_RESULT_MAX BEACON_KEY_RESULT_BEACON_KEY_RESULT_STORE_ERROR
#define _BEACON_KEY_RESULT_ARRAYSIZE ((beacon_key_result_t)(BEACON_KEY_RESULT_BEACON_KEY_RESULT_STORE_ERROR+1))

#define _PERIPHERAL_TYPE_MIN PERIPHERAL_TYPE_PERIPHERAL_SATCOM
#define _PERIPHERAL_TYPE_MAX PERIPHERAL_TYPE_PERIPHERAL_DETACHMENT
#define _PERIPHERAL_TYPE_ARRAYSIZE ((peripheral_type_t)(PERIPHERAL_TYPE_PERIPHERAL_DETACHMENT+1))






#define lo_ra_wan_config_t_region_ENUMTYPE radio_region_t
#define lo_ra_wan_config_t_auth_ENUMTYPE radio_auth_t

#define lo_ra_config_t_radio_spreading_factor_ENUMTYPE radio_spreading_factor_t
#define lo_ra_config_t_radio_bandwidth_ENUMTYPE radio_bandwidth_t
#define lo_ra_config_t_radio_coding_rate_ENUMTYPE radio_coding_rate_t




#define microphone_config_t_sample_rate_ENUMTYPE mic_sample_rate_t
#define microphone_config_t_bit_depth_ENUMTYPE mic_bit_depth_t
#define microphone_config_t_sensitivity_ENUMTYPE mic_sensitivity_t
#define microphone_config_t_codec_ENUMTYPE mic_codec_t

#define accelerometer_config_t_sample_rate_ENUMTYPE accel_sample_rate_t
#define accelerometer_config_t_sensitivity_ENUMTYPE accel_sensitivity_t





#define mag_cal_report_t_state_ENUMTYPE mag_cal_state_t
#define mag_cal_report_t_verdict_ENUMTYPE mag_cal_verdict_t
#define mag_cal_report_t_reason_ENUMTYPE mag_cal_reason_t

#define beacon_key_report_t_state_ENUMTYPE beacon_key_state_t
#define beacon_key_report_t_result_ENUMTYPE beacon_key_result_t

#define simple_sensor_reading_t_activity_ENUMTYPE activity_t


#define peripheral_packet_t_type_ENUMTYPE peripheral_type_t




/* Initializer values for message structs */
#define TIME_WINDOW_INIT_DEFAULT                 {0, 0, 0, 0, 0}
#define SAMPLING_CONFIG_INIT_DEFAULT             {0, 0}
#define GPS_CONFIG_INIT_DEFAULT                  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define RADIO_OTAA_INIT_DEFAULT                  {{0}, {0}, {0}, {0}}
#define RADIO_ABP_INIT_DEFAULT                   {{0}, {0}, {0}, {0}, {0}}
#define LO_RA_WAN_CONFIG_INIT_DEFAULT            {_RADIO_REGION_MIN, _RADIO_AUTH_MIN, 0, {RADIO_OTAA_INIT_DEFAULT}, 0, 0, 0}
#define LO_RA_CONFIG_INIT_DEFAULT                {_RADIO_SPREADING_FACTOR_MIN, _RADIO_BANDWIDTH_MIN, _RADIO_CODING_RATE_MIN, 0, 0, 0, 0}
#define LOST_MODE_CONFIG_INIT_DEFAULT            {0, 0, 0}
#define MORTALITY_CONFIG_INIT_DEFAULT            {0, 0}
#define RADIO_CONFIG_PACKET_INIT_DEFAULT         {false, LO_RA_WAN_CONFIG_INIT_DEFAULT, false, LO_RA_CONFIG_INIT_DEFAULT, 0, false, LOST_MODE_CONFIG_INIT_DEFAULT, 0, false, MORTALITY_CONFIG_INIT_DEFAULT}
#define MICROPHONE_CONFIG_INIT_DEFAULT           {0, 0, 0, 0, _MIC_SAMPLE_RATE_MIN, _MIC_BIT_DEPTH_MIN, _MIC_SENSITIVITY_MIN, _MIC_CODEC_MIN, 0}
#define ACCELEROMETER_CONFIG_INIT_DEFAULT        {0, _ACCEL_SAMPLE_RATE_MIN, _ACCEL_SENSITIVITY_MIN}
#define MAGNETOMETER_CONFIG_INIT_DEFAULT         {0, 0, 0}
#define SCHEDULE_CONFIG_INIT_DEFAULT             {false, TIME_WINDOW_INIT_DEFAULT, false, SAMPLING_CONFIG_INIT_DEFAULT, false, SAMPLING_CONFIG_INIT_DEFAULT, false, SAMPLING_CONFIG_INIT_DEFAULT, false, GPS_CONFIG_INIT_DEFAULT, false, MICROPHONE_CONFIG_INIT_DEFAULT, false, ACCELEROMETER_CONFIG_INIT_DEFAULT, 0, 0, 0, 0, false, MAGNETOMETER_CONFIG_INIT_DEFAULT}
#define SCHEDULE_CONFIG_PACKET_INIT_DEFAULT      {0, 0, {SCHEDULE_CONFIG_INIT_DEFAULT, SCHEDULE_CONFIG_INIT_DEFAULT, SCHEDULE_CONFIG_INIT_DEFAULT, SCHEDULE_CONFIG_INIT_DEFAULT, SCHEDULE_CONFIG_INIT_DEFAULT}, 0, {0, {0}}, 0, false, CFG_ECHO_PACKET_INIT_DEFAULT, 0}
#define CFG_ECHO_PACKET_INIT_DEFAULT             {0, 0, 0, 0, 0, 0, 0, {0, {0}}, 0, 0, 0, {0, {0}}, 0, 0, false, BEACON_KEY_REPORT_INIT_DEFAULT, false, MAG_CAL_REPORT_INIT_DEFAULT}
#define MAG_CAL_REPORT_INIT_DEFAULT              {_MAG_CAL_STATE_MIN, 0, 0, 0, _MAG_CAL_VERDICT_MIN, _MAG_CAL_REASON_MIN, 0, 0}
#define BEACON_KEY_REPORT_INIT_DEFAULT           {_BEACON_KEY_STATE_MIN, 0, {0, {0}}, _BEACON_KEY_RESULT_MIN, 0}
#define SIMPLE_SENSOR_READING_INIT_DEFAULT       {0, 0, 0, 0, 0, 0, 0, _ACTIVITY_MIN, 0, 0, 0, 0}
#define SYSTEM_STATE_PACKET_INIT_DEFAULT         {0, false, BATTERY_STATE_INIT_DEFAULT, false, SD_CARD_STATE_INIT_DEFAULT, false, GPS_DATA_INIT_DEFAULT, false, SIMPLE_SENSOR_READING_INIT_DEFAULT, "", false, 0}
#define PERIPHERAL_PACKET_INIT_DEFAULT           {{0}, _PERIPHERAL_TYPE_MIN}
#define PERIPHERAL_INFO_INIT_DEFAULT             {{{NULL}, NULL}}
#define BLE_PACKET_INIT_DEFAULT                  {false, PACKET_HEADER_INIT_DEFAULT, 0, {SCHEDULE_CONFIG_PACKET_INIT_DEFAULT}}
#define TIME_WINDOW_INIT_ZERO                    {0, 0, 0, 0, 0}
#define SAMPLING_CONFIG_INIT_ZERO                {0, 0}
#define GPS_CONFIG_INIT_ZERO                     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define RADIO_OTAA_INIT_ZERO                     {{0}, {0}, {0}, {0}}
#define RADIO_ABP_INIT_ZERO                      {{0}, {0}, {0}, {0}, {0}}
#define LO_RA_WAN_CONFIG_INIT_ZERO               {_RADIO_REGION_MIN, _RADIO_AUTH_MIN, 0, {RADIO_OTAA_INIT_ZERO}, 0, 0, 0}
#define LO_RA_CONFIG_INIT_ZERO                   {_RADIO_SPREADING_FACTOR_MIN, _RADIO_BANDWIDTH_MIN, _RADIO_CODING_RATE_MIN, 0, 0, 0, 0}
#define LOST_MODE_CONFIG_INIT_ZERO               {0, 0, 0}
#define MORTALITY_CONFIG_INIT_ZERO               {0, 0}
#define RADIO_CONFIG_PACKET_INIT_ZERO            {false, LO_RA_WAN_CONFIG_INIT_ZERO, false, LO_RA_CONFIG_INIT_ZERO, 0, false, LOST_MODE_CONFIG_INIT_ZERO, 0, false, MORTALITY_CONFIG_INIT_ZERO}
#define MICROPHONE_CONFIG_INIT_ZERO              {0, 0, 0, 0, _MIC_SAMPLE_RATE_MIN, _MIC_BIT_DEPTH_MIN, _MIC_SENSITIVITY_MIN, _MIC_CODEC_MIN, 0}
#define ACCELEROMETER_CONFIG_INIT_ZERO           {0, _ACCEL_SAMPLE_RATE_MIN, _ACCEL_SENSITIVITY_MIN}
#define MAGNETOMETER_CONFIG_INIT_ZERO            {0, 0, 0}
#define SCHEDULE_CONFIG_INIT_ZERO                {false, TIME_WINDOW_INIT_ZERO, false, SAMPLING_CONFIG_INIT_ZERO, false, SAMPLING_CONFIG_INIT_ZERO, false, SAMPLING_CONFIG_INIT_ZERO, false, GPS_CONFIG_INIT_ZERO, false, MICROPHONE_CONFIG_INIT_ZERO, false, ACCELEROMETER_CONFIG_INIT_ZERO, 0, 0, 0, 0, false, MAGNETOMETER_CONFIG_INIT_ZERO}
#define SCHEDULE_CONFIG_PACKET_INIT_ZERO         {0, 0, {SCHEDULE_CONFIG_INIT_ZERO, SCHEDULE_CONFIG_INIT_ZERO, SCHEDULE_CONFIG_INIT_ZERO, SCHEDULE_CONFIG_INIT_ZERO, SCHEDULE_CONFIG_INIT_ZERO}, 0, {0, {0}}, 0, false, CFG_ECHO_PACKET_INIT_ZERO, 0}
#define CFG_ECHO_PACKET_INIT_ZERO                {0, 0, 0, 0, 0, 0, 0, {0, {0}}, 0, 0, 0, {0, {0}}, 0, 0, false, BEACON_KEY_REPORT_INIT_ZERO, false, MAG_CAL_REPORT_INIT_ZERO}
#define MAG_CAL_REPORT_INIT_ZERO                 {_MAG_CAL_STATE_MIN, 0, 0, 0, _MAG_CAL_VERDICT_MIN, _MAG_CAL_REASON_MIN, 0, 0}
#define BEACON_KEY_REPORT_INIT_ZERO              {_BEACON_KEY_STATE_MIN, 0, {0, {0}}, _BEACON_KEY_RESULT_MIN, 0}
#define SIMPLE_SENSOR_READING_INIT_ZERO          {0, 0, 0, 0, 0, 0, 0, _ACTIVITY_MIN, 0, 0, 0, 0}
#define SYSTEM_STATE_PACKET_INIT_ZERO            {0, false, BATTERY_STATE_INIT_ZERO, false, SD_CARD_STATE_INIT_ZERO, false, GPS_DATA_INIT_ZERO, false, SIMPLE_SENSOR_READING_INIT_ZERO, "", false, 0}
#define PERIPHERAL_PACKET_INIT_ZERO              {{0}, _PERIPHERAL_TYPE_MIN}
#define PERIPHERAL_INFO_INIT_ZERO                {{{NULL}, NULL}}
#define BLE_PACKET_INIT_ZERO                     {false, PACKET_HEADER_INIT_ZERO, 0, {SCHEDULE_CONFIG_PACKET_INIT_ZERO}}

/* Field tags (for use in manual encoding/decoding) */
#define TIME_WINDOW_START_HOUR_TAG               1
#define TIME_WINDOW_END_HOUR_TAG                 2
#define TIME_WINDOW_DAY_MASK_TAG                 3
#define TIME_WINDOW_START_DAY_TAG                4
#define TIME_WINDOW_END_DAY_TAG                  5
#define SAMPLING_CONFIG_ENABLED_TAG              1
#define SAMPLING_CONFIG_SAMPLE_INTERVAL_MIN_TAG  2
#define GPS_CONFIG_ENABLED_TAG                   1
#define GPS_CONFIG_SAMPLE_INTERVAL_MIN_TAG       2
#define GPS_CONFIG_ACCURACY_TAG                  3
#define GPS_CONFIG_DYNAMIC_SAMPLING_MODE_TAG     4
#define GPS_CONFIG_MEDIUM_MOTION_VEDBA_THRESHOLD_X100_TAG 5
#define GPS_CONFIG_MEDIUM_MOTION_GPS_INTERVAL_MIN_TAG 6
#define GPS_CONFIG_HIGH_MOTION_VEDBA_THRESHOLD_X100_TAG 7
#define GPS_CONFIG_HIGH_MOTION_GPS_INTERVAL_MIN_TAG 8
#define GPS_CONFIG_LORAWAN_TX_ON_GPS_FIX_TAG     9
#define GPS_CONFIG_LORA_TX_ON_GPS_FIX_TAG        10
#define RADIO_OTAA_DEV_EUI_TAG                   1
#define RADIO_OTAA_JOIN_EUI_TAG                  2
#define RADIO_OTAA_APP_KEY_TAG                   3
#define RADIO_OTAA_NWK_KEY_TAG                   4
#define RADIO_ABP_DEV_ADDR_TAG                   1
#define RADIO_ABP_NWK_S_KEY_TAG                  2
#define RADIO_ABP_APP_S_KEY_TAG                  3
#define RADIO_ABP_F_NWK_S_INT_KEY_TAG            4
#define RADIO_ABP_S_NWK_S_INT_KEY_TAG            5
#define LO_RA_WAN_CONFIG_REGION_TAG              1
#define LO_RA_WAN_CONFIG_AUTH_TAG                2
#define LO_RA_WAN_CONFIG_OTAA_TAG                3
#define LO_RA_WAN_CONFIG_ABP_TAG                 4
#define LO_RA_WAN_CONFIG_TRANSMIT_INTERVAL_MIN_TAG 5
#define LO_RA_WAN_CONFIG_TX_ONLY_ON_NEW_GPS_FIX_TAG 6
#define LO_RA_WAN_CONFIG_TX_POWER_DBM_TAG        7
#define LO_RA_CONFIG_RADIO_SPREADING_FACTOR_TAG  1
#define LO_RA_CONFIG_RADIO_BANDWIDTH_TAG         2
#define LO_RA_CONFIG_RADIO_CODING_RATE_TAG       3
#define LO_RA_CONFIG_TX_POWER_DBM_TAG            4
#define LO_RA_CONFIG_SYNC_WORD_TAG               5
#define LO_RA_CONFIG_FREQUENCY_TAG               6
#define LO_RA_CONFIG_RX_LISTEN_TAG               7
#define LOST_MODE_CONFIG_ACTIVATION_EPOCH_TAG    1
#define LOST_MODE_CONFIG_TRANSMIT_INTERVAL_MIN_TAG 2
#define LOST_MODE_CONFIG_TX_POWER_DBM_TAG        3
#define MORTALITY_CONFIG_TRIGGER_DURATION_HOURS_TAG 1
#define MORTALITY_CONFIG_TRANSMIT_INTERVAL_MIN_TAG 2
#define RADIO_CONFIG_PACKET_LO_RA_WAN_CONFIG_TAG 1
#define RADIO_CONFIG_PACKET_LO_RA_CONFIG_TAG     2
#define RADIO_CONFIG_PACKET_LOST_MODE_ENABLED_TAG 3
#define RADIO_CONFIG_PACKET_LOST_MODE_CONFIG_TAG 4
#define RADIO_CONFIG_PACKET_MORTALITY_ENABLED_TAG 5
#define RADIO_CONFIG_PACKET_MORTALITY_CONFIG_TAG 6
#define MICROPHONE_CONFIG_ENABLED_TAG            1
#define MICROPHONE_CONFIG_CONTINUOUS_MODE_TAG    2
#define MICROPHONE_CONFIG_SAMPLE_LENGTH_MIN_TAG  3
#define MICROPHONE_CONFIG_SAMPLE_WINDOW_MIN_TAG  4
#define MICROPHONE_CONFIG_SAMPLE_RATE_TAG        5
#define MICROPHONE_CONFIG_BIT_DEPTH_TAG          6
#define MICROPHONE_CONFIG_SENSITIVITY_TAG        7
#define MICROPHONE_CONFIG_CODEC_TAG              8
#define MICROPHONE_CONFIG_LSB_DROP_TAG           9
#define ACCELEROMETER_CONFIG_ENABLED_TAG         1
#define ACCELEROMETER_CONFIG_SAMPLE_RATE_TAG     2
#define ACCELEROMETER_CONFIG_SENSITIVITY_TAG     3
#define MAGNETOMETER_CONFIG_ENABLED_TAG          1
#define MAGNETOMETER_CONFIG_SAMPLE_INTERVAL_S_TAG 2
#define MAGNETOMETER_CONFIG_SAMPLE_RATE_HZ_TAG   3
#define SCHEDULE_CONFIG_WINDOW_TAG               1
#define SCHEDULE_CONFIG_LIGHT_TAG                2
#define SCHEDULE_CONFIG_ENVIRONMENTAL_TAG        3
#define SCHEDULE_CONFIG_PARTICULATE_TAG          4
#define SCHEDULE_CONFIG_GPS_TAG                  5
#define SCHEDULE_CONFIG_MICROPHONE_TAG           6
#define SCHEDULE_CONFIG_ACCELEROMETER_TAG        7
#define SCHEDULE_CONFIG_LORAWAN_ENABLED_TAG      8
#define SCHEDULE_CONFIG_LORAWAN_SEND_INTERVAL_MIN_TAG 9
#define SCHEDULE_CONFIG_LORA_ENABLED_TAG         10
#define SCHEDULE_CONFIG_LORA_SEND_INTERVAL_MIN_TAG 11
#define SCHEDULE_CONFIG_MAGNETOMETER_TAG         12
#define MAG_CAL_REPORT_STATE_TAG                 1
#define MAG_CAL_REPORT_RUN_TAG                   2
#define MAG_CAL_REPORT_PROGRESS_PCT_TAG          3
#define MAG_CAL_REPORT_SECTORS_HIT_TAG           4
#define MAG_CAL_REPORT_VERDICT_TAG               5
#define MAG_CAL_REPORT_REASON_TAG                6
#define MAG_CAL_REPORT_FIELD_UT_X10_TAG          7
#define MAG_CAL_REPORT_RESIDUAL_PERMILLE_TAG     8
#define BEACON_KEY_REPORT_STATE_TAG              1
#define BEACON_KEY_REPORT_GEN_TAG                2
#define BEACON_KEY_REPORT_KCV_TAG                3
#define BEACON_KEY_REPORT_RESULT_TAG             4
#define BEACON_KEY_REPORT_TX_COUNTER_TAG         5
#define CFG_ECHO_PACKET_TXN_ID_TAG               1
#define CFG_ECHO_PACKET_ACK_STATUS_TAG           2
#define CFG_ECHO_PACKET_MISSING_MASK_TAG         3
#define CFG_ECHO_PACKET_FENCE_USED_MASK_TAG      4
#define CFG_ECHO_PACKET_FENCE_ACTIVE_MASK_TAG    5
#define CFG_ECHO_PACKET_FENCE_FIRED_MASK_TAG     6
#define CFG_ECHO_PACKET_SCHED_CRC_TAG            7
#define CFG_ECHO_PACKET_FENCE_REPORT_TAG         8
#define CFG_ECHO_PACKET_ECHO_SEQ_TAG             9
#define CFG_ECHO_PACKET_WIPE_STATUS_TAG          10
#define CFG_ECHO_PACKET_WIPE_REMOVED_TAG         11
#define CFG_ECHO_PACKET_SLOT_REPORT_TAG          12
#define CFG_ECHO_PACKET_SCHEDULE_COUNT_TAG       13
#define CFG_ECHO_PACKET_ENGAGED_TAG              14
#define CFG_ECHO_PACKET_BEACON_KEY_TAG           15
#define CFG_ECHO_PACKET_MAG_CAL_TAG              16
#define SCHEDULE_CONFIG_PACKET_ENGAGED_TAG       1
#define SCHEDULE_CONFIG_PACKET_SCHEDULES_TAG     2
#define SCHEDULE_CONFIG_PACKET_SPECIAL_MODE_TAG  3
#define SCHEDULE_CONFIG_PACKET_CFG_DOWNLINK_TAG  4
#define SCHEDULE_CONFIG_PACKET_BLE_QUERY_TAG     5
#define SCHEDULE_CONFIG_PACKET_CFG_ECHO_TAG      6
#define SCHEDULE_CONFIG_PACKET_WRITER_VERSION_TAG 7
#define SIMPLE_SENSOR_READING_INDEX_TAG          1
#define SIMPLE_SENSOR_READING_TEMPERATURE_TAG    2
#define SIMPLE_SENSOR_READING_HUMIDITY_TAG       3
#define SIMPLE_SENSOR_READING_PRESSURE_TAG       4
#define SIMPLE_SENSOR_READING_GAS_TAG            5
#define SIMPLE_SENSOR_READING_PM2_5_TAG          6
#define SIMPLE_SENSOR_READING_LIGHT_TAG          7
#define SIMPLE_SENSOR_READING_ACTIVITY_TAG       8
#define SIMPLE_SENSOR_READING_STEPS_TAG          9
#define SIMPLE_SENSOR_READING_PARTICULATE_STATIC_OBSTRUCTED_TAG 10
#define SIMPLE_SENSOR_READING_PARTICULATE_DYNAMIC_OBSTRUCTED_TAG 11
#define SIMPLE_SENSOR_READING_PARTICULATE_OUTSIDE_DETECTION_LIMITS_TAG 12
#define SYSTEM_STATE_PACKET_ENGAGE_STATE_TAG     1
#define SYSTEM_STATE_PACKET_BATTERY_TAG          2
#define SYSTEM_STATE_PACKET_SDCARD_TAG           3
#define SYSTEM_STATE_PACKET_GPS_DATA_TAG         4
#define SYSTEM_STATE_PACKET_SENSORS_TAG          5
#define SYSTEM_STATE_PACKET_FIRMWARE_VERSION_TAG 6
#define SYSTEM_STATE_PACKET_HW_DIAG_TAG          7
#define PERIPHERAL_PACKET_MAC_ADDRESS_TAG        1
#define PERIPHERAL_PACKET_TYPE_TAG               2
#define PERIPHERAL_INFO_DEVICE_UIDS_TAG          1
#define BLE_PACKET_HEADER_TAG                    1
#define BLE_PACKET_SCHEDULE_CONFIG_PACKET_TAG    2
#define BLE_PACKET_SYSTEM_STATE_PACKET_TAG       3
#define BLE_PACKET_RADIO_CONFIG_PACKET_TAG       4
#define BLE_PACKET_PERIPHERAL_PACKET_TAG         5
#define BLE_PACKET_PERIPHERAL_INFO_TAG           6

/* Struct field encoding specification for nanopb */
#define TIME_WINDOW_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   start_hour,        1) \
X(a, STATIC,   SINGULAR, UINT32,   end_hour,          2) \
X(a, STATIC,   SINGULAR, UINT32,   day_mask,          3) \
X(a, STATIC,   SINGULAR, UINT32,   start_day,         4) \
X(a, STATIC,   SINGULAR, UINT32,   end_day,           5)
#define TIME_WINDOW_CALLBACK NULL
#define TIME_WINDOW_DEFAULT NULL

#define SAMPLING_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, UINT32,   sample_interval_min,   2)
#define SAMPLING_CONFIG_CALLBACK NULL
#define SAMPLING_CONFIG_DEFAULT NULL

#define GPS_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, UINT32,   sample_interval_min,   2) \
X(a, STATIC,   SINGULAR, UINT32,   accuracy,          3) \
X(a, STATIC,   SINGULAR, BOOL,     dynamic_sampling_mode,   4) \
X(a, STATIC,   SINGULAR, UINT32,   medium_motion_vedba_threshold_x100,   5) \
X(a, STATIC,   SINGULAR, UINT32,   medium_motion_gps_interval_min,   6) \
X(a, STATIC,   SINGULAR, UINT32,   high_motion_vedba_threshold_x100,   7) \
X(a, STATIC,   SINGULAR, UINT32,   high_motion_gps_interval_min,   8) \
X(a, STATIC,   SINGULAR, BOOL,     lorawan_tx_on_gps_fix,   9) \
X(a, STATIC,   SINGULAR, BOOL,     lora_tx_on_gps_fix,  10)
#define GPS_CONFIG_CALLBACK NULL
#define GPS_CONFIG_DEFAULT NULL

#define RADIO_OTAA_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, dev_eui,           1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, join_eui,          2) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, app_key,           3) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, nwk_key,           4)
#define RADIO_OTAA_CALLBACK NULL
#define RADIO_OTAA_DEFAULT NULL

#define RADIO_ABP_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, dev_addr,          1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, nwk_s_key,         2) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, app_s_key,         3) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, f_nwk_s_int_key,   4) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, s_nwk_s_int_key,   5)
#define RADIO_ABP_CALLBACK NULL
#define RADIO_ABP_DEFAULT NULL

#define LO_RA_WAN_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    region,            1) \
X(a, STATIC,   SINGULAR, UENUM,    auth,              2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (credentials,otaa,credentials.otaa),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (credentials,abp,credentials.abp),   4) \
X(a, STATIC,   SINGULAR, UINT32,   transmit_interval_min,   5) \
X(a, STATIC,   SINGULAR, BOOL,     tx_only_on_new_gps_fix,   6) \
X(a, STATIC,   SINGULAR, INT32,    tx_power_dbm,      7)
#define LO_RA_WAN_CONFIG_CALLBACK NULL
#define LO_RA_WAN_CONFIG_DEFAULT NULL
#define lo_ra_wan_config_t_credentials_otaa_MSGTYPE radio_otaa_t
#define lo_ra_wan_config_t_credentials_abp_MSGTYPE radio_abp_t

#define LO_RA_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    radio_spreading_factor,   1) \
X(a, STATIC,   SINGULAR, UENUM,    radio_bandwidth,   2) \
X(a, STATIC,   SINGULAR, UENUM,    radio_coding_rate,   3) \
X(a, STATIC,   SINGULAR, INT32,    tx_power_dbm,      4) \
X(a, STATIC,   SINGULAR, UINT32,   sync_word,         5) \
X(a, STATIC,   SINGULAR, UINT32,   frequency,         6) \
X(a, STATIC,   SINGULAR, BOOL,     rx_listen,         7)
#define LO_RA_CONFIG_CALLBACK NULL
#define LO_RA_CONFIG_DEFAULT NULL

#define LOST_MODE_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   activation_epoch,   1) \
X(a, STATIC,   SINGULAR, UINT32,   transmit_interval_min,   2) \
X(a, STATIC,   SINGULAR, INT32,    tx_power_dbm,      3)
#define LOST_MODE_CONFIG_CALLBACK NULL
#define LOST_MODE_CONFIG_DEFAULT NULL

#define MORTALITY_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   trigger_duration_hours,   1) \
X(a, STATIC,   SINGULAR, UINT32,   transmit_interval_min,   2)
#define MORTALITY_CONFIG_CALLBACK NULL
#define MORTALITY_CONFIG_DEFAULT NULL

#define RADIO_CONFIG_PACKET_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  lo_ra_wan_config,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  lo_ra_config,      2) \
X(a, STATIC,   SINGULAR, BOOL,     lost_mode_enabled,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  lost_mode_config,   4) \
X(a, STATIC,   SINGULAR, BOOL,     mortality_enabled,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mortality_config,   6)
#define RADIO_CONFIG_PACKET_CALLBACK NULL
#define RADIO_CONFIG_PACKET_DEFAULT NULL
#define radio_config_packet_t_lo_ra_wan_config_MSGTYPE lo_ra_wan_config_t
#define radio_config_packet_t_lo_ra_config_MSGTYPE lo_ra_config_t
#define radio_config_packet_t_lost_mode_config_MSGTYPE lost_mode_config_t
#define radio_config_packet_t_mortality_config_MSGTYPE mortality_config_t

#define MICROPHONE_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, BOOL,     continuous_mode,   2) \
X(a, STATIC,   SINGULAR, UINT32,   sample_length_min,   3) \
X(a, STATIC,   SINGULAR, UINT32,   sample_window_min,   4) \
X(a, STATIC,   SINGULAR, UENUM,    sample_rate,       5) \
X(a, STATIC,   SINGULAR, UENUM,    bit_depth,         6) \
X(a, STATIC,   SINGULAR, UENUM,    sensitivity,       7) \
X(a, STATIC,   SINGULAR, UENUM,    codec,             8) \
X(a, STATIC,   SINGULAR, UINT32,   lsb_drop,          9)
#define MICROPHONE_CONFIG_CALLBACK NULL
#define MICROPHONE_CONFIG_DEFAULT NULL

#define ACCELEROMETER_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, UENUM,    sample_rate,       2) \
X(a, STATIC,   SINGULAR, UENUM,    sensitivity,       3)
#define ACCELEROMETER_CONFIG_CALLBACK NULL
#define ACCELEROMETER_CONFIG_DEFAULT NULL

#define MAGNETOMETER_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, UINT32,   sample_interval_s,   2) \
X(a, STATIC,   SINGULAR, UINT32,   sample_rate_hz,    3)
#define MAGNETOMETER_CONFIG_CALLBACK NULL
#define MAGNETOMETER_CONFIG_DEFAULT NULL

#define SCHEDULE_CONFIG_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  window,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  light,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  environmental,     3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  particulate,       4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gps,               5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  microphone,        6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  accelerometer,     7) \
X(a, STATIC,   SINGULAR, BOOL,     lorawan_enabled,   8) \
X(a, STATIC,   SINGULAR, UINT32,   lorawan_send_interval_min,   9) \
X(a, STATIC,   SINGULAR, BOOL,     lora_enabled,     10) \
X(a, STATIC,   SINGULAR, UINT32,   lora_send_interval_min,  11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  magnetometer,     12)
#define SCHEDULE_CONFIG_CALLBACK NULL
#define SCHEDULE_CONFIG_DEFAULT NULL
#define schedule_config_t_window_MSGTYPE time_window_t
#define schedule_config_t_light_MSGTYPE sampling_config_t
#define schedule_config_t_environmental_MSGTYPE sampling_config_t
#define schedule_config_t_particulate_MSGTYPE sampling_config_t
#define schedule_config_t_gps_MSGTYPE gps_config_t
#define schedule_config_t_microphone_MSGTYPE microphone_config_t
#define schedule_config_t_accelerometer_MSGTYPE accelerometer_config_t
#define schedule_config_t_magnetometer_MSGTYPE magnetometer_config_t

#define SCHEDULE_CONFIG_PACKET_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     engaged,           1) \
X(a, STATIC,   REPEATED, MESSAGE,  schedules,         2) \
X(a, STATIC,   SINGULAR, UINT32,   special_mode,      3) \
X(a, STATIC,   SINGULAR, BYTES,    cfg_downlink,      4) \
X(a, STATIC,   SINGULAR, UINT32,   ble_query,         5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cfg_echo,          6) \
X(a, STATIC,   SINGULAR, UINT32,   writer_version,    7)
#define SCHEDULE_CONFIG_PACKET_CALLBACK NULL
#define SCHEDULE_CONFIG_PACKET_DEFAULT NULL
#define schedule_config_packet_t_schedules_MSGTYPE schedule_config_t
#define schedule_config_packet_t_cfg_echo_MSGTYPE cfg_echo_packet_t

#define CFG_ECHO_PACKET_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   txn_id,            1) \
X(a, STATIC,   SINGULAR, UINT32,   ack_status,        2) \
X(a, STATIC,   SINGULAR, UINT32,   missing_mask,      3) \
X(a, STATIC,   SINGULAR, UINT32,   fence_used_mask,   4) \
X(a, STATIC,   SINGULAR, UINT32,   fence_active_mask,   5) \
X(a, STATIC,   SINGULAR, UINT32,   fence_fired_mask,   6) \
X(a, STATIC,   SINGULAR, UINT32,   sched_crc,         7) \
X(a, STATIC,   SINGULAR, BYTES,    fence_report,      8) \
X(a, STATIC,   SINGULAR, UINT32,   echo_seq,          9) \
X(a, STATIC,   SINGULAR, UINT32,   wipe_status,      10) \
X(a, STATIC,   SINGULAR, UINT32,   wipe_removed,     11) \
X(a, STATIC,   SINGULAR, BYTES,    slot_report,      12) \
X(a, STATIC,   SINGULAR, UINT32,   schedule_count,   13) \
X(a, STATIC,   SINGULAR, BOOL,     engaged,          14) \
X(a, STATIC,   OPTIONAL, MESSAGE,  beacon_key,       15) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mag_cal,          16)
#define CFG_ECHO_PACKET_CALLBACK NULL
#define CFG_ECHO_PACKET_DEFAULT NULL
#define cfg_echo_packet_t_beacon_key_MSGTYPE beacon_key_report_t
#define cfg_echo_packet_t_mag_cal_MSGTYPE mag_cal_report_t

#define MAG_CAL_REPORT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, STATIC,   SINGULAR, UINT32,   run,               2) \
X(a, STATIC,   SINGULAR, UINT32,   progress_pct,      3) \
X(a, STATIC,   SINGULAR, UINT32,   sectors_hit,       4) \
X(a, STATIC,   SINGULAR, UENUM,    verdict,           5) \
X(a, STATIC,   SINGULAR, UENUM,    reason,            6) \
X(a, STATIC,   SINGULAR, UINT32,   field_ut_x10,      7) \
X(a, STATIC,   SINGULAR, UINT32,   residual_permille,   8)
#define MAG_CAL_REPORT_CALLBACK NULL
#define MAG_CAL_REPORT_DEFAULT NULL

#define BEACON_KEY_REPORT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, STATIC,   SINGULAR, UINT32,   gen,               2) \
X(a, STATIC,   SINGULAR, BYTES,    kcv,               3) \
X(a, STATIC,   SINGULAR, UENUM,    result,            4) \
X(a, STATIC,   SINGULAR, UINT32,   tx_counter,        5)
#define BEACON_KEY_REPORT_CALLBACK NULL
#define BEACON_KEY_REPORT_DEFAULT NULL

#define SIMPLE_SENSOR_READING_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   index,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          3) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure,          4) \
X(a, STATIC,   SINGULAR, FLOAT,    gas,               5) \
X(a, STATIC,   SINGULAR, FLOAT,    pm2_5,             6) \
X(a, STATIC,   SINGULAR, UINT32,   light,             7) \
X(a, STATIC,   SINGULAR, UENUM,    activity,          8) \
X(a, STATIC,   SINGULAR, UINT32,   steps,             9) \
X(a, STATIC,   SINGULAR, BOOL,     particulate_static_obstructed,  10) \
X(a, STATIC,   SINGULAR, BOOL,     particulate_dynamic_obstructed,  11) \
X(a, STATIC,   SINGULAR, BOOL,     particulate_outside_detection_limits,  12)
#define SIMPLE_SENSOR_READING_CALLBACK NULL
#define SIMPLE_SENSOR_READING_DEFAULT NULL

#define SYSTEM_STATE_PACKET_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     engage_state,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  battery,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sdcard,            3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gps_data,          4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sensors,           5) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   6) \
X(a, STATIC,   OPTIONAL, UINT32,   hw_diag,           7)
#define SYSTEM_STATE_PACKET_CALLBACK NULL
#define SYSTEM_STATE_PACKET_DEFAULT NULL
#define system_state_packet_t_battery_MSGTYPE battery_state_t
#define system_state_packet_t_sdcard_MSGTYPE sd_card_state_t
#define system_state_packet_t_gps_data_MSGTYPE gps_data_t
#define system_state_packet_t_sensors_MSGTYPE simple_sensor_reading_t

#define PERIPHERAL_PACKET_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, mac_address,       1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2)
#define PERIPHERAL_PACKET_CALLBACK NULL
#define PERIPHERAL_PACKET_DEFAULT NULL

#define PERIPHERAL_INFO_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   device_uids,       1)
#define PERIPHERAL_INFO_CALLBACK pb_default_field_callback
#define PERIPHERAL_INFO_DEFAULT NULL

#define BLE_PACKET_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,schedule_config_packet,payload.schedule_config_packet),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,system_state_packet,payload.system_state_packet),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,radio_config_packet,payload.radio_config_packet),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,peripheral_packet,payload.peripheral_packet),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,peripheral_info,payload.peripheral_info),   6)
#define BLE_PACKET_CALLBACK NULL
#define BLE_PACKET_DEFAULT NULL
#define ble_packet_t_header_MSGTYPE packet_header_t
#define ble_packet_t_payload_schedule_config_packet_MSGTYPE schedule_config_packet_t
#define ble_packet_t_payload_system_state_packet_MSGTYPE system_state_packet_t
#define ble_packet_t_payload_radio_config_packet_MSGTYPE radio_config_packet_t
#define ble_packet_t_payload_peripheral_packet_MSGTYPE peripheral_packet_t
#define ble_packet_t_payload_peripheral_info_MSGTYPE peripheral_info_t

extern const pb_msgdesc_t time_window_t_msg;
extern const pb_msgdesc_t sampling_config_t_msg;
extern const pb_msgdesc_t gps_config_t_msg;
extern const pb_msgdesc_t radio_otaa_t_msg;
extern const pb_msgdesc_t radio_abp_t_msg;
extern const pb_msgdesc_t lo_ra_wan_config_t_msg;
extern const pb_msgdesc_t lo_ra_config_t_msg;
extern const pb_msgdesc_t lost_mode_config_t_msg;
extern const pb_msgdesc_t mortality_config_t_msg;
extern const pb_msgdesc_t radio_config_packet_t_msg;
extern const pb_msgdesc_t microphone_config_t_msg;
extern const pb_msgdesc_t accelerometer_config_t_msg;
extern const pb_msgdesc_t magnetometer_config_t_msg;
extern const pb_msgdesc_t schedule_config_t_msg;
extern const pb_msgdesc_t schedule_config_packet_t_msg;
extern const pb_msgdesc_t cfg_echo_packet_t_msg;
extern const pb_msgdesc_t mag_cal_report_t_msg;
extern const pb_msgdesc_t beacon_key_report_t_msg;
extern const pb_msgdesc_t simple_sensor_reading_t_msg;
extern const pb_msgdesc_t system_state_packet_t_msg;
extern const pb_msgdesc_t peripheral_packet_t_msg;
extern const pb_msgdesc_t peripheral_info_t_msg;
extern const pb_msgdesc_t ble_packet_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TIME_WINDOW_FIELDS &time_window_t_msg
#define SAMPLING_CONFIG_FIELDS &sampling_config_t_msg
#define GPS_CONFIG_FIELDS &gps_config_t_msg
#define RADIO_OTAA_FIELDS &radio_otaa_t_msg
#define RADIO_ABP_FIELDS &radio_abp_t_msg
#define LO_RA_WAN_CONFIG_FIELDS &lo_ra_wan_config_t_msg
#define LO_RA_CONFIG_FIELDS &lo_ra_config_t_msg
#define LOST_MODE_CONFIG_FIELDS &lost_mode_config_t_msg
#define MORTALITY_CONFIG_FIELDS &mortality_config_t_msg
#define RADIO_CONFIG_PACKET_FIELDS &radio_config_packet_t_msg
#define MICROPHONE_CONFIG_FIELDS &microphone_config_t_msg
#define ACCELEROMETER_CONFIG_FIELDS &accelerometer_config_t_msg
#define MAGNETOMETER_CONFIG_FIELDS &magnetometer_config_t_msg
#define SCHEDULE_CONFIG_FIELDS &schedule_config_t_msg
#define SCHEDULE_CONFIG_PACKET_FIELDS &schedule_config_packet_t_msg
#define CFG_ECHO_PACKET_FIELDS &cfg_echo_packet_t_msg
#define MAG_CAL_REPORT_FIELDS &mag_cal_report_t_msg
#define BEACON_KEY_REPORT_FIELDS &beacon_key_report_t_msg
#define SIMPLE_SENSOR_READING_FIELDS &simple_sensor_reading_t_msg
#define SYSTEM_STATE_PACKET_FIELDS &system_state_packet_t_msg
#define PERIPHERAL_PACKET_FIELDS &peripheral_packet_t_msg
#define PERIPHERAL_INFO_FIELDS &peripheral_info_t_msg
#define BLE_PACKET_FIELDS &ble_packet_t_msg

/* Maximum encoded size of messages (where known) */
/* PeripheralInfo_size depends on runtime parameters */
/* BlePacket_size depends on runtime parameters */
#define ACCELEROMETER_CONFIG_SIZE                6
#define BEACON_KEY_REPORT_SIZE                   21
#define CFG_ECHO_PACKET_SIZE                     351
#define GPS_CONFIG_SIZE                          44
#define LOST_MODE_CONFIG_SIZE                    23
#define LO_RA_CONFIG_SIZE                        31
#define LO_RA_WAN_CONFIG_SIZE                    103
#define MAGNETOMETER_CONFIG_SIZE                 14
#define MAG_CAL_REPORT_SIZE                      36
#define MICROPHONE_CONFIG_SIZE                   30
#define MORTALITY_CONFIG_SIZE                    12
#define PERIPHERAL_PACKET_SIZE                   10
#define RADIO_ABP_SIZE                           78
#define RADIO_CONFIG_PACKET_SIZE                 181
#define RADIO_OTAA_SIZE                          56
#define SAMPLING_CONFIG_SIZE                     8
#define SCHEDULE_CONFIG_PACKET_SIZE              1387
#define SCHEDULE_CONFIG_SIZE                     180
#define SIMPLE_SENSOR_READING_SIZE               51
#define SYSTEM_STATE_PACKET_SIZE                 145
#define TIME_WINDOW_SIZE                         30

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
