// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: common.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// ---- Activity ----
/// Identical enum from both files.
enum Activity: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case still // = 0
  case walk // = 1
  case run // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .still
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .still
    case 1: self = .walk
    case 2: self = .run
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .still: return 0
    case .walk: return 1
    case .run: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Activity] = [
    .still,
    .walk,
    .run,
  ]

}

/// ---- Header ----
/// A unified header. ms_from_start is from ble.proto, request_ack from message.proto.
struct PacketHeader: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var systemUid: UInt32 = 0

  var msFromStart: UInt32 = 0

  var epoch: UInt32 = 0

  var packetIndex: UInt32 = 0

  var requestAck: Bool {
    get {return _requestAck ?? false}
    set {_requestAck = newValue}
  }
  /// Returns true if `requestAck` has been explicitly set.
  var hasRequestAck: Bool {return self._requestAck != nil}
  /// Clears the value of `requestAck`. Subsequent reads from it will return its default value.
  mutating func clearRequestAck() {self._requestAck = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _requestAck: Bool? = nil
}

/// ---- GPS ----
/// Identical definition from both files.
struct GPSData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var latitude: Float = 0

  var longitude: Float = 0

  var altitude: Float = 0

  var speed: Float = 0

  var heading: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// ---- Battery ----
/// Unified on float for voltage and percentage for consistency.
struct BatteryState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var charging: Bool = false

  var voltage: Float = 0

  var percentage: Float {
    get {return _percentage ?? 0}
    set {_percentage = newValue}
  }
  /// Returns true if `percentage` has been explicitly set.
  var hasPercentage: Bool {return self._percentage != nil}
  /// Clears the value of `percentage`. Subsequent reads from it will return its default value.
  mutating func clearPercentage() {self._percentage = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _percentage: Float? = nil
}

/// ---- SD Card ----
/// Unified on uint64 for sizes to prevent overflow.
struct SDCardState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var detected: Bool = false

  /// bytes
  var spaceRemaining: UInt64 = 0

  /// bytes
  var totalSpace: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Activity: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "STILL"),
    1: .same(proto: "WALK"),
    2: .same(proto: "RUN"),
  ]
}

extension PacketHeader: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "PacketHeader"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "system_uid"),
    2: .standard(proto: "ms_from_start"),
    3: .same(proto: "epoch"),
    4: .standard(proto: "packet_index"),
    5: .standard(proto: "request_ack"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.systemUid) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.msFromStart) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.epoch) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.packetIndex) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self._requestAck) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.systemUid != 0 {
      try visitor.visitSingularUInt32Field(value: self.systemUid, fieldNumber: 1)
    }
    if self.msFromStart != 0 {
      try visitor.visitSingularUInt32Field(value: self.msFromStart, fieldNumber: 2)
    }
    if self.epoch != 0 {
      try visitor.visitSingularUInt32Field(value: self.epoch, fieldNumber: 3)
    }
    if self.packetIndex != 0 {
      try visitor.visitSingularUInt32Field(value: self.packetIndex, fieldNumber: 4)
    }
    try { if let v = self._requestAck {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PacketHeader, rhs: PacketHeader) -> Bool {
    if lhs.systemUid != rhs.systemUid {return false}
    if lhs.msFromStart != rhs.msFromStart {return false}
    if lhs.epoch != rhs.epoch {return false}
    if lhs.packetIndex != rhs.packetIndex {return false}
    if lhs._requestAck != rhs._requestAck {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension GPSData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "GPSData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "latitude"),
    2: .same(proto: "longitude"),
    3: .same(proto: "altitude"),
    4: .same(proto: "speed"),
    5: .same(proto: "heading"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.latitude) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.longitude) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.altitude) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.speed) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self.heading) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.latitude.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.latitude, fieldNumber: 1)
    }
    if self.longitude.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.longitude, fieldNumber: 2)
    }
    if self.altitude.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.altitude, fieldNumber: 3)
    }
    if self.speed.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.speed, fieldNumber: 4)
    }
    if self.heading.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.heading, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: GPSData, rhs: GPSData) -> Bool {
    if lhs.latitude != rhs.latitude {return false}
    if lhs.longitude != rhs.longitude {return false}
    if lhs.altitude != rhs.altitude {return false}
    if lhs.speed != rhs.speed {return false}
    if lhs.heading != rhs.heading {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BatteryState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "BatteryState"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "charging"),
    2: .same(proto: "voltage"),
    3: .same(proto: "percentage"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.charging) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.voltage) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self._percentage) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.charging != false {
      try visitor.visitSingularBoolField(value: self.charging, fieldNumber: 1)
    }
    if self.voltage.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.voltage, fieldNumber: 2)
    }
    try { if let v = self._percentage {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BatteryState, rhs: BatteryState) -> Bool {
    if lhs.charging != rhs.charging {return false}
    if lhs.voltage != rhs.voltage {return false}
    if lhs._percentage != rhs._percentage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SDCardState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SDCardState"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "detected"),
    2: .standard(proto: "space_remaining"),
    3: .standard(proto: "total_space"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.detected) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.spaceRemaining) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.totalSpace) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.detected != false {
      try visitor.visitSingularBoolField(value: self.detected, fieldNumber: 1)
    }
    if self.spaceRemaining != 0 {
      try visitor.visitSingularUInt64Field(value: self.spaceRemaining, fieldNumber: 2)
    }
    if self.totalSpace != 0 {
      try visitor.visitSingularUInt64Field(value: self.totalSpace, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SDCardState, rhs: SDCardState) -> Bool {
    if lhs.detected != rhs.detected {return false}
    if lhs.spaceRemaining != rhs.spaceRemaining {return false}
    if lhs.totalSpace != rhs.totalSpace {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
