/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_COMMON_PB_H_INCLUDED
#define PB_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* ---- Activity ----
 Identical enum from both files. */
typedef enum _Activity {
    Activity_STILL = 0,
    Activity_WALK = 1,
    Activity_RUN = 2
} Activity;

/* Struct definitions */
/* ---- Header ----
 A unified header. ms_from_start is from ble.proto, request_ack from message.proto. */
typedef struct _PacketHeader {
    uint32_t system_uid;
    uint32_t ms_from_start;
    uint32_t epoch;
    uint32_t packet_index;
    bool has_request_ack;
    bool request_ack;
    /* Firmware build number = `git rev-parse --count HEAD` of collarID_thread,
 injected at compile time (CMake, next to FIRMWARE_GIT_HASH). Ordered, so
 the server gates capabilities with simple >= checks; absent on legacy
 firmware (server treats missing as "capabilities unknown"). ~3 B on air. */
    bool has_fw_build;
    uint32_t fw_build;
} PacketHeader;

/* ---- GPS ----
 Identical definition from both files. */
typedef struct _GPSData {
    float latitude;
    float longitude;
    float altitude;
    float speed;
    float heading;
} GPSData;

/* ---- Battery ----
 Unified on float for voltage and percentage for consistency. */
typedef struct _BatteryState {
    bool charging;
    float voltage;
    bool has_percentage;
    float percentage;
} BatteryState;

/* ---- SD Card ----
 Unified on uint64 for sizes to prevent overflow. */
typedef struct _SDCardState {
    bool detected;
    uint64_t space_remaining; /* bytes */
    uint64_t total_space; /* bytes */
} SDCardState;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Activity_MIN Activity_STILL
#define _Activity_MAX Activity_RUN
#define _Activity_ARRAYSIZE ((Activity)(Activity_RUN+1))






/* Initializer values for message structs */
#define PacketHeader_init_default                {0, 0, 0, 0, false, 0, false, 0}
#define GPSData_init_default                     {0, 0, 0, 0, 0}
#define BatteryState_init_default                {0, 0, false, 0}
#define SDCardState_init_default                 {0, 0, 0}
#define PacketHeader_init_zero                   {0, 0, 0, 0, false, 0, false, 0}
#define GPSData_init_zero                        {0, 0, 0, 0, 0}
#define BatteryState_init_zero                   {0, 0, false, 0}
#define SDCardState_init_zero                    {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PacketHeader_system_uid_tag              1
#define PacketHeader_ms_from_start_tag           2
#define PacketHeader_epoch_tag                   3
#define PacketHeader_packet_index_tag            4
#define PacketHeader_request_ack_tag             5
#define PacketHeader_fw_build_tag                6
#define GPSData_latitude_tag                     1
#define GPSData_longitude_tag                    2
#define GPSData_altitude_tag                     3
#define GPSData_speed_tag                        4
#define GPSData_heading_tag                      5
#define BatteryState_charging_tag                1
#define BatteryState_voltage_tag                 2
#define BatteryState_percentage_tag              3
#define SDCardState_detected_tag                 1
#define SDCardState_space_remaining_tag          2
#define SDCardState_total_space_tag              3

/* Struct field encoding specification for nanopb */
#define PacketHeader_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   system_uid,        1) \
X(a, STATIC,   SINGULAR, UINT32,   ms_from_start,     2) \
X(a, STATIC,   SINGULAR, UINT32,   epoch,             3) \
X(a, STATIC,   SINGULAR, UINT32,   packet_index,      4) \
X(a, STATIC,   OPTIONAL, BOOL,     request_ack,       5) \
X(a, STATIC,   OPTIONAL, UINT32,   fw_build,          6)
#define PacketHeader_CALLBACK NULL
#define PacketHeader_DEFAULT NULL

#define GPSData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    latitude,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    longitude,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    altitude,          3) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             4) \
X(a, STATIC,   SINGULAR, FLOAT,    heading,           5)
#define GPSData_CALLBACK NULL
#define GPSData_DEFAULT NULL

#define BatteryState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     charging,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage,           2) \
X(a, STATIC,   OPTIONAL, FLOAT,    percentage,        3)
#define BatteryState_CALLBACK NULL
#define BatteryState_DEFAULT NULL

#define SDCardState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     detected,          1) \
X(a, STATIC,   SINGULAR, UINT64,   space_remaining,   2) \
X(a, STATIC,   SINGULAR, UINT64,   total_space,       3)
#define SDCardState_CALLBACK NULL
#define SDCardState_DEFAULT NULL

extern const pb_msgdesc_t PacketHeader_msg;
extern const pb_msgdesc_t GPSData_msg;
extern const pb_msgdesc_t BatteryState_msg;
extern const pb_msgdesc_t SDCardState_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PacketHeader_fields &PacketHeader_msg
#define GPSData_fields &GPSData_msg
#define BatteryState_fields &BatteryState_msg
#define SDCardState_fields &SDCardState_msg

/* Maximum encoded size of messages (where known) */
#define BatteryState_size                        12
#define GPSData_size                             25
#define PacketHeader_size                        32
#define SDCardState_size                         24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
