/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_COMMON_PB_H_INCLUDED
#define PB_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* ---- Activity ----
 Identical enum from both files. */
typedef enum activity {
    ACTIVITY_STILL = 0,
    ACTIVITY_WALK = 1,
    ACTIVITY_RUN = 2
} activity_t;

/* Struct definitions */
/* ---- Header ----
 A unified header. ms_from_start is from ble.proto, request_ack from message.proto. */
typedef struct packet_header {
    uint32_t system_uid;
    uint32_t ms_from_start;
    uint32_t epoch;
    uint32_t packet_index;
    bool has_request_ack;
    bool request_ack;
    /* Firmware build number = `git rev-parse --count HEAD` of collarID_thread,
 injected at compile time (CMake, next to FIRMWARE_GIT_HASH). Ordered, so
 the server gates capabilities with simple >= checks; absent on legacy
 firmware (server treats missing as "capabilities unknown"). ~3 B on air. */
    bool has_fw_build;
    uint32_t fw_build;
} packet_header_t;

/* ---- GPS ----
 Identical definition from both files. */
typedef struct gps_data {
    float latitude;
    float longitude;
    float altitude;
    float speed;
    float heading;
} gps_data_t;

/* ---- Battery ----
 Unified on float for voltage and percentage for consistency. */
typedef struct battery_state {
    bool charging;
    float voltage;
    bool has_percentage;
    float percentage;
} battery_state_t;

/* ---- SD Card ----
 Unified on uint64 for sizes to prevent overflow. */
typedef struct sd_card_state {
    bool detected;
    uint64_t space_remaining; /* bytes */
    uint64_t total_space; /* bytes */
} sd_card_state_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ACTIVITY_MIN ACTIVITY_STILL
#define _ACTIVITY_MAX ACTIVITY_RUN
#define _ACTIVITY_ARRAYSIZE ((activity_t)(ACTIVITY_RUN+1))






/* Initializer values for message structs */
#define PACKET_HEADER_INIT_DEFAULT               {0, 0, 0, 0, false, 0, false, 0}
#define GPS_DATA_INIT_DEFAULT                    {0, 0, 0, 0, 0}
#define BATTERY_STATE_INIT_DEFAULT               {0, 0, false, 0}
#define SD_CARD_STATE_INIT_DEFAULT               {0, 0, 0}
#define PACKET_HEADER_INIT_ZERO                  {0, 0, 0, 0, false, 0, false, 0}
#define GPS_DATA_INIT_ZERO                       {0, 0, 0, 0, 0}
#define BATTERY_STATE_INIT_ZERO                  {0, 0, false, 0}
#define SD_CARD_STATE_INIT_ZERO                  {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PACKET_HEADER_SYSTEM_UID_TAG             1
#define PACKET_HEADER_MS_FROM_START_TAG          2
#define PACKET_HEADER_EPOCH_TAG                  3
#define PACKET_HEADER_PACKET_INDEX_TAG           4
#define PACKET_HEADER_REQUEST_ACK_TAG            5
#define PACKET_HEADER_FW_BUILD_TAG               6
#define GPS_DATA_LATITUDE_TAG                    1
#define GPS_DATA_LONGITUDE_TAG                   2
#define GPS_DATA_ALTITUDE_TAG                    3
#define GPS_DATA_SPEED_TAG                       4
#define GPS_DATA_HEADING_TAG                     5
#define BATTERY_STATE_CHARGING_TAG               1
#define BATTERY_STATE_VOLTAGE_TAG                2
#define BATTERY_STATE_PERCENTAGE_TAG             3
#define SD_CARD_STATE_DETECTED_TAG               1
#define SD_CARD_STATE_SPACE_REMAINING_TAG        2
#define SD_CARD_STATE_TOTAL_SPACE_TAG            3

/* Struct field encoding specification for nanopb */
#define PACKET_HEADER_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   system_uid,        1) \
X(a, STATIC,   SINGULAR, UINT32,   ms_from_start,     2) \
X(a, STATIC,   SINGULAR, UINT32,   epoch,             3) \
X(a, STATIC,   SINGULAR, UINT32,   packet_index,      4) \
X(a, STATIC,   OPTIONAL, BOOL,     request_ack,       5) \
X(a, STATIC,   OPTIONAL, UINT32,   fw_build,          6)
#define PACKET_HEADER_CALLBACK NULL
#define PACKET_HEADER_DEFAULT NULL

#define GPS_DATA_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    latitude,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    longitude,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    altitude,          3) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             4) \
X(a, STATIC,   SINGULAR, FLOAT,    heading,           5)
#define GPS_DATA_CALLBACK NULL
#define GPS_DATA_DEFAULT NULL

#define BATTERY_STATE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     charging,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage,           2) \
X(a, STATIC,   OPTIONAL, FLOAT,    percentage,        3)
#define BATTERY_STATE_CALLBACK NULL
#define BATTERY_STATE_DEFAULT NULL

#define SD_CARD_STATE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     detected,          1) \
X(a, STATIC,   SINGULAR, UINT64,   space_remaining,   2) \
X(a, STATIC,   SINGULAR, UINT64,   total_space,       3)
#define SD_CARD_STATE_CALLBACK NULL
#define SD_CARD_STATE_DEFAULT NULL

extern const pb_msgdesc_t packet_header_t_msg;
extern const pb_msgdesc_t gps_data_t_msg;
extern const pb_msgdesc_t battery_state_t_msg;
extern const pb_msgdesc_t sd_card_state_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PACKET_HEADER_FIELDS &packet_header_t_msg
#define GPS_DATA_FIELDS &gps_data_t_msg
#define BATTERY_STATE_FIELDS &battery_state_t_msg
#define SD_CARD_STATE_FIELDS &sd_card_state_t_msg

/* Maximum encoded size of messages (where known) */
#define BATTERY_STATE_SIZE                       12
#define GPS_DATA_SIZE                            25
#define PACKET_HEADER_SIZE                       32
#define SD_CARD_STATE_SIZE                       24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
