/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "common.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PACKET_HEADER, packet_header_t, AUTO)


PB_BIND(GPS_DATA, gps_data_t, AUTO)


PB_BIND(BATTERY_STATE, battery_state_t, AUTO)


PB_BIND(SD_CARD_STATE, sd_card_state_t, AUTO)




