/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DOWNLINK_PB_H_INCLUDED
#define PB_DOWNLINK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* ---- Commands ---- */
typedef enum _CommandType {
    CommandType_CMD_NONE = 0,
    CommandType_CMD_RESET = 1, /* Reboot the device */
    CommandType_CMD_DROP_OFF = 2, /* Detach the collar (irreversible) */
    CommandType_CMD_HIGH_FIX_ON = 3, /* Enable high-fix GPS mode */
    CommandType_CMD_HIGH_FIX_OFF = 4, /* Disable high-fix GPS mode */
    CommandType_CMD_SYNC_TIME = 5, /* Sync RTC to server epoch */
    CommandType_CMD_BUZZ = 6, /* Audible locate ping (future) */
    CommandType_CMD_ENGAGE = 7, /* Engage the system (start scheduling) */
    CommandType_CMD_DISENGAGE = 8, /* Disengage (stop all sensors, idle) */
    CommandType_CMD_CONFIG_BEGIN = 9, /* Start config transaction (snapshot live → staging) */
    CommandType_CMD_CONFIG_COMMIT = 10, /* Verify + apply staging → live, persist, notify */
    CommandType_CMD_CONFIG_ABORT = 11 /* Discard staging buffer */
} CommandType;

/* Struct definitions */
/* ---- Geofence ---- */
typedef struct _GeoPoint {
    int32_t latitude_e7;
    int32_t longitude_e7;
} GeoPoint;

typedef struct _GeofenceData {
    uint32_t fence_id;
    pb_size_t vertices_count;
    GeoPoint vertices[8]; /* max 8 */
    bool active;
} GeofenceData;

/* ---- High-fix parameters ---- */
typedef struct _HighFixParams {
    uint32_t duration_hours; /* default 24 */
    uint32_t sample_interval_sec; /* default 300 */
} HighFixParams;

/* Time window for a schedule slot (~4 bytes) */
typedef struct _ConfigTimeWindow {
    bool has_start_hour;
    uint32_t start_hour; /* 0-23 */
    bool has_end_hour;
    uint32_t end_hour; /* 0-23 */
} ConfigTimeWindow;

/* Accelerometer (~4 bytes) */
typedef struct _ConfigAccelerometer {
    bool has_enabled;
    bool enabled;
    bool has_sample_rate;
    uint32_t sample_rate; /* 0=25Hz, 1=50Hz */
    bool has_sensitivity;
    uint32_t sensitivity; /* 0=2G, 1=4G, 2=8G */
} ConfigAccelerometer;

/* Microphone (~5 bytes) */
typedef struct _ConfigMicrophone {
    bool has_enabled;
    bool enabled;
    bool has_continuous_mode;
    bool continuous_mode;
    bool has_sample_length_min;
    uint32_t sample_length_min;
    bool has_sample_window_min;
    uint32_t sample_window_min;
} ConfigMicrophone;

/* GPS (~4 bytes) */
typedef struct _ConfigGPS {
    bool has_enabled;
    bool enabled;
    bool has_sample_interval_min;
    uint32_t sample_interval_min;
    bool has_accuracy;
    uint32_t accuracy; /* 1-10 */
} ConfigGPS;

/* Magnetometer (~3 bytes) */
typedef struct _ConfigMagnetometer {
    bool has_enabled;
    bool enabled;
    bool has_sample_interval_s;
    uint32_t sample_interval_s;
} ConfigMagnetometer;

/* Generic sensor: light, environmental, particulate (~3 bytes) */
typedef struct _ConfigSampling {
    bool has_enabled;
    bool enabled;
    bool has_sample_interval_min;
    uint32_t sample_interval_min;
} ConfigSampling;

/* Per-schedule radio enable/interval (~6 bytes) */
typedef struct _ConfigRadioTiming {
    bool has_lorawan_enabled;
    bool lorawan_enabled;
    bool has_lorawan_send_interval_min;
    uint32_t lorawan_send_interval_min;
    bool has_lora_enabled;
    bool lora_enabled;
    bool has_lora_send_interval_min;
    uint32_t lora_send_interval_min;
    bool has_tx_power_dbm;
    int32_t tx_power_dbm;
} ConfigRadioTiming;

/* Global system flags — not per-schedule (~4 bytes) */
typedef struct _ConfigSystem {
    bool has_verbose_logging;
    bool verbose_logging;
    bool has_enable_reset_on_error;
    bool enable_reset_on_error;
    bool has_special_mode;
    uint32_t special_mode;
} ConfigSystem;

/* ---- Config fragment wrapper ----
 Pairs a schedule slot index with exactly one sensor/system config.
 fragment_index and fragment_total enable integrity checking on commit. */
typedef struct _ConfigFragment {
    uint32_t schedule_index; /* target schedule slot (0-4) */
    uint32_t fragment_index; /* 0-based index of this fragment in the transaction */
    uint32_t fragment_total; /* total number of fragments the server will send */
    pb_size_t which_setting;
    union {
        ConfigTimeWindow cfg_time_window;
        ConfigAccelerometer cfg_accelerometer;
        ConfigMicrophone cfg_microphone;
        ConfigGPS cfg_gps;
        ConfigMagnetometer cfg_magnetometer;
        ConfigSampling cfg_light;
        ConfigSampling cfg_environmental;
        ConfigSampling cfg_particulate;
        ConfigRadioTiming cfg_radio_timing;
        ConfigSystem cfg_system; /* global, schedule_index ignored */
    } setting;
} ConfigFragment;

/* ---- Main downlink envelope ---- */
typedef struct _DownlinkPacket {
    uint32_t epoch; /* server UTC epoch for RTC sync */
    CommandType command; /* command to execute */
    bool has_high_fix_params;
    HighFixParams high_fix_params;
    bool has_geofence;
    GeofenceData geofence;
    /* Config fragment: one per downlink.
 Only processed when a config transaction is open (after CMD_CONFIG_BEGIN).
 On CMD_CONFIG_COMMIT, device checks that all fragment_total fragments
 were received (via a bitmask indexed by fragment_index). If any are
 missing, commit is rejected, staging is discarded, and the device
 uplinks a NACK with the missing fragment bitmask so the server can retry. */
    bool has_config;
    ConfigFragment config;
} DownlinkPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _CommandType_MIN CommandType_CMD_NONE
#define _CommandType_MAX CommandType_CMD_CONFIG_ABORT
#define _CommandType_ARRAYSIZE ((CommandType)(CommandType_CMD_CONFIG_ABORT+1))













#define DownlinkPacket_command_ENUMTYPE CommandType


/* Initializer values for message structs */
#define GeoPoint_init_default                    {0, 0}
#define GeofenceData_init_default                {0, 0, {GeoPoint_init_default, GeoPoint_init_default, GeoPoint_init_default, GeoPoint_init_default, GeoPoint_init_default, GeoPoint_init_default, GeoPoint_init_default, GeoPoint_init_default}, 0}
#define HighFixParams_init_default               {0, 0}
#define ConfigTimeWindow_init_default            {false, 0, false, 0}
#define ConfigAccelerometer_init_default         {false, 0, false, 0, false, 0}
#define ConfigMicrophone_init_default            {false, 0, false, 0, false, 0, false, 0}
#define ConfigGPS_init_default                   {false, 0, false, 0, false, 0}
#define ConfigMagnetometer_init_default          {false, 0, false, 0}
#define ConfigSampling_init_default              {false, 0, false, 0}
#define ConfigRadioTiming_init_default           {false, 0, false, 0, false, 0, false, 0, false, 0}
#define ConfigSystem_init_default                {false, 0, false, 0, false, 0}
#define ConfigFragment_init_default              {0, 0, 0, 0, {ConfigTimeWindow_init_default}}
#define DownlinkPacket_init_default              {0, _CommandType_MIN, false, HighFixParams_init_default, false, GeofenceData_init_default, false, ConfigFragment_init_default}
#define GeoPoint_init_zero                       {0, 0}
#define GeofenceData_init_zero                   {0, 0, {GeoPoint_init_zero, GeoPoint_init_zero, GeoPoint_init_zero, GeoPoint_init_zero, GeoPoint_init_zero, GeoPoint_init_zero, GeoPoint_init_zero, GeoPoint_init_zero}, 0}
#define HighFixParams_init_zero                  {0, 0}
#define ConfigTimeWindow_init_zero               {false, 0, false, 0}
#define ConfigAccelerometer_init_zero            {false, 0, false, 0, false, 0}
#define ConfigMicrophone_init_zero               {false, 0, false, 0, false, 0, false, 0}
#define ConfigGPS_init_zero                      {false, 0, false, 0, false, 0}
#define ConfigMagnetometer_init_zero             {false, 0, false, 0}
#define ConfigSampling_init_zero                 {false, 0, false, 0}
#define ConfigRadioTiming_init_zero              {false, 0, false, 0, false, 0, false, 0, false, 0}
#define ConfigSystem_init_zero                   {false, 0, false, 0, false, 0}
#define ConfigFragment_init_zero                 {0, 0, 0, 0, {ConfigTimeWindow_init_zero}}
#define DownlinkPacket_init_zero                 {0, _CommandType_MIN, false, HighFixParams_init_zero, false, GeofenceData_init_zero, false, ConfigFragment_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define GeoPoint_latitude_e7_tag                 1
#define GeoPoint_longitude_e7_tag                2
#define GeofenceData_fence_id_tag                1
#define GeofenceData_vertices_tag                2
#define GeofenceData_active_tag                  3
#define HighFixParams_duration_hours_tag         1
#define HighFixParams_sample_interval_sec_tag    2
#define ConfigTimeWindow_start_hour_tag          1
#define ConfigTimeWindow_end_hour_tag            2
#define ConfigAccelerometer_enabled_tag          1
#define ConfigAccelerometer_sample_rate_tag      2
#define ConfigAccelerometer_sensitivity_tag      3
#define ConfigMicrophone_enabled_tag             1
#define ConfigMicrophone_continuous_mode_tag     2
#define ConfigMicrophone_sample_length_min_tag   3
#define ConfigMicrophone_sample_window_min_tag   4
#define ConfigGPS_enabled_tag                    1
#define ConfigGPS_sample_interval_min_tag        2
#define ConfigGPS_accuracy_tag                   3
#define ConfigMagnetometer_enabled_tag           1
#define ConfigMagnetometer_sample_interval_s_tag 2
#define ConfigSampling_enabled_tag               1
#define ConfigSampling_sample_interval_min_tag   2
#define ConfigRadioTiming_lorawan_enabled_tag    1
#define ConfigRadioTiming_lorawan_send_interval_min_tag 2
#define ConfigRadioTiming_lora_enabled_tag       3
#define ConfigRadioTiming_lora_send_interval_min_tag 4
#define ConfigRadioTiming_tx_power_dbm_tag       5
#define ConfigSystem_verbose_logging_tag         1
#define ConfigSystem_enable_reset_on_error_tag   2
#define ConfigSystem_special_mode_tag            3
#define ConfigFragment_schedule_index_tag        1
#define ConfigFragment_fragment_index_tag        2
#define ConfigFragment_fragment_total_tag        3
#define ConfigFragment_cfg_time_window_tag       4
#define ConfigFragment_cfg_accelerometer_tag     5
#define ConfigFragment_cfg_microphone_tag        6
#define ConfigFragment_cfg_gps_tag               7
#define ConfigFragment_cfg_magnetometer_tag      8
#define ConfigFragment_cfg_light_tag             9
#define ConfigFragment_cfg_environmental_tag     10
#define ConfigFragment_cfg_particulate_tag       11
#define ConfigFragment_cfg_radio_timing_tag      12
#define ConfigFragment_cfg_system_tag            13
#define DownlinkPacket_epoch_tag                 1
#define DownlinkPacket_command_tag               2
#define DownlinkPacket_high_fix_params_tag       3
#define DownlinkPacket_geofence_tag              4
#define DownlinkPacket_config_tag                5

/* Struct field encoding specification for nanopb */
#define GeoPoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    latitude_e7,       1) \
X(a, STATIC,   SINGULAR, INT32,    longitude_e7,      2)
#define GeoPoint_CALLBACK NULL
#define GeoPoint_DEFAULT NULL

#define GeofenceData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   fence_id,          1) \
X(a, STATIC,   REPEATED, MESSAGE,  vertices,          2) \
X(a, STATIC,   SINGULAR, BOOL,     active,            3)
#define GeofenceData_CALLBACK NULL
#define GeofenceData_DEFAULT NULL
#define GeofenceData_vertices_MSGTYPE GeoPoint

#define HighFixParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   duration_hours,    1) \
X(a, STATIC,   SINGULAR, UINT32,   sample_interval_sec,   2)
#define HighFixParams_CALLBACK NULL
#define HighFixParams_DEFAULT NULL

#define ConfigTimeWindow_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   start_hour,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   end_hour,          2)
#define ConfigTimeWindow_CALLBACK NULL
#define ConfigTimeWindow_DEFAULT NULL

#define ConfigAccelerometer_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   sample_rate,       2) \
X(a, STATIC,   OPTIONAL, UINT32,   sensitivity,       3)
#define ConfigAccelerometer_CALLBACK NULL
#define ConfigAccelerometer_DEFAULT NULL

#define ConfigMicrophone_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           1) \
X(a, STATIC,   OPTIONAL, BOOL,     continuous_mode,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   sample_length_min,   3) \
X(a, STATIC,   OPTIONAL, UINT32,   sample_window_min,   4)
#define ConfigMicrophone_CALLBACK NULL
#define ConfigMicrophone_DEFAULT NULL

#define ConfigGPS_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   sample_interval_min,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   accuracy,          3)
#define ConfigGPS_CALLBACK NULL
#define ConfigGPS_DEFAULT NULL

#define ConfigMagnetometer_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   sample_interval_s,   2)
#define ConfigMagnetometer_CALLBACK NULL
#define ConfigMagnetometer_DEFAULT NULL

#define ConfigSampling_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   sample_interval_min,   2)
#define ConfigSampling_CALLBACK NULL
#define ConfigSampling_DEFAULT NULL

#define ConfigRadioTiming_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     lorawan_enabled,   1) \
X(a, STATIC,   OPTIONAL, UINT32,   lorawan_send_interval_min,   2) \
X(a, STATIC,   OPTIONAL, BOOL,     lora_enabled,      3) \
X(a, STATIC,   OPTIONAL, UINT32,   lora_send_interval_min,   4) \
X(a, STATIC,   OPTIONAL, INT32,    tx_power_dbm,      5)
#define ConfigRadioTiming_CALLBACK NULL
#define ConfigRadioTiming_DEFAULT NULL

#define ConfigSystem_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     verbose_logging,   1) \
X(a, STATIC,   OPTIONAL, BOOL,     enable_reset_on_error,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   special_mode,      3)
#define ConfigSystem_CALLBACK NULL
#define ConfigSystem_DEFAULT NULL

#define ConfigFragment_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   schedule_index,    1) \
X(a, STATIC,   SINGULAR, UINT32,   fragment_index,    2) \
X(a, STATIC,   SINGULAR, UINT32,   fragment_total,    3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_time_window,setting.cfg_time_window),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_accelerometer,setting.cfg_accelerometer),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_microphone,setting.cfg_microphone),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_gps,setting.cfg_gps),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_magnetometer,setting.cfg_magnetometer),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_light,setting.cfg_light),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_environmental,setting.cfg_environmental),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_particulate,setting.cfg_particulate),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_radio_timing,setting.cfg_radio_timing),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_system,setting.cfg_system),  13)
#define ConfigFragment_CALLBACK NULL
#define ConfigFragment_DEFAULT NULL
#define ConfigFragment_setting_cfg_time_window_MSGTYPE ConfigTimeWindow
#define ConfigFragment_setting_cfg_accelerometer_MSGTYPE ConfigAccelerometer
#define ConfigFragment_setting_cfg_microphone_MSGTYPE ConfigMicrophone
#define ConfigFragment_setting_cfg_gps_MSGTYPE ConfigGPS
#define ConfigFragment_setting_cfg_magnetometer_MSGTYPE ConfigMagnetometer
#define ConfigFragment_setting_cfg_light_MSGTYPE ConfigSampling
#define ConfigFragment_setting_cfg_environmental_MSGTYPE ConfigSampling
#define ConfigFragment_setting_cfg_particulate_MSGTYPE ConfigSampling
#define ConfigFragment_setting_cfg_radio_timing_MSGTYPE ConfigRadioTiming
#define ConfigFragment_setting_cfg_system_MSGTYPE ConfigSystem

#define DownlinkPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   epoch,             1) \
X(a, STATIC,   SINGULAR, UENUM,    command,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  high_fix_params,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  geofence,          4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            5)
#define DownlinkPacket_CALLBACK NULL
#define DownlinkPacket_DEFAULT NULL
#define DownlinkPacket_high_fix_params_MSGTYPE HighFixParams
#define DownlinkPacket_geofence_MSGTYPE GeofenceData
#define DownlinkPacket_config_MSGTYPE ConfigFragment

extern const pb_msgdesc_t GeoPoint_msg;
extern const pb_msgdesc_t GeofenceData_msg;
extern const pb_msgdesc_t HighFixParams_msg;
extern const pb_msgdesc_t ConfigTimeWindow_msg;
extern const pb_msgdesc_t ConfigAccelerometer_msg;
extern const pb_msgdesc_t ConfigMicrophone_msg;
extern const pb_msgdesc_t ConfigGPS_msg;
extern const pb_msgdesc_t ConfigMagnetometer_msg;
extern const pb_msgdesc_t ConfigSampling_msg;
extern const pb_msgdesc_t ConfigRadioTiming_msg;
extern const pb_msgdesc_t ConfigSystem_msg;
extern const pb_msgdesc_t ConfigFragment_msg;
extern const pb_msgdesc_t DownlinkPacket_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GeoPoint_fields &GeoPoint_msg
#define GeofenceData_fields &GeofenceData_msg
#define HighFixParams_fields &HighFixParams_msg
#define ConfigTimeWindow_fields &ConfigTimeWindow_msg
#define ConfigAccelerometer_fields &ConfigAccelerometer_msg
#define ConfigMicrophone_fields &ConfigMicrophone_msg
#define ConfigGPS_fields &ConfigGPS_msg
#define ConfigMagnetometer_fields &ConfigMagnetometer_msg
#define ConfigSampling_fields &ConfigSampling_msg
#define ConfigRadioTiming_fields &ConfigRadioTiming_msg
#define ConfigSystem_fields &ConfigSystem_msg
#define ConfigFragment_fields &ConfigFragment_msg
#define DownlinkPacket_fields &DownlinkPacket_msg

/* Maximum encoded size of messages (where known) */
#define ConfigAccelerometer_size                 14
#define ConfigFragment_size                      47
#define ConfigGPS_size                           14
#define ConfigMagnetometer_size                  8
#define ConfigMicrophone_size                    16
#define ConfigRadioTiming_size                   27
#define ConfigSampling_size                      8
#define ConfigSystem_size                        10
#define ConfigTimeWindow_size                    12
#define DOWNLINK_PB_H_MAX_SIZE                   DownlinkPacket_size
#define DownlinkPacket_size                      274
#define GeoPoint_size                            22
#define GeofenceData_size                        200
#define HighFixParams_size                       12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
