# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: downlink.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'downlink.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ownlink.proto\x1a\x0cnanopb.proto\"5\n\x08GeoPoint\x12\x13\n\x0blatitude_e7\x18\x01 \x01(\x05\x12\x14\n\x0clongitude_e7\x18\x02 \x01(\x05\"M\n\x0cGeofenceData\x12\x10\n\x08\x66\x65nce_id\x18\x01 \x01(\r\x12\x1b\n\x08vertices\x18\x02 \x03(\x0b\x32\t.GeoPoint\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\"D\n\rHighFixParams\x12\x16\n\x0e\x64uration_hours\x18\x01 \x01(\r\x12\x1b\n\x13sample_interval_sec\x18\x02 \x01(\r\"\xb3\x01\n\x0e\x44ownlinkPacket\x12\r\n\x05\x65poch\x18\x01 \x01(\r\x12\x1d\n\x07\x63ommand\x18\x02 \x01(\x0e\x32\x0c.CommandType\x12,\n\x0fhigh_fix_params\x18\x03 \x01(\x0b\x32\x0e.HighFixParamsH\x00\x88\x01\x01\x12$\n\x08geofence\x18\x04 \x01(\x0b\x32\r.GeofenceDataH\x01\x88\x01\x01\x42\x12\n\x10_high_fix_paramsB\x0b\n\t_geofence*\x88\x01\n\x0b\x43ommandType\x12\x0c\n\x08\x43MD_NONE\x10\x00\x12\r\n\tCMD_RESET\x10\x01\x12\x10\n\x0c\x43MD_DROP_OFF\x10\x02\x12\x13\n\x0f\x43MD_HIGH_FIX_ON\x10\x03\x12\x14\n\x10\x43MD_HIGH_FIX_OFF\x10\x04\x12\x11\n\rCMD_SYNC_TIME\x10\x05\x12\x0c\n\x08\x43MD_BUZZ\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'downlink_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDTYPE']._serialized_start=419
  _globals['_COMMANDTYPE']._serialized_end=555
  _globals['_GEOPOINT']._serialized_start=32
  _globals['_GEOPOINT']._serialized_end=85
  _globals['_GEOFENCEDATA']._serialized_start=87
  _globals['_GEOFENCEDATA']._serialized_end=164
  _globals['_HIGHFIXPARAMS']._serialized_start=166
  _globals['_HIGHFIXPARAMS']._serialized_end=234
  _globals['_DOWNLINKPACKET']._serialized_start=237
  _globals['_DOWNLINKPACKET']._serialized_end=416
# @@protoc_insertion_point(module_scope)
