/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "downlink.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GEO_POINT, geo_point_t, AUTO)


PB_BIND(GEOFENCE_DATA, geofence_data_t, AUTO)


PB_BIND(HIGH_FIX_PARAMS, high_fix_params_t, AUTO)


PB_BIND(CONFIG_TIME_WINDOW, config_time_window_t, AUTO)


PB_BIND(CONFIG_ACCELEROMETER, config_accelerometer_t, AUTO)


PB_BIND(CONFIG_MICROPHONE, config_microphone_t, AUTO)


PB_BIND(CONFIG_GPS, config_gps_t, AUTO)


PB_BIND(CONFIG_MAGNETOMETER, config_magnetometer_t, AUTO)


PB_BIND(CONFIG_SAMPLING, config_sampling_t, AUTO)


PB_BIND(CONFIG_RADIO_TIMING, config_radio_timing_t, AUTO)


PB_BIND(CONFIG_SYSTEM, config_system_t, AUTO)


PB_BIND(CONFIG_FRAGMENT, config_fragment_t, AUTO)


PB_BIND(DOWNLINK_PACKET, downlink_packet_t, AUTO)




