/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_DOWNLINK_PB_H_INCLUDED
#define PB_DOWNLINK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* ---- Commands ---- */
typedef enum command_type {
    COMMAND_TYPE_CMD_NONE = 0,
    COMMAND_TYPE_CMD_RESET = 1, /* Reboot the device */
    COMMAND_TYPE_CMD_DROP_OFF = 2, /* Detach the collar (irreversible) */
    COMMAND_TYPE_CMD_HIGH_FIX_ON = 3, /* Enable high-fix GPS mode */
    COMMAND_TYPE_CMD_HIGH_FIX_OFF = 4, /* Disable high-fix GPS mode */
    COMMAND_TYPE_CMD_SYNC_TIME = 5, /* Sync RTC to server epoch */
    COMMAND_TYPE_CMD_BUZZ = 6, /* Audible locate ping (future) */
    COMMAND_TYPE_CMD_ENGAGE = 7, /* Engage the system (start scheduling) */
    COMMAND_TYPE_CMD_DISENGAGE = 8, /* Disengage (stop all sensors, idle) */
    COMMAND_TYPE_CMD_CONFIG_BEGIN = 9, /* Start config transaction (snapshot live → staging) */
    COMMAND_TYPE_CMD_CONFIG_COMMIT = 10, /* Verify + apply staging → live, persist, notify */
    COMMAND_TYPE_CMD_CONFIG_ABORT = 11, /* Discard staging buffer */
    /* 7.1 remote add-on control: routed into the collar's durable command
 queue and forwarded to the detach add-on at its next rendezvous. */
    COMMAND_TYPE_CMD_ADDON_ARM = 13, /* Arm detach at addon_arm_epoch (UTC s) */
    COMMAND_TYPE_CMD_ADDON_ABORT = 14, /* Disarm the detach add-on */
    /* Missed-packet recovery (DESIGN_lorawan_reliability.md): server detected
 a gap in packet_header.packet_index and asks the device to replay the
 stored uplinks verbatim (pure retransmit, fPort 12). */
    COMMAND_TYPE_CMD_RESEND = 15, /* Replay uplinks named by resend_from/resend_mask */
    /* Remote schedule push (DESIGN_remote_schedule_push.md): ask the device to
 uplink its full ConfigPacket + sched_crc so the server can (re)learn the
 running schedule — the SD-card-edit recovery path, and the freshness
 prerequisite for building delta fragments. */
    COMMAND_TYPE_CMD_CONFIG_REPORT = 16 /* Uplink current schedule config */
} command_type_t;

/* Struct definitions */
/* ---- Geofence ---- */
typedef struct geo_point {
    int32_t latitude_e7;
    int32_t longitude_e7;
} geo_point_t;

typedef struct geofence_data {
    uint32_t fence_id;
    pb_size_t vertices_count;
    geo_point_t vertices[8]; /* max 8 */
    bool active;
} geofence_data_t;

/* ---- High-fix parameters ---- */
typedef struct high_fix_params {
    uint32_t duration_hours; /* default 24 */
    uint32_t sample_interval_sec; /* default 300 */
} high_fix_params_t;

/* Time window for a schedule slot (~4 bytes) */
typedef struct config_time_window {
    bool has_start_hour;
    uint32_t start_hour; /* 0-23 */
    bool has_end_hour;
    uint32_t end_hour; /* 0-23 */
} config_time_window_t;

/* Accelerometer (~4 bytes) */
typedef struct config_accelerometer {
    bool has_enabled;
    bool enabled;
    bool has_sample_rate;
    uint32_t sample_rate; /* 0=25Hz, 1=50Hz */
    bool has_sensitivity;
    uint32_t sensitivity; /* 0=2G, 1=4G, 2=8G */
} config_accelerometer_t;

/* Microphone (~5 bytes) */
typedef struct config_microphone {
    bool has_enabled;
    bool enabled;
    bool has_continuous_mode;
    bool continuous_mode;
    bool has_sample_length_min;
    uint32_t sample_length_min;
    bool has_sample_window_min;
    uint32_t sample_window_min;
} config_microphone_t;

/* GPS (~4 bytes) */
typedef struct config_gps {
    bool has_enabled;
    bool enabled;
    bool has_sample_interval_min;
    uint32_t sample_interval_min;
    bool has_accuracy;
    uint32_t accuracy; /* 1-10 */
} config_gps_t;

/* Magnetometer (~3 bytes) */
typedef struct config_magnetometer {
    bool has_enabled;
    bool enabled;
    bool has_sample_interval_s;
    uint32_t sample_interval_s;
} config_magnetometer_t;

/* Generic sensor: light, environmental, particulate (~3 bytes) */
typedef struct config_sampling {
    bool has_enabled;
    bool enabled;
    bool has_sample_interval_min;
    uint32_t sample_interval_min;
} config_sampling_t;

/* Per-schedule radio enable/interval (~6 bytes) */
typedef struct config_radio_timing {
    bool has_lorawan_enabled;
    bool lorawan_enabled;
    bool has_lorawan_send_interval_min;
    uint32_t lorawan_send_interval_min;
    bool has_lora_enabled;
    bool lora_enabled;
    bool has_lora_send_interval_min;
    uint32_t lora_send_interval_min;
    bool has_tx_power_dbm;
    int32_t tx_power_dbm;
} config_radio_timing_t;

/* Mortality detection — collar-wide, lives in the radio config on the
 device (~6 bytes). Remote-safe by construction: enabling or disabling it
 can never silence the collar (the beacon is an EXTRA transmission on top
 of the scheduled radio cadence), so no reachability rail applies. Zero
 values mean "use firmware defaults" (48 h trigger, 240 min beacon),
 matching the CONFIG.CSV parser's semantics. */
typedef struct config_mortality {
    bool has_enabled;
    bool enabled;
    bool has_trigger_duration_hours;
    uint32_t trigger_duration_hours;
    bool has_transmit_interval_min;
    uint32_t transmit_interval_min;
} config_mortality_t;

/* Global system flags — not per-schedule (~4 bytes) */
typedef struct config_system {
    bool has_verbose_logging;
    bool verbose_logging;
    bool has_enable_reset_on_error;
    bool enable_reset_on_error;
    bool has_special_mode;
    uint32_t special_mode;
    /* Number of active schedule slots (1-5). Lets a remote push add or remove
 slots — the per-slot fragments above can only mutate existing ones.
 Firmware rails: growing requires the same transaction to configure each
 new slot (at minimum its time window); staging zeroes slots beyond the
 live count at BEGIN so a stale array entry can never be resurrected. */
    bool has_schedules_count;
    uint32_t schedules_count;
} config_system_t;

/* Geofence definition, delivered through the config transaction one
 fragment per vertex plus one meta fragment (DESIGN_geofence_actions.md —
 a worst-case vertex is ~14 B against the 33 B RX2 floor). The meta
 fragment carries every scalar; vertex fragments carry vertex_index +
 vertex. vertex_count = 0 on a meta fragment deletes the fence. The same
 message is the self-report vocabulary (consumed reports a fired detach
 fence). Rails: R7 shape, R8 zone slot, R9 GPS off, R10 detach safety. */
typedef struct config_geofence {
    uint32_t fence_id; /* 1..4 */
    bool has_action;
    uint32_t action; /* 0=SCHEDULE_OVERRIDE 1=DETACH 2=REPORT_ONLY */
    bool has_zone_slot;
    uint32_t zone_slot; /* SCHEDULE_OVERRIDE: slot to preempt with */
    bool has_confirm_fixes;
    uint32_t confirm_fixes; /* default 2 */
    bool has_min_dwell_min;
    uint32_t min_dwell_min; /* default 15; state lock after transitions */
    bool has_max_hacc_m;
    uint32_t max_hacc_m; /* 0 = no accuracy gate */
    bool has_start_epoch;
    uint32_t start_epoch; /* 0 = armed on delivery */
    bool has_expiry_epoch;
    uint32_t expiry_epoch; /* mandatory for DETACH (<= start+30 d) */
    bool has_vertex_count;
    uint32_t vertex_count; /* meta fragment; 0 = delete fence */
    bool has_vertex_index;
    uint32_t vertex_index; /* vertex fragment */
    bool has_vertex;
    geo_point_t vertex; /* vertex fragment */
    bool has_consumed;
    bool consumed; /* report only: detach fence has fired */
} config_geofence_t;

/* ---- Config fragment wrapper ----
 Pairs a schedule slot index with exactly one sensor/system config.
 fragment_index and fragment_total enable integrity checking on commit. */
typedef struct config_fragment {
    uint32_t schedule_index; /* target schedule slot (0-4) */
    uint32_t fragment_index; /* 0-based index of this fragment in the transaction */
    uint32_t fragment_total; /* total number of fragments the server will send */
    pb_size_t which_setting;
    union {
        config_time_window_t cfg_time_window;
        config_accelerometer_t cfg_accelerometer;
        config_microphone_t cfg_microphone;
        config_gps_t cfg_gps;
        config_magnetometer_t cfg_magnetometer;
        config_sampling_t cfg_light;
        config_sampling_t cfg_environmental;
        config_sampling_t cfg_particulate;
        config_radio_timing_t cfg_radio_timing;
        config_system_t cfg_system; /* global, schedule_index ignored */
        config_mortality_t cfg_mortality; /* global, schedule_index ignored */
        config_geofence_t cfg_geofence; /* global, schedule_index ignored */
    } setting;
} config_fragment_t;

/* ---- Main downlink envelope ---- */
typedef struct downlink_packet {
    uint32_t epoch; /* server UTC epoch for RTC sync */
    command_type_t command; /* command to execute */
    bool has_high_fix_params;
    high_fix_params_t high_fix_params;
    bool has_geofence;
    geofence_data_t geofence;
    /* Config fragment: one per downlink.
 Only processed when a config transaction is open (after CMD_CONFIG_BEGIN).
 On CMD_CONFIG_COMMIT, device checks that all fragment_total fragments
 were received (via a bitmask indexed by fragment_index). If any are
 missing, commit is rejected, staging is discarded, and the device
 uplinks a NACK with the missing fragment bitmask so the server can retry. */
    bool has_config;
    config_fragment_t config;
    /* CMD_ADDON_ARM: the armed drop-off time. Deliberately NOT the epoch
 field above — that one is the RTC-sync reference on every downlink. */
    bool has_addon_arm_epoch;
    uint32_t addon_arm_epoch;
    /* CMD_RESEND: bit i of resend_mask set => replay the stored uplink with
 packet_index == resend_from + i (bit 0 = resend_from itself), so one
 command names up to 32 indices. Device replays at most a few per
 command (duty cycle); the server re-requests the rest later. */
    bool has_resend_from;
    uint32_t resend_from;
    bool has_resend_mask;
    uint32_t resend_mask;
    /* Config transaction id, present on CMD_CONFIG_BEGIN/COMMIT/ABORT and on
 every fragment of that transaction. Echoed back in the device's
 AckPacket so a retried COMMIT and a stale ack are distinguishable.
 Server-assigned, monotonically increasing per device; 0 = legacy client. */
    bool has_cfg_txn_id;
    uint32_t cfg_txn_id;
} downlink_packet_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _COMMAND_TYPE_MIN COMMAND_TYPE_CMD_NONE
#define _COMMAND_TYPE_MAX COMMAND_TYPE_CMD_CONFIG_REPORT
#define _COMMAND_TYPE_ARRAYSIZE ((command_type_t)(COMMAND_TYPE_CMD_CONFIG_REPORT+1))















#define downlink_packet_t_command_ENUMTYPE command_type_t


/* Initializer values for message structs */
#define GEO_POINT_INIT_DEFAULT                   {0, 0}
#define GEOFENCE_DATA_INIT_DEFAULT               {0, 0, {GEO_POINT_INIT_DEFAULT, GEO_POINT_INIT_DEFAULT, GEO_POINT_INIT_DEFAULT, GEO_POINT_INIT_DEFAULT, GEO_POINT_INIT_DEFAULT, GEO_POINT_INIT_DEFAULT, GEO_POINT_INIT_DEFAULT, GEO_POINT_INIT_DEFAULT}, 0}
#define HIGH_FIX_PARAMS_INIT_DEFAULT             {0, 0}
#define CONFIG_TIME_WINDOW_INIT_DEFAULT          {false, 0, false, 0}
#define CONFIG_ACCELEROMETER_INIT_DEFAULT        {false, 0, false, 0, false, 0}
#define CONFIG_MICROPHONE_INIT_DEFAULT           {false, 0, false, 0, false, 0, false, 0}
#define CONFIG_GPS_INIT_DEFAULT                  {false, 0, false, 0, false, 0}
#define CONFIG_MAGNETOMETER_INIT_DEFAULT         {false, 0, false, 0}
#define CONFIG_SAMPLING_INIT_DEFAULT             {false, 0, false, 0}
#define CONFIG_RADIO_TIMING_INIT_DEFAULT         {false, 0, false, 0, false, 0, false, 0, false, 0}
#define CONFIG_MORTALITY_INIT_DEFAULT            {false, 0, false, 0, false, 0}
#define CONFIG_SYSTEM_INIT_DEFAULT               {false, 0, false, 0, false, 0, false, 0}
#define CONFIG_GEOFENCE_INIT_DEFAULT             {0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, GEO_POINT_INIT_DEFAULT, false, 0}
#define CONFIG_FRAGMENT_INIT_DEFAULT             {0, 0, 0, 0, {CONFIG_TIME_WINDOW_INIT_DEFAULT}}
#define DOWNLINK_PACKET_INIT_DEFAULT             {0, _COMMAND_TYPE_MIN, false, HIGH_FIX_PARAMS_INIT_DEFAULT, false, GEOFENCE_DATA_INIT_DEFAULT, false, CONFIG_FRAGMENT_INIT_DEFAULT, false, 0, false, 0, false, 0, false, 0}
#define GEO_POINT_INIT_ZERO                      {0, 0}
#define GEOFENCE_DATA_INIT_ZERO                  {0, 0, {GEO_POINT_INIT_ZERO, GEO_POINT_INIT_ZERO, GEO_POINT_INIT_ZERO, GEO_POINT_INIT_ZERO, GEO_POINT_INIT_ZERO, GEO_POINT_INIT_ZERO, GEO_POINT_INIT_ZERO, GEO_POINT_INIT_ZERO}, 0}
#define HIGH_FIX_PARAMS_INIT_ZERO                {0, 0}
#define CONFIG_TIME_WINDOW_INIT_ZERO             {false, 0, false, 0}
#define CONFIG_ACCELEROMETER_INIT_ZERO           {false, 0, false, 0, false, 0}
#define CONFIG_MICROPHONE_INIT_ZERO              {false, 0, false, 0, false, 0, false, 0}
#define CONFIG_GPS_INIT_ZERO                     {false, 0, false, 0, false, 0}
#define CONFIG_MAGNETOMETER_INIT_ZERO            {false, 0, false, 0}
#define CONFIG_SAMPLING_INIT_ZERO                {false, 0, false, 0}
#define CONFIG_RADIO_TIMING_INIT_ZERO            {false, 0, false, 0, false, 0, false, 0, false, 0}
#define CONFIG_MORTALITY_INIT_ZERO               {false, 0, false, 0, false, 0}
#define CONFIG_SYSTEM_INIT_ZERO                  {false, 0, false, 0, false, 0, false, 0}
#define CONFIG_GEOFENCE_INIT_ZERO                {0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, GEO_POINT_INIT_ZERO, false, 0}
#define CONFIG_FRAGMENT_INIT_ZERO                {0, 0, 0, 0, {CONFIG_TIME_WINDOW_INIT_ZERO}}
#define DOWNLINK_PACKET_INIT_ZERO                {0, _COMMAND_TYPE_MIN, false, HIGH_FIX_PARAMS_INIT_ZERO, false, GEOFENCE_DATA_INIT_ZERO, false, CONFIG_FRAGMENT_INIT_ZERO, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define GEO_POINT_LATITUDE_E7_TAG                1
#define GEO_POINT_LONGITUDE_E7_TAG               2
#define GEOFENCE_DATA_FENCE_ID_TAG               1
#define GEOFENCE_DATA_VERTICES_TAG               2
#define GEOFENCE_DATA_ACTIVE_TAG                 3
#define HIGH_FIX_PARAMS_DURATION_HOURS_TAG       1
#define HIGH_FIX_PARAMS_SAMPLE_INTERVAL_SEC_TAG  2
#define CONFIG_TIME_WINDOW_START_HOUR_TAG        1
#define CONFIG_TIME_WINDOW_END_HOUR_TAG          2
#define CONFIG_ACCELEROMETER_ENABLED_TAG         1
#define CONFIG_ACCELEROMETER_SAMPLE_RATE_TAG     2
#define CONFIG_ACCELEROMETER_SENSITIVITY_TAG     3
#define CONFIG_MICROPHONE_ENABLED_TAG            1
#define CONFIG_MICROPHONE_CONTINUOUS_MODE_TAG    2
#define CONFIG_MICROPHONE_SAMPLE_LENGTH_MIN_TAG  3
#define CONFIG_MICROPHONE_SAMPLE_WINDOW_MIN_TAG  4
#define CONFIG_GPS_ENABLED_TAG                   1
#define CONFIG_GPS_SAMPLE_INTERVAL_MIN_TAG       2
#define CONFIG_GPS_ACCURACY_TAG                  3
#define CONFIG_MAGNETOMETER_ENABLED_TAG          1
#define CONFIG_MAGNETOMETER_SAMPLE_INTERVAL_S_TAG 2
#define CONFIG_SAMPLING_ENABLED_TAG              1
#define CONFIG_SAMPLING_SAMPLE_INTERVAL_MIN_TAG  2
#define CONFIG_RADIO_TIMING_LORAWAN_ENABLED_TAG  1
#define CONFIG_RADIO_TIMING_LORAWAN_SEND_INTERVAL_MIN_TAG 2
#define CONFIG_RADIO_TIMING_LORA_ENABLED_TAG     3
#define CONFIG_RADIO_TIMING_LORA_SEND_INTERVAL_MIN_TAG 4
#define CONFIG_RADIO_TIMING_TX_POWER_DBM_TAG     5
#define CONFIG_MORTALITY_ENABLED_TAG             1
#define CONFIG_MORTALITY_TRIGGER_DURATION_HOURS_TAG 2
#define CONFIG_MORTALITY_TRANSMIT_INTERVAL_MIN_TAG 3
#define CONFIG_SYSTEM_VERBOSE_LOGGING_TAG        1
#define CONFIG_SYSTEM_ENABLE_RESET_ON_ERROR_TAG  2
#define CONFIG_SYSTEM_SPECIAL_MODE_TAG           3
#define CONFIG_SYSTEM_SCHEDULES_COUNT_TAG        4
#define CONFIG_GEOFENCE_FENCE_ID_TAG             1
#define CONFIG_GEOFENCE_ACTION_TAG               2
#define CONFIG_GEOFENCE_ZONE_SLOT_TAG            3
#define CONFIG_GEOFENCE_CONFIRM_FIXES_TAG        4
#define CONFIG_GEOFENCE_MIN_DWELL_MIN_TAG        5
#define CONFIG_GEOFENCE_MAX_HACC_M_TAG           6
#define CONFIG_GEOFENCE_START_EPOCH_TAG          7
#define CONFIG_GEOFENCE_EXPIRY_EPOCH_TAG         8
#define CONFIG_GEOFENCE_VERTEX_COUNT_TAG         9
#define CONFIG_GEOFENCE_VERTEX_INDEX_TAG         10
#define CONFIG_GEOFENCE_VERTEX_TAG               11
#define CONFIG_GEOFENCE_CONSUMED_TAG             12
#define CONFIG_FRAGMENT_SCHEDULE_INDEX_TAG       1
#define CONFIG_FRAGMENT_FRAGMENT_INDEX_TAG       2
#define CONFIG_FRAGMENT_FRAGMENT_TOTAL_TAG       3
#define CONFIG_FRAGMENT_CFG_TIME_WINDOW_TAG      4
#define CONFIG_FRAGMENT_CFG_ACCELEROMETER_TAG    5
#define CONFIG_FRAGMENT_CFG_MICROPHONE_TAG       6
#define CONFIG_FRAGMENT_CFG_GPS_TAG              7
#define CONFIG_FRAGMENT_CFG_MAGNETOMETER_TAG     8
#define CONFIG_FRAGMENT_CFG_LIGHT_TAG            9
#define CONFIG_FRAGMENT_CFG_ENVIRONMENTAL_TAG    10
#define CONFIG_FRAGMENT_CFG_PARTICULATE_TAG      11
#define CONFIG_FRAGMENT_CFG_RADIO_TIMING_TAG     12
#define CONFIG_FRAGMENT_CFG_SYSTEM_TAG           13
#define CONFIG_FRAGMENT_CFG_MORTALITY_TAG        14
#define CONFIG_FRAGMENT_CFG_GEOFENCE_TAG         15
#define DOWNLINK_PACKET_EPOCH_TAG                1
#define DOWNLINK_PACKET_COMMAND_TAG              2
#define DOWNLINK_PACKET_HIGH_FIX_PARAMS_TAG      3
#define DOWNLINK_PACKET_GEOFENCE_TAG             4
#define DOWNLINK_PACKET_CONFIG_TAG               5
#define DOWNLINK_PACKET_ADDON_ARM_EPOCH_TAG      6
#define DOWNLINK_PACKET_RESEND_FROM_TAG          7
#define DOWNLINK_PACKET_RESEND_MASK_TAG          8
#define DOWNLINK_PACKET_CFG_TXN_ID_TAG           9

/* Struct field encoding specification for nanopb */
#define GEO_POINT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    latitude_e7,       1) \
X(a, STATIC,   SINGULAR, INT32,    longitude_e7,      2)
#define GEO_POINT_CALLBACK NULL
#define GEO_POINT_DEFAULT NULL

#define GEOFENCE_DATA_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   fence_id,          1) \
X(a, STATIC,   REPEATED, MESSAGE,  vertices,          2) \
X(a, STATIC,   SINGULAR, BOOL,     active,            3)
#define GEOFENCE_DATA_CALLBACK NULL
#define GEOFENCE_DATA_DEFAULT NULL
#define geofence_data_t_vertices_MSGTYPE geo_point_t

#define HIGH_FIX_PARAMS_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   duration_hours,    1) \
X(a, STATIC,   SINGULAR, UINT32,   sample_interval_sec,   2)
#define HIGH_FIX_PARAMS_CALLBACK NULL
#define HIGH_FIX_PARAMS_DEFAULT NULL

#define CONFIG_TIME_WINDOW_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   start_hour,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   end_hour,          2)
#define CONFIG_TIME_WINDOW_CALLBACK NULL
#define CONFIG_TIME_WINDOW_DEFAULT NULL

#define CONFIG_ACCELEROMETER_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   sample_rate,       2) \
X(a, STATIC,   OPTIONAL, UINT32,   sensitivity,       3)
#define CONFIG_ACCELEROMETER_CALLBACK NULL
#define CONFIG_ACCELEROMETER_DEFAULT NULL

#define CONFIG_MICROPHONE_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           1) \
X(a, STATIC,   OPTIONAL, BOOL,     continuous_mode,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   sample_length_min,   3) \
X(a, STATIC,   OPTIONAL, UINT32,   sample_window_min,   4)
#define CONFIG_MICROPHONE_CALLBACK NULL
#define CONFIG_MICROPHONE_DEFAULT NULL

#define CONFIG_GPS_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   sample_interval_min,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   accuracy,          3)
#define CONFIG_GPS_CALLBACK NULL
#define CONFIG_GPS_DEFAULT NULL

#define CONFIG_MAGNETOMETER_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   sample_interval_s,   2)
#define CONFIG_MAGNETOMETER_CALLBACK NULL
#define CONFIG_MAGNETOMETER_DEFAULT NULL

#define CONFIG_SAMPLING_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   sample_interval_min,   2)
#define CONFIG_SAMPLING_CALLBACK NULL
#define CONFIG_SAMPLING_DEFAULT NULL

#define CONFIG_RADIO_TIMING_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     lorawan_enabled,   1) \
X(a, STATIC,   OPTIONAL, UINT32,   lorawan_send_interval_min,   2) \
X(a, STATIC,   OPTIONAL, BOOL,     lora_enabled,      3) \
X(a, STATIC,   OPTIONAL, UINT32,   lora_send_interval_min,   4) \
X(a, STATIC,   OPTIONAL, INT32,    tx_power_dbm,      5)
#define CONFIG_RADIO_TIMING_CALLBACK NULL
#define CONFIG_RADIO_TIMING_DEFAULT NULL

#define CONFIG_MORTALITY_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   trigger_duration_hours,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   transmit_interval_min,   3)
#define CONFIG_MORTALITY_CALLBACK NULL
#define CONFIG_MORTALITY_DEFAULT NULL

#define CONFIG_SYSTEM_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     verbose_logging,   1) \
X(a, STATIC,   OPTIONAL, BOOL,     enable_reset_on_error,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   special_mode,      3) \
X(a, STATIC,   OPTIONAL, UINT32,   schedules_count,   4)
#define CONFIG_SYSTEM_CALLBACK NULL
#define CONFIG_SYSTEM_DEFAULT NULL

#define CONFIG_GEOFENCE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   fence_id,          1) \
X(a, STATIC,   OPTIONAL, UINT32,   action,            2) \
X(a, STATIC,   OPTIONAL, UINT32,   zone_slot,         3) \
X(a, STATIC,   OPTIONAL, UINT32,   confirm_fixes,     4) \
X(a, STATIC,   OPTIONAL, UINT32,   min_dwell_min,     5) \
X(a, STATIC,   OPTIONAL, UINT32,   max_hacc_m,        6) \
X(a, STATIC,   OPTIONAL, UINT32,   start_epoch,       7) \
X(a, STATIC,   OPTIONAL, UINT32,   expiry_epoch,      8) \
X(a, STATIC,   OPTIONAL, UINT32,   vertex_count,      9) \
X(a, STATIC,   OPTIONAL, UINT32,   vertex_index,     10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vertex,           11) \
X(a, STATIC,   OPTIONAL, BOOL,     consumed,         12)
#define CONFIG_GEOFENCE_CALLBACK NULL
#define CONFIG_GEOFENCE_DEFAULT NULL
#define config_geofence_t_vertex_MSGTYPE geo_point_t

#define CONFIG_FRAGMENT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   schedule_index,    1) \
X(a, STATIC,   SINGULAR, UINT32,   fragment_index,    2) \
X(a, STATIC,   SINGULAR, UINT32,   fragment_total,    3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_time_window,setting.cfg_time_window),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_accelerometer,setting.cfg_accelerometer),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_microphone,setting.cfg_microphone),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_gps,setting.cfg_gps),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_magnetometer,setting.cfg_magnetometer),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_light,setting.cfg_light),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_environmental,setting.cfg_environmental),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_particulate,setting.cfg_particulate),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_radio_timing,setting.cfg_radio_timing),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_system,setting.cfg_system),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_mortality,setting.cfg_mortality),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting,cfg_geofence,setting.cfg_geofence),  15)
#define CONFIG_FRAGMENT_CALLBACK NULL
#define CONFIG_FRAGMENT_DEFAULT NULL
#define config_fragment_t_setting_cfg_time_window_MSGTYPE config_time_window_t
#define config_fragment_t_setting_cfg_accelerometer_MSGTYPE config_accelerometer_t
#define config_fragment_t_setting_cfg_microphone_MSGTYPE config_microphone_t
#define config_fragment_t_setting_cfg_gps_MSGTYPE config_gps_t
#define config_fragment_t_setting_cfg_magnetometer_MSGTYPE config_magnetometer_t
#define config_fragment_t_setting_cfg_light_MSGTYPE config_sampling_t
#define config_fragment_t_setting_cfg_environmental_MSGTYPE config_sampling_t
#define config_fragment_t_setting_cfg_particulate_MSGTYPE config_sampling_t
#define config_fragment_t_setting_cfg_radio_timing_MSGTYPE config_radio_timing_t
#define config_fragment_t_setting_cfg_system_MSGTYPE config_system_t
#define config_fragment_t_setting_cfg_mortality_MSGTYPE config_mortality_t
#define config_fragment_t_setting_cfg_geofence_MSGTYPE config_geofence_t

#define DOWNLINK_PACKET_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   epoch,             1) \
X(a, STATIC,   SINGULAR, UENUM,    command,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  high_fix_params,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  geofence,          4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            5) \
X(a, STATIC,   OPTIONAL, UINT32,   addon_arm_epoch,   6) \
X(a, STATIC,   OPTIONAL, UINT32,   resend_from,       7) \
X(a, STATIC,   OPTIONAL, UINT32,   resend_mask,       8) \
X(a, STATIC,   OPTIONAL, UINT32,   cfg_txn_id,        9)
#define DOWNLINK_PACKET_CALLBACK NULL
#define DOWNLINK_PACKET_DEFAULT NULL
#define downlink_packet_t_high_fix_params_MSGTYPE high_fix_params_t
#define downlink_packet_t_geofence_MSGTYPE geofence_data_t
#define downlink_packet_t_config_MSGTYPE config_fragment_t

extern const pb_msgdesc_t geo_point_t_msg;
extern const pb_msgdesc_t geofence_data_t_msg;
extern const pb_msgdesc_t high_fix_params_t_msg;
extern const pb_msgdesc_t config_time_window_t_msg;
extern const pb_msgdesc_t config_accelerometer_t_msg;
extern const pb_msgdesc_t config_microphone_t_msg;
extern const pb_msgdesc_t config_gps_t_msg;
extern const pb_msgdesc_t config_magnetometer_t_msg;
extern const pb_msgdesc_t config_sampling_t_msg;
extern const pb_msgdesc_t config_radio_timing_t_msg;
extern const pb_msgdesc_t config_mortality_t_msg;
extern const pb_msgdesc_t config_system_t_msg;
extern const pb_msgdesc_t config_geofence_t_msg;
extern const pb_msgdesc_t config_fragment_t_msg;
extern const pb_msgdesc_t downlink_packet_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GEO_POINT_FIELDS &geo_point_t_msg
#define GEOFENCE_DATA_FIELDS &geofence_data_t_msg
#define HIGH_FIX_PARAMS_FIELDS &high_fix_params_t_msg
#define CONFIG_TIME_WINDOW_FIELDS &config_time_window_t_msg
#define CONFIG_ACCELEROMETER_FIELDS &config_accelerometer_t_msg
#define CONFIG_MICROPHONE_FIELDS &config_microphone_t_msg
#define CONFIG_GPS_FIELDS &config_gps_t_msg
#define CONFIG_MAGNETOMETER_FIELDS &config_magnetometer_t_msg
#define CONFIG_SAMPLING_FIELDS &config_sampling_t_msg
#define CONFIG_RADIO_TIMING_FIELDS &config_radio_timing_t_msg
#define CONFIG_MORTALITY_FIELDS &config_mortality_t_msg
#define CONFIG_SYSTEM_FIELDS &config_system_t_msg
#define CONFIG_GEOFENCE_FIELDS &config_geofence_t_msg
#define CONFIG_FRAGMENT_FIELDS &config_fragment_t_msg
#define DOWNLINK_PACKET_FIELDS &downlink_packet_t_msg

/* Maximum encoded size of messages (where known) */
#define CONFIG_ACCELEROMETER_SIZE                14
#define CONFIG_FRAGMENT_SIZE                     106
#define CONFIG_GEOFENCE_SIZE                     86
#define CONFIG_GPS_SIZE                          14
#define CONFIG_MAGNETOMETER_SIZE                 8
#define CONFIG_MICROPHONE_SIZE                   16
#define CONFIG_MORTALITY_SIZE                    14
#define CONFIG_RADIO_TIMING_SIZE                 27
#define CONFIG_SAMPLING_SIZE                     8
#define CONFIG_SYSTEM_SIZE                       16
#define CONFIG_TIME_WINDOW_SIZE                  12
#define DOWNLINK_PACKET_SIZE                     357
#define GEOFENCE_DATA_SIZE                       200
#define GEO_POINT_SIZE                           22
#define HIGH_FIX_PARAMS_SIZE                     12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
