/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "downlink.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GeoPoint, GeoPoint, AUTO)


PB_BIND(GeofenceData, GeofenceData, AUTO)


PB_BIND(HighFixParams, HighFixParams, AUTO)


PB_BIND(ConfigTimeWindow, ConfigTimeWindow, AUTO)


PB_BIND(ConfigAccelerometer, ConfigAccelerometer, AUTO)


PB_BIND(ConfigMicrophone, ConfigMicrophone, AUTO)


PB_BIND(ConfigGPS, ConfigGPS, AUTO)


PB_BIND(ConfigMagnetometer, ConfigMagnetometer, AUTO)


PB_BIND(ConfigSampling, ConfigSampling, AUTO)


PB_BIND(ConfigRadioTiming, ConfigRadioTiming, AUTO)


PB_BIND(ConfigSystem, ConfigSystem, AUTO)


PB_BIND(ConfigFragment, ConfigFragment, AUTO)


PB_BIND(DownlinkPacket, DownlinkPacket, AUTO)




