/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_MESSAGE_PB_H_INCLUDED
#define PB_MESSAGE_PB_H_INCLUDED
#include <pb.h>
#include "common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct metadata {
    float gps_avg_fix_time;
} metadata_t;

typedef struct config_packet {
    bool engage_system;
    bool enable_microphone;
    bool enable_activity;
    bool enable_particulate;
    bool enable_environmental;
    bool enable_light;
    bool enable_motion;
    bool enable_lora;
} config_packet_t;

typedef struct gps_data_2 {
    int32_t latitude_e7;
    int32_t longitude_e7;
    bool has_altitude_mm;
    uint32_t altitude_mm;
    uint32_t timestamp;
    bool has_gps_avg_fix_time_ms;
    uint32_t gps_avg_fix_time_ms;
    bool has_hdop;
    uint32_t hdop;
} gps_data_2_t;

typedef struct system_sensor_summary {
    float temperature;
    float humidity;
    float pressure;
    float gas;
    float pm1;
    float pm2_5;
    float pm10;
    uint32_t light;
    uint32_t steps;
    bool particulate_obstructed;
    bool particulate_outside_detection_limits;
} system_sensor_summary_t;

typedef struct system_info_packet {
    bool has_system_sensor_summary;
    system_sensor_summary_t system_sensor_summary;
    bool has_sdcard_state;
    sd_card_state_t sdcard_state;
    bool has_battery_state;
    battery_state_t battery_state;
    bool has_metadata;
    metadata_t metadata;
    bool has_gps_data;
    gps_data_t gps_data;
} system_info_packet_t;

typedef struct ack_packet {
    char dummy_field;
} ack_packet_t;

typedef struct radio_info {
    int32_t rssi;
    int32_t snr;
    int32_t rssi_est;
} radio_info_t;

typedef struct acc_axis {
    uint32_t x;
    uint32_t y;
    uint32_t z;
} acc_axis_t;

typedef struct acc_stats {
    uint32_t odba_mean_x100;
    uint32_t odba_max_x100;
    uint32_t ve_dba_mean_x100;
    uint32_t ve_dba_max_x100;
    bool has_std_dev_x100;
    acc_axis_t std_dev_x100;
    bool has_mean_x100;
    acc_axis_t mean_x100;
} acc_stats_t;

typedef struct env_data {
    bool has_temperature_x10;
    int32_t temperature_x10;
    bool has_humidity_x10;
    uint32_t humidity_x10;
    bool has_gas;
    uint32_t gas;
    bool has_pressure;
    uint32_t pressure;
    bool has_light;
    uint32_t light;
    bool has_timestamp;
    uint32_t timestamp;
} env_data_t;

typedef struct particulate_data {
    uint32_t pm1;
    uint32_t pm2_5;
    uint32_t pm10;
    bool has_timestamp;
    uint32_t timestamp;
} particulate_data_t;

typedef struct error_flags {
    uint32_t flag;
} error_flags_t;

typedef struct deployment {
    bool has_particulate_data;
    particulate_data_t particulate_data;
    bool has_env_data;
    env_data_t env_data;
    bool has_space_remaining_mb;
    uint32_t space_remaining_mb;
    uint32_t battery_percentage_x10;
    bool has_acc_stats;
    acc_stats_t acc_stats;
    bool has_steps;
    uint32_t steps;
    pb_size_t gps_data_count;
    gps_data_2_t gps_data[5];
    bool has_error_flags;
    error_flags_t error_flags;
} deployment_t;

typedef struct message_packet {
    bool has_header;
    packet_header_t header;
    pb_size_t which_payload;
    union {
        system_info_packet_t system_info_packet;
        config_packet_t config_packet;
        ack_packet_t ack_packet;
        deployment_t system_deployment_packet;
    } payload;
    bool has_radio_info;
    radio_info_t radio_info;
} message_packet_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SYSTEM_INFO_PACKET_INIT_DEFAULT          {false, SYSTEM_SENSOR_SUMMARY_INIT_DEFAULT, false, SD_CARD_STATE_INIT_DEFAULT, false, BATTERY_STATE_INIT_DEFAULT, false, METADATA_INIT_DEFAULT, false, GPS_DATA_INIT_DEFAULT}
#define METADATA_INIT_DEFAULT                    {0}
#define CONFIG_PACKET_INIT_DEFAULT               {0, 0, 0, 0, 0, 0, 0, 0}
#define GPS_DATA_2_INIT_DEFAULT                  {0, 0, false, 0, 0, false, 0, false, 0}
#define SYSTEM_SENSOR_SUMMARY_INIT_DEFAULT       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define ACK_PACKET_INIT_DEFAULT                  {0}
#define RADIO_INFO_INIT_DEFAULT                  {0, 0, 0}
#define ACC_AXIS_INIT_DEFAULT                    {0, 0, 0}
#define ACC_STATS_INIT_DEFAULT                   {0, 0, 0, 0, false, ACC_AXIS_INIT_DEFAULT, false, ACC_AXIS_INIT_DEFAULT}
#define ENV_DATA_INIT_DEFAULT                    {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define PARTICULATE_DATA_INIT_DEFAULT            {0, 0, 0, false, 0}
#define ERROR_FLAGS_INIT_DEFAULT                 {0}
#define DEPLOYMENT_INIT_DEFAULT                  {false, PARTICULATE_DATA_INIT_DEFAULT, false, ENV_DATA_INIT_DEFAULT, false, 0, 0, false, ACC_STATS_INIT_DEFAULT, false, 0, 0, {GPS_DATA_2_INIT_DEFAULT, GPS_DATA_2_INIT_DEFAULT, GPS_DATA_2_INIT_DEFAULT, GPS_DATA_2_INIT_DEFAULT, GPS_DATA_2_INIT_DEFAULT}, false, ERROR_FLAGS_INIT_DEFAULT}
#define MESSAGE_PACKET_INIT_DEFAULT              {false, PACKET_HEADER_INIT_DEFAULT, 0, {SYSTEM_INFO_PACKET_INIT_DEFAULT}, false, RADIO_INFO_INIT_DEFAULT}
#define SYSTEM_INFO_PACKET_INIT_ZERO             {false, SYSTEM_SENSOR_SUMMARY_INIT_ZERO, false, SD_CARD_STATE_INIT_ZERO, false, BATTERY_STATE_INIT_ZERO, false, METADATA_INIT_ZERO, false, GPS_DATA_INIT_ZERO}
#define METADATA_INIT_ZERO                       {0}
#define CONFIG_PACKET_INIT_ZERO                  {0, 0, 0, 0, 0, 0, 0, 0}
#define GPS_DATA_2_INIT_ZERO                     {0, 0, false, 0, 0, false, 0, false, 0}
#define SYSTEM_SENSOR_SUMMARY_INIT_ZERO          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define ACK_PACKET_INIT_ZERO                     {0}
#define RADIO_INFO_INIT_ZERO                     {0, 0, 0}
#define ACC_AXIS_INIT_ZERO                       {0, 0, 0}
#define ACC_STATS_INIT_ZERO                      {0, 0, 0, 0, false, ACC_AXIS_INIT_ZERO, false, ACC_AXIS_INIT_ZERO}
#define ENV_DATA_INIT_ZERO                       {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define PARTICULATE_DATA_INIT_ZERO               {0, 0, 0, false, 0}
#define ERROR_FLAGS_INIT_ZERO                    {0}
#define DEPLOYMENT_INIT_ZERO                     {false, PARTICULATE_DATA_INIT_ZERO, false, ENV_DATA_INIT_ZERO, false, 0, 0, false, ACC_STATS_INIT_ZERO, false, 0, 0, {GPS_DATA_2_INIT_ZERO, GPS_DATA_2_INIT_ZERO, GPS_DATA_2_INIT_ZERO, GPS_DATA_2_INIT_ZERO, GPS_DATA_2_INIT_ZERO}, false, ERROR_FLAGS_INIT_ZERO}
#define MESSAGE_PACKET_INIT_ZERO                 {false, PACKET_HEADER_INIT_ZERO, 0, {SYSTEM_INFO_PACKET_INIT_ZERO}, false, RADIO_INFO_INIT_ZERO}

/* Field tags (for use in manual encoding/decoding) */
#define METADATA_GPS_AVG_FIX_TIME_TAG            1
#define CONFIG_PACKET_ENGAGE_SYSTEM_TAG          1
#define CONFIG_PACKET_ENABLE_MICROPHONE_TAG      2
#define CONFIG_PACKET_ENABLE_ACTIVITY_TAG        3
#define CONFIG_PACKET_ENABLE_PARTICULATE_TAG     4
#define CONFIG_PACKET_ENABLE_ENVIRONMENTAL_TAG   5
#define CONFIG_PACKET_ENABLE_LIGHT_TAG           6
#define CONFIG_PACKET_ENABLE_MOTION_TAG          7
#define CONFIG_PACKET_ENABLE_LORA_TAG            8
#define GPS_DATA_2_LATITUDE_E7_TAG               1
#define GPS_DATA_2_LONGITUDE_E7_TAG              2
#define GPS_DATA_2_ALTITUDE_MM_TAG               3
#define GPS_DATA_2_TIMESTAMP_TAG                 4
#define GPS_DATA_2_GPS_AVG_FIX_TIME_MS_TAG       5
#define GPS_DATA_2_HDOP_TAG                      6
#define SYSTEM_SENSOR_SUMMARY_TEMPERATURE_TAG    1
#define SYSTEM_SENSOR_SUMMARY_HUMIDITY_TAG       2
#define SYSTEM_SENSOR_SUMMARY_PRESSURE_TAG       3
#define SYSTEM_SENSOR_SUMMARY_GAS_TAG            4
#define SYSTEM_SENSOR_SUMMARY_PM1_TAG            5
#define SYSTEM_SENSOR_SUMMARY_PM2_5_TAG          6
#define SYSTEM_SENSOR_SUMMARY_PM10_TAG           7
#define SYSTEM_SENSOR_SUMMARY_LIGHT_TAG          8
#define SYSTEM_SENSOR_SUMMARY_STEPS_TAG          9
#define SYSTEM_SENSOR_SUMMARY_PARTICULATE_OBSTRUCTED_TAG 10
#define SYSTEM_SENSOR_SUMMARY_PARTICULATE_OUTSIDE_DETECTION_LIMITS_TAG 11
#define SYSTEM_INFO_PACKET_SYSTEM_SENSOR_SUMMARY_TAG 1
#define SYSTEM_INFO_PACKET_SDCARD_STATE_TAG      2
#define SYSTEM_INFO_PACKET_BATTERY_STATE_TAG     3
#define SYSTEM_INFO_PACKET_METADATA_TAG          4
#define SYSTEM_INFO_PACKET_GPS_DATA_TAG          5
#define RADIO_INFO_RSSI_TAG                      1
#define RADIO_INFO_SNR_TAG                       2
#define RADIO_INFO_RSSI_EST_TAG                  3
#define ACC_AXIS_X_TAG                           1
#define ACC_AXIS_Y_TAG                           2
#define ACC_AXIS_Z_TAG                           3
#define ACC_STATS_ODBA_MEAN_X100_TAG             1
#define ACC_STATS_ODBA_MAX_X100_TAG              2
#define ACC_STATS_VE_DBA_MEAN_X100_TAG           3
#define ACC_STATS_VE_DBA_MAX_X100_TAG            4
#define ACC_STATS_STD_DEV_X100_TAG               5
#define ACC_STATS_MEAN_X100_TAG                  6
#define ENV_DATA_TEMPERATURE_X10_TAG             1
#define ENV_DATA_HUMIDITY_X10_TAG                2
#define ENV_DATA_GAS_TAG                         3
#define ENV_DATA_PRESSURE_TAG                    4
#define ENV_DATA_LIGHT_TAG                       5
#define ENV_DATA_TIMESTAMP_TAG                   6
#define PARTICULATE_DATA_PM1_TAG                 1
#define PARTICULATE_DATA_PM2_5_TAG               2
#define PARTICULATE_DATA_PM10_TAG                3
#define PARTICULATE_DATA_TIMESTAMP_TAG           4
#define ERROR_FLAGS_FLAG_TAG                     1
#define DEPLOYMENT_PARTICULATE_DATA_TAG          1
#define DEPLOYMENT_ENV_DATA_TAG                  2
#define DEPLOYMENT_SPACE_REMAINING_MB_TAG        3
#define DEPLOYMENT_BATTERY_PERCENTAGE_X10_TAG    4
#define DEPLOYMENT_ACC_STATS_TAG                 5
#define DEPLOYMENT_STEPS_TAG                     6
#define DEPLOYMENT_GPS_DATA_TAG                  7
#define DEPLOYMENT_ERROR_FLAGS_TAG               8
#define MESSAGE_PACKET_HEADER_TAG                1
#define MESSAGE_PACKET_SYSTEM_INFO_PACKET_TAG    2
#define MESSAGE_PACKET_CONFIG_PACKET_TAG         3
#define MESSAGE_PACKET_ACK_PACKET_TAG            4
#define MESSAGE_PACKET_SYSTEM_DEPLOYMENT_PACKET_TAG 5
#define MESSAGE_PACKET_RADIO_INFO_TAG            6

/* Struct field encoding specification for nanopb */
#define SYSTEM_INFO_PACKET_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  system_sensor_summary,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sdcard_state,      2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  battery_state,     3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  metadata,          4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gps_data,          5)
#define SYSTEM_INFO_PACKET_CALLBACK NULL
#define SYSTEM_INFO_PACKET_DEFAULT NULL
#define system_info_packet_t_system_sensor_summary_MSGTYPE system_sensor_summary_t
#define system_info_packet_t_sdcard_state_MSGTYPE sd_card_state_t
#define system_info_packet_t_battery_state_MSGTYPE battery_state_t
#define system_info_packet_t_metadata_MSGTYPE metadata_t
#define system_info_packet_t_gps_data_MSGTYPE gps_data_t

#define METADATA_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    gps_avg_fix_time,   1)
#define METADATA_CALLBACK NULL
#define METADATA_DEFAULT NULL

#define CONFIG_PACKET_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     engage_system,     1) \
X(a, STATIC,   SINGULAR, BOOL,     enable_microphone,   2) \
X(a, STATIC,   SINGULAR, BOOL,     enable_activity,   3) \
X(a, STATIC,   SINGULAR, BOOL,     enable_particulate,   4) \
X(a, STATIC,   SINGULAR, BOOL,     enable_environmental,   5) \
X(a, STATIC,   SINGULAR, BOOL,     enable_light,      6) \
X(a, STATIC,   SINGULAR, BOOL,     enable_motion,     7) \
X(a, STATIC,   SINGULAR, BOOL,     enable_lora,       8)
#define CONFIG_PACKET_CALLBACK NULL
#define CONFIG_PACKET_DEFAULT NULL

#define GPS_DATA_2_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    latitude_e7,       1) \
X(a, STATIC,   SINGULAR, INT32,    longitude_e7,      2) \
X(a, STATIC,   OPTIONAL, UINT32,   altitude_mm,       3) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         4) \
X(a, STATIC,   OPTIONAL, UINT32,   gps_avg_fix_time_ms,   5) \
X(a, STATIC,   OPTIONAL, UINT32,   hdop,              6)
#define GPS_DATA_2_CALLBACK NULL
#define GPS_DATA_2_DEFAULT NULL

#define SYSTEM_SENSOR_SUMMARY_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure,          3) \
X(a, STATIC,   SINGULAR, FLOAT,    gas,               4) \
X(a, STATIC,   SINGULAR, FLOAT,    pm1,               5) \
X(a, STATIC,   SINGULAR, FLOAT,    pm2_5,             6) \
X(a, STATIC,   SINGULAR, FLOAT,    pm10,              7) \
X(a, STATIC,   SINGULAR, UINT32,   light,             8) \
X(a, STATIC,   SINGULAR, UINT32,   steps,             9) \
X(a, STATIC,   SINGULAR, BOOL,     particulate_obstructed,  10) \
X(a, STATIC,   SINGULAR, BOOL,     particulate_outside_detection_limits,  11)
#define SYSTEM_SENSOR_SUMMARY_CALLBACK NULL
#define SYSTEM_SENSOR_SUMMARY_DEFAULT NULL

#define ACK_PACKET_FIELDLIST(X, a) \

#define ACK_PACKET_CALLBACK NULL
#define ACK_PACKET_DEFAULT NULL

#define RADIO_INFO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              1) \
X(a, STATIC,   SINGULAR, INT32,    snr,               2) \
X(a, STATIC,   SINGULAR, INT32,    rssi_est,          3)
#define RADIO_INFO_CALLBACK NULL
#define RADIO_INFO_DEFAULT NULL

#define ACC_AXIS_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   x,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   y,                 2) \
X(a, STATIC,   SINGULAR, UINT32,   z,                 3)
#define ACC_AXIS_CALLBACK NULL
#define ACC_AXIS_DEFAULT NULL

#define ACC_STATS_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   odba_mean_x100,    1) \
X(a, STATIC,   SINGULAR, UINT32,   odba_max_x100,     2) \
X(a, STATIC,   SINGULAR, UINT32,   ve_dba_mean_x100,   3) \
X(a, STATIC,   SINGULAR, UINT32,   ve_dba_max_x100,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  std_dev_x100,      5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mean_x100,         6)
#define ACC_STATS_CALLBACK NULL
#define ACC_STATS_DEFAULT NULL
#define acc_stats_t_std_dev_x100_MSGTYPE acc_axis_t
#define acc_stats_t_mean_x100_MSGTYPE acc_axis_t

#define ENV_DATA_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    temperature_x10,   1) \
X(a, STATIC,   OPTIONAL, UINT32,   humidity_x10,      2) \
X(a, STATIC,   OPTIONAL, UINT32,   gas,               3) \
X(a, STATIC,   OPTIONAL, UINT32,   pressure,          4) \
X(a, STATIC,   OPTIONAL, UINT32,   light,             5) \
X(a, STATIC,   OPTIONAL, UINT32,   timestamp,         6)
#define ENV_DATA_CALLBACK NULL
#define ENV_DATA_DEFAULT NULL

#define PARTICULATE_DATA_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pm1,               1) \
X(a, STATIC,   SINGULAR, UINT32,   pm2_5,             2) \
X(a, STATIC,   SINGULAR, UINT32,   pm10,              3) \
X(a, STATIC,   OPTIONAL, UINT32,   timestamp,         4)
#define PARTICULATE_DATA_CALLBACK NULL
#define PARTICULATE_DATA_DEFAULT NULL

#define ERROR_FLAGS_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   flag,              1)
#define ERROR_FLAGS_CALLBACK NULL
#define ERROR_FLAGS_DEFAULT NULL

#define DEPLOYMENT_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  particulate_data,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  env_data,          2) \
X(a, STATIC,   OPTIONAL, UINT32,   space_remaining_mb,   3) \
X(a, STATIC,   SINGULAR, UINT32,   battery_percentage_x10,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  acc_stats,         5) \
X(a, STATIC,   OPTIONAL, UINT32,   steps,             6) \
X(a, STATIC,   REPEATED, MESSAGE,  gps_data,          7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  error_flags,       8)
#define DEPLOYMENT_CALLBACK NULL
#define DEPLOYMENT_DEFAULT NULL
#define deployment_t_particulate_data_MSGTYPE particulate_data_t
#define deployment_t_env_data_MSGTYPE env_data_t
#define deployment_t_acc_stats_MSGTYPE acc_stats_t
#define deployment_t_gps_data_MSGTYPE gps_data_2_t
#define deployment_t_error_flags_MSGTYPE error_flags_t

#define MESSAGE_PACKET_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,system_info_packet,payload.system_info_packet),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,config_packet,payload.config_packet),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ack_packet,payload.ack_packet),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,system_deployment_packet,payload.system_deployment_packet),   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  radio_info,        6)
#define MESSAGE_PACKET_CALLBACK NULL
#define MESSAGE_PACKET_DEFAULT NULL
#define message_packet_t_header_MSGTYPE packet_header_t
#define message_packet_t_payload_system_info_packet_MSGTYPE system_info_packet_t
#define message_packet_t_payload_config_packet_MSGTYPE config_packet_t
#define message_packet_t_payload_ack_packet_MSGTYPE ack_packet_t
#define message_packet_t_payload_system_deployment_packet_MSGTYPE deployment_t
#define message_packet_t_radio_info_MSGTYPE radio_info_t

extern const pb_msgdesc_t system_info_packet_t_msg;
extern const pb_msgdesc_t metadata_t_msg;
extern const pb_msgdesc_t config_packet_t_msg;
extern const pb_msgdesc_t gps_data_2_t_msg;
extern const pb_msgdesc_t system_sensor_summary_t_msg;
extern const pb_msgdesc_t ack_packet_t_msg;
extern const pb_msgdesc_t radio_info_t_msg;
extern const pb_msgdesc_t acc_axis_t_msg;
extern const pb_msgdesc_t acc_stats_t_msg;
extern const pb_msgdesc_t env_data_t_msg;
extern const pb_msgdesc_t particulate_data_t_msg;
extern const pb_msgdesc_t error_flags_t_msg;
extern const pb_msgdesc_t deployment_t_msg;
extern const pb_msgdesc_t message_packet_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SYSTEM_INFO_PACKET_FIELDS &system_info_packet_t_msg
#define METADATA_FIELDS &metadata_t_msg
#define CONFIG_PACKET_FIELDS &config_packet_t_msg
#define GPS_DATA_2_FIELDS &gps_data_2_t_msg
#define SYSTEM_SENSOR_SUMMARY_FIELDS &system_sensor_summary_t_msg
#define ACK_PACKET_FIELDS &ack_packet_t_msg
#define RADIO_INFO_FIELDS &radio_info_t_msg
#define ACC_AXIS_FIELDS &acc_axis_t_msg
#define ACC_STATS_FIELDS &acc_stats_t_msg
#define ENV_DATA_FIELDS &env_data_t_msg
#define PARTICULATE_DATA_FIELDS &particulate_data_t_msg
#define ERROR_FLAGS_FIELDS &error_flags_t_msg
#define DEPLOYMENT_FIELDS &deployment_t_msg
#define MESSAGE_PACKET_FIELDS &message_packet_t_msg

/* Maximum encoded size of messages (where known) */
#define ACC_AXIS_SIZE                            18
#define ACC_STATS_SIZE                           64
#define ACK_PACKET_SIZE                          0
#define CONFIG_PACKET_SIZE                       16
#define DEPLOYMENT_SIZE                          401
#define ENV_DATA_SIZE                            41
#define ERROR_FLAGS_SIZE                         6
#define GPS_DATA_2_SIZE                          46
#define MESSAGE_PACKET_SIZE                      467
#define METADATA_SIZE                            5
#define PARTICULATE_DATA_SIZE                    24
#define RADIO_INFO_SIZE                          33
#define SYSTEM_INFO_PACKET_SIZE                  127
#define SYSTEM_SENSOR_SUMMARY_SIZE               51

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
