/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SystemInfoPacket, SystemInfoPacket, AUTO)


PB_BIND(Metadata, Metadata, AUTO)


PB_BIND(ConfigPacket, ConfigPacket, AUTO)


PB_BIND(GPSData_2, GPSData_2, AUTO)


PB_BIND(SystemSensorSummary, SystemSensorSummary, AUTO)


PB_BIND(AckPacket, AckPacket, AUTO)


PB_BIND(RadioInfo, RadioInfo, AUTO)


PB_BIND(AccAxis, AccAxis, AUTO)


PB_BIND(AccStats, AccStats, AUTO)


PB_BIND(EnvData, EnvData, AUTO)


PB_BIND(ParticulateData, ParticulateData, AUTO)


PB_BIND(ErrorFlags, ErrorFlags, AUTO)


PB_BIND(Deployment, Deployment, 2)


PB_BIND(AddonReport, AddonReport, AUTO)


PB_BIND(MessagePacket, MessagePacket, 2)



