// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: message.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct SystemInfoPacket: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var systemSensorSummary: SystemSensorSummary {
    get {return _storage._systemSensorSummary ?? SystemSensorSummary()}
    set {_uniqueStorage()._systemSensorSummary = newValue}
  }
  /// Returns true if `systemSensorSummary` has been explicitly set.
  var hasSystemSensorSummary: Bool {return _storage._systemSensorSummary != nil}
  /// Clears the value of `systemSensorSummary`. Subsequent reads from it will return its default value.
  mutating func clearSystemSensorSummary() {_uniqueStorage()._systemSensorSummary = nil}

  var sdcardState: SDCardState {
    get {return _storage._sdcardState ?? SDCardState()}
    set {_uniqueStorage()._sdcardState = newValue}
  }
  /// Returns true if `sdcardState` has been explicitly set.
  var hasSdcardState: Bool {return _storage._sdcardState != nil}
  /// Clears the value of `sdcardState`. Subsequent reads from it will return its default value.
  mutating func clearSdcardState() {_uniqueStorage()._sdcardState = nil}

  var batteryState: BatteryState {
    get {return _storage._batteryState ?? BatteryState()}
    set {_uniqueStorage()._batteryState = newValue}
  }
  /// Returns true if `batteryState` has been explicitly set.
  var hasBatteryState: Bool {return _storage._batteryState != nil}
  /// Clears the value of `batteryState`. Subsequent reads from it will return its default value.
  mutating func clearBatteryState() {_uniqueStorage()._batteryState = nil}

  var metadata: Metadata {
    get {return _storage._metadata ?? Metadata()}
    set {_uniqueStorage()._metadata = newValue}
  }
  /// Returns true if `metadata` has been explicitly set.
  var hasMetadata: Bool {return _storage._metadata != nil}
  /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
  mutating func clearMetadata() {_uniqueStorage()._metadata = nil}

  var gpsData: GPSData {
    get {return _storage._gpsData ?? GPSData()}
    set {_uniqueStorage()._gpsData = newValue}
  }
  /// Returns true if `gpsData` has been explicitly set.
  var hasGpsData: Bool {return _storage._gpsData != nil}
  /// Clears the value of `gpsData`. Subsequent reads from it will return its default value.
  mutating func clearGpsData() {_uniqueStorage()._gpsData = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct Metadata: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var gpsAvgFixTime: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct ConfigPacket: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var engageSystem: Bool = false

  var enableMicrophone: Bool = false

  var enableActivity: Bool = false

  var enableParticulate: Bool = false

  var enableEnvironmental: Bool = false

  var enableLight: Bool = false

  var enableMotion: Bool = false

  var enableLora: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct GPSData_2: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var latitudeE7: Int32 = 0

  var longitudeE7: Int32 = 0

  var altitudeMm: UInt32 = 0

  var timestamp: UInt32 {
    get {return _timestamp ?? 0}
    set {_timestamp = newValue}
  }
  /// Returns true if `timestamp` has been explicitly set.
  var hasTimestamp: Bool {return self._timestamp != nil}
  /// Clears the value of `timestamp`. Subsequent reads from it will return its default value.
  mutating func clearTimestamp() {self._timestamp = nil}

  var gpsAvgFixTimeMs: UInt32 {
    get {return _gpsAvgFixTimeMs ?? 0}
    set {_gpsAvgFixTimeMs = newValue}
  }
  /// Returns true if `gpsAvgFixTimeMs` has been explicitly set.
  var hasGpsAvgFixTimeMs: Bool {return self._gpsAvgFixTimeMs != nil}
  /// Clears the value of `gpsAvgFixTimeMs`. Subsequent reads from it will return its default value.
  mutating func clearGpsAvgFixTimeMs() {self._gpsAvgFixTimeMs = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _timestamp: UInt32? = nil
  fileprivate var _gpsAvgFixTimeMs: UInt32? = nil
}

struct SystemSensorSummary: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var temperature: Float = 0

  var humidity: Float = 0

  var pressure: Float = 0

  var gas: Float = 0

  var pm1: Float = 0

  var pm25: Float = 0

  var pm10: Float = 0

  var light: UInt32 = 0

  var steps: UInt32 = 0

  var particulateObstructed: Bool = false

  var particulateOutsideDetectionLimits: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct AckPacket: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct RadioInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var rssi: Int32 = 0

  var snr: Int32 = 0

  var rssiEst: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct AccAxis: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var x: UInt32 = 0

  var y: UInt32 = 0

  var z: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct AccStats: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var odbaMeanX100: UInt32 = 0

  var odbaMaxX100: UInt32 = 0

  var veDbaMeanX100: UInt32 = 0

  var veDbaMaxX100: UInt32 = 0

  var stdDevX100: AccAxis {
    get {return _stdDevX100 ?? AccAxis()}
    set {_stdDevX100 = newValue}
  }
  /// Returns true if `stdDevX100` has been explicitly set.
  var hasStdDevX100: Bool {return self._stdDevX100 != nil}
  /// Clears the value of `stdDevX100`. Subsequent reads from it will return its default value.
  mutating func clearStdDevX100() {self._stdDevX100 = nil}

  var meanX100: AccAxis {
    get {return _meanX100 ?? AccAxis()}
    set {_meanX100 = newValue}
  }
  /// Returns true if `meanX100` has been explicitly set.
  var hasMeanX100: Bool {return self._meanX100 != nil}
  /// Clears the value of `meanX100`. Subsequent reads from it will return its default value.
  mutating func clearMeanX100() {self._meanX100 = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _stdDevX100: AccAxis? = nil
  fileprivate var _meanX100: AccAxis? = nil
}

struct EnvData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var temperatureX10: Int32 {
    get {return _temperatureX10 ?? 0}
    set {_temperatureX10 = newValue}
  }
  /// Returns true if `temperatureX10` has been explicitly set.
  var hasTemperatureX10: Bool {return self._temperatureX10 != nil}
  /// Clears the value of `temperatureX10`. Subsequent reads from it will return its default value.
  mutating func clearTemperatureX10() {self._temperatureX10 = nil}

  var humidityX10: UInt32 {
    get {return _humidityX10 ?? 0}
    set {_humidityX10 = newValue}
  }
  /// Returns true if `humidityX10` has been explicitly set.
  var hasHumidityX10: Bool {return self._humidityX10 != nil}
  /// Clears the value of `humidityX10`. Subsequent reads from it will return its default value.
  mutating func clearHumidityX10() {self._humidityX10 = nil}

  var gas: UInt32 {
    get {return _gas ?? 0}
    set {_gas = newValue}
  }
  /// Returns true if `gas` has been explicitly set.
  var hasGas: Bool {return self._gas != nil}
  /// Clears the value of `gas`. Subsequent reads from it will return its default value.
  mutating func clearGas() {self._gas = nil}

  var pressure: UInt32 {
    get {return _pressure ?? 0}
    set {_pressure = newValue}
  }
  /// Returns true if `pressure` has been explicitly set.
  var hasPressure: Bool {return self._pressure != nil}
  /// Clears the value of `pressure`. Subsequent reads from it will return its default value.
  mutating func clearPressure() {self._pressure = nil}

  var light: UInt32 {
    get {return _light ?? 0}
    set {_light = newValue}
  }
  /// Returns true if `light` has been explicitly set.
  var hasLight: Bool {return self._light != nil}
  /// Clears the value of `light`. Subsequent reads from it will return its default value.
  mutating func clearLight() {self._light = nil}

  var timestamp: UInt32 {
    get {return _timestamp ?? 0}
    set {_timestamp = newValue}
  }
  /// Returns true if `timestamp` has been explicitly set.
  var hasTimestamp: Bool {return self._timestamp != nil}
  /// Clears the value of `timestamp`. Subsequent reads from it will return its default value.
  mutating func clearTimestamp() {self._timestamp = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _temperatureX10: Int32? = nil
  fileprivate var _humidityX10: UInt32? = nil
  fileprivate var _gas: UInt32? = nil
  fileprivate var _pressure: UInt32? = nil
  fileprivate var _light: UInt32? = nil
  fileprivate var _timestamp: UInt32? = nil
}

struct ParticulateData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pm1: UInt32 = 0

  var pm25: UInt32 = 0

  var pm10: UInt32 = 0

  var timestamp: UInt32 {
    get {return _timestamp ?? 0}
    set {_timestamp = newValue}
  }
  /// Returns true if `timestamp` has been explicitly set.
  var hasTimestamp: Bool {return self._timestamp != nil}
  /// Clears the value of `timestamp`. Subsequent reads from it will return its default value.
  mutating func clearTimestamp() {self._timestamp = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _timestamp: UInt32? = nil
}

struct ErrorFlags: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var flag: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Deployment: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var particulateData: ParticulateData {
    get {return _storage._particulateData ?? ParticulateData()}
    set {_uniqueStorage()._particulateData = newValue}
  }
  /// Returns true if `particulateData` has been explicitly set.
  var hasParticulateData: Bool {return _storage._particulateData != nil}
  /// Clears the value of `particulateData`. Subsequent reads from it will return its default value.
  mutating func clearParticulateData() {_uniqueStorage()._particulateData = nil}

  var envData: EnvData {
    get {return _storage._envData ?? EnvData()}
    set {_uniqueStorage()._envData = newValue}
  }
  /// Returns true if `envData` has been explicitly set.
  var hasEnvData: Bool {return _storage._envData != nil}
  /// Clears the value of `envData`. Subsequent reads from it will return its default value.
  mutating func clearEnvData() {_uniqueStorage()._envData = nil}

  var spaceRemainingMb: UInt32 {
    get {return _storage._spaceRemainingMb ?? 0}
    set {_uniqueStorage()._spaceRemainingMb = newValue}
  }
  /// Returns true if `spaceRemainingMb` has been explicitly set.
  var hasSpaceRemainingMb: Bool {return _storage._spaceRemainingMb != nil}
  /// Clears the value of `spaceRemainingMb`. Subsequent reads from it will return its default value.
  mutating func clearSpaceRemainingMb() {_uniqueStorage()._spaceRemainingMb = nil}

  var batteryPercentageX10: UInt32 {
    get {return _storage._batteryPercentageX10}
    set {_uniqueStorage()._batteryPercentageX10 = newValue}
  }

  var accStats: AccStats {
    get {return _storage._accStats ?? AccStats()}
    set {_uniqueStorage()._accStats = newValue}
  }
  /// Returns true if `accStats` has been explicitly set.
  var hasAccStats: Bool {return _storage._accStats != nil}
  /// Clears the value of `accStats`. Subsequent reads from it will return its default value.
  mutating func clearAccStats() {_uniqueStorage()._accStats = nil}

  var steps: UInt32 {
    get {return _storage._steps ?? 0}
    set {_uniqueStorage()._steps = newValue}
  }
  /// Returns true if `steps` has been explicitly set.
  var hasSteps: Bool {return _storage._steps != nil}
  /// Clears the value of `steps`. Subsequent reads from it will return its default value.
  mutating func clearSteps() {_uniqueStorage()._steps = nil}

  var gpsData: GPSData_2 {
    get {return _storage._gpsData ?? GPSData_2()}
    set {_uniqueStorage()._gpsData = newValue}
  }
  /// Returns true if `gpsData` has been explicitly set.
  var hasGpsData: Bool {return _storage._gpsData != nil}
  /// Clears the value of `gpsData`. Subsequent reads from it will return its default value.
  mutating func clearGpsData() {_uniqueStorage()._gpsData = nil}

  var errorFlags: ErrorFlags {
    get {return _storage._errorFlags ?? ErrorFlags()}
    set {_uniqueStorage()._errorFlags = newValue}
  }
  /// Returns true if `errorFlags` has been explicitly set.
  var hasErrorFlags: Bool {return _storage._errorFlags != nil}
  /// Clears the value of `errorFlags`. Subsequent reads from it will return its default value.
  mutating func clearErrorFlags() {_uniqueStorage()._errorFlags = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct MessagePacket: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var header: PacketHeader {
    get {return _header ?? PacketHeader()}
    set {_header = newValue}
  }
  /// Returns true if `header` has been explicitly set.
  var hasHeader: Bool {return self._header != nil}
  /// Clears the value of `header`. Subsequent reads from it will return its default value.
  mutating func clearHeader() {self._header = nil}

  var payload: MessagePacket.OneOf_Payload? = nil

  var systemInfoPacket: SystemInfoPacket {
    get {
      if case .systemInfoPacket(let v)? = payload {return v}
      return SystemInfoPacket()
    }
    set {payload = .systemInfoPacket(newValue)}
  }

  var configPacket: ConfigPacket {
    get {
      if case .configPacket(let v)? = payload {return v}
      return ConfigPacket()
    }
    set {payload = .configPacket(newValue)}
  }

  var ackPacket: AckPacket {
    get {
      if case .ackPacket(let v)? = payload {return v}
      return AckPacket()
    }
    set {payload = .ackPacket(newValue)}
  }

  var systemDeploymentPacket: Deployment {
    get {
      if case .systemDeploymentPacket(let v)? = payload {return v}
      return Deployment()
    }
    set {payload = .systemDeploymentPacket(newValue)}
  }

  var radioInfo: RadioInfo {
    get {return _radioInfo ?? RadioInfo()}
    set {_radioInfo = newValue}
  }
  /// Returns true if `radioInfo` has been explicitly set.
  var hasRadioInfo: Bool {return self._radioInfo != nil}
  /// Clears the value of `radioInfo`. Subsequent reads from it will return its default value.
  mutating func clearRadioInfo() {self._radioInfo = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Payload: Equatable, Sendable {
    case systemInfoPacket(SystemInfoPacket)
    case configPacket(ConfigPacket)
    case ackPacket(AckPacket)
    case systemDeploymentPacket(Deployment)

  }

  init() {}

  fileprivate var _header: PacketHeader? = nil
  fileprivate var _radioInfo: RadioInfo? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension SystemInfoPacket: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SystemInfoPacket"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "system_sensor_summary"),
    2: .standard(proto: "sdcard_state"),
    3: .standard(proto: "battery_state"),
    4: .same(proto: "metadata"),
    5: .standard(proto: "gps_data"),
  ]

  fileprivate class _StorageClass {
    var _systemSensorSummary: SystemSensorSummary? = nil
    var _sdcardState: SDCardState? = nil
    var _batteryState: BatteryState? = nil
    var _metadata: Metadata? = nil
    var _gpsData: GPSData? = nil

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _systemSensorSummary = source._systemSensorSummary
      _sdcardState = source._sdcardState
      _batteryState = source._batteryState
      _metadata = source._metadata
      _gpsData = source._gpsData
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._systemSensorSummary) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._sdcardState) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._batteryState) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._metadata) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._gpsData) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._systemSensorSummary {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._sdcardState {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._batteryState {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._metadata {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._gpsData {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SystemInfoPacket, rhs: SystemInfoPacket) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._systemSensorSummary != rhs_storage._systemSensorSummary {return false}
        if _storage._sdcardState != rhs_storage._sdcardState {return false}
        if _storage._batteryState != rhs_storage._batteryState {return false}
        if _storage._metadata != rhs_storage._metadata {return false}
        if _storage._gpsData != rhs_storage._gpsData {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Metadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Metadata"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "gps_avg_fix_time"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.gpsAvgFixTime) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.gpsAvgFixTime.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.gpsAvgFixTime, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Metadata, rhs: Metadata) -> Bool {
    if lhs.gpsAvgFixTime != rhs.gpsAvgFixTime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ConfigPacket: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ConfigPacket"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "engage_system"),
    2: .standard(proto: "enable_microphone"),
    3: .standard(proto: "enable_activity"),
    4: .standard(proto: "enable_particulate"),
    5: .standard(proto: "enable_environmental"),
    6: .standard(proto: "enable_light"),
    7: .standard(proto: "enable_motion"),
    8: .standard(proto: "enable_lora"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.engageSystem) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.enableMicrophone) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.enableActivity) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.enableParticulate) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.enableEnvironmental) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.enableLight) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.enableMotion) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.enableLora) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.engageSystem != false {
      try visitor.visitSingularBoolField(value: self.engageSystem, fieldNumber: 1)
    }
    if self.enableMicrophone != false {
      try visitor.visitSingularBoolField(value: self.enableMicrophone, fieldNumber: 2)
    }
    if self.enableActivity != false {
      try visitor.visitSingularBoolField(value: self.enableActivity, fieldNumber: 3)
    }
    if self.enableParticulate != false {
      try visitor.visitSingularBoolField(value: self.enableParticulate, fieldNumber: 4)
    }
    if self.enableEnvironmental != false {
      try visitor.visitSingularBoolField(value: self.enableEnvironmental, fieldNumber: 5)
    }
    if self.enableLight != false {
      try visitor.visitSingularBoolField(value: self.enableLight, fieldNumber: 6)
    }
    if self.enableMotion != false {
      try visitor.visitSingularBoolField(value: self.enableMotion, fieldNumber: 7)
    }
    if self.enableLora != false {
      try visitor.visitSingularBoolField(value: self.enableLora, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ConfigPacket, rhs: ConfigPacket) -> Bool {
    if lhs.engageSystem != rhs.engageSystem {return false}
    if lhs.enableMicrophone != rhs.enableMicrophone {return false}
    if lhs.enableActivity != rhs.enableActivity {return false}
    if lhs.enableParticulate != rhs.enableParticulate {return false}
    if lhs.enableEnvironmental != rhs.enableEnvironmental {return false}
    if lhs.enableLight != rhs.enableLight {return false}
    if lhs.enableMotion != rhs.enableMotion {return false}
    if lhs.enableLora != rhs.enableLora {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension GPSData_2: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "GPSData_2"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "latitude_e7"),
    2: .standard(proto: "longitude_e7"),
    3: .standard(proto: "altitude_mm"),
    4: .same(proto: "timestamp"),
    5: .standard(proto: "gps_avg_fix_time_ms"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.latitudeE7) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.longitudeE7) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.altitudeMm) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self._timestamp) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self._gpsAvgFixTimeMs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.latitudeE7 != 0 {
      try visitor.visitSingularInt32Field(value: self.latitudeE7, fieldNumber: 1)
    }
    if self.longitudeE7 != 0 {
      try visitor.visitSingularInt32Field(value: self.longitudeE7, fieldNumber: 2)
    }
    if self.altitudeMm != 0 {
      try visitor.visitSingularUInt32Field(value: self.altitudeMm, fieldNumber: 3)
    }
    try { if let v = self._timestamp {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._gpsAvgFixTimeMs {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: GPSData_2, rhs: GPSData_2) -> Bool {
    if lhs.latitudeE7 != rhs.latitudeE7 {return false}
    if lhs.longitudeE7 != rhs.longitudeE7 {return false}
    if lhs.altitudeMm != rhs.altitudeMm {return false}
    if lhs._timestamp != rhs._timestamp {return false}
    if lhs._gpsAvgFixTimeMs != rhs._gpsAvgFixTimeMs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SystemSensorSummary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SystemSensorSummary"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "temperature"),
    2: .same(proto: "humidity"),
    3: .same(proto: "pressure"),
    4: .same(proto: "gas"),
    5: .same(proto: "pm1"),
    6: .standard(proto: "pm2_5"),
    7: .same(proto: "pm10"),
    8: .same(proto: "light"),
    9: .same(proto: "steps"),
    10: .standard(proto: "particulate_obstructed"),
    11: .standard(proto: "particulate_outside_detection_limits"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.temperature) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.humidity) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.pressure) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.gas) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self.pm1) }()
      case 6: try { try decoder.decodeSingularFloatField(value: &self.pm25) }()
      case 7: try { try decoder.decodeSingularFloatField(value: &self.pm10) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.light) }()
      case 9: try { try decoder.decodeSingularUInt32Field(value: &self.steps) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self.particulateObstructed) }()
      case 11: try { try decoder.decodeSingularBoolField(value: &self.particulateOutsideDetectionLimits) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.temperature.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.temperature, fieldNumber: 1)
    }
    if self.humidity.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.humidity, fieldNumber: 2)
    }
    if self.pressure.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.pressure, fieldNumber: 3)
    }
    if self.gas.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.gas, fieldNumber: 4)
    }
    if self.pm1.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.pm1, fieldNumber: 5)
    }
    if self.pm25.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.pm25, fieldNumber: 6)
    }
    if self.pm10.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.pm10, fieldNumber: 7)
    }
    if self.light != 0 {
      try visitor.visitSingularUInt32Field(value: self.light, fieldNumber: 8)
    }
    if self.steps != 0 {
      try visitor.visitSingularUInt32Field(value: self.steps, fieldNumber: 9)
    }
    if self.particulateObstructed != false {
      try visitor.visitSingularBoolField(value: self.particulateObstructed, fieldNumber: 10)
    }
    if self.particulateOutsideDetectionLimits != false {
      try visitor.visitSingularBoolField(value: self.particulateOutsideDetectionLimits, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SystemSensorSummary, rhs: SystemSensorSummary) -> Bool {
    if lhs.temperature != rhs.temperature {return false}
    if lhs.humidity != rhs.humidity {return false}
    if lhs.pressure != rhs.pressure {return false}
    if lhs.gas != rhs.gas {return false}
    if lhs.pm1 != rhs.pm1 {return false}
    if lhs.pm25 != rhs.pm25 {return false}
    if lhs.pm10 != rhs.pm10 {return false}
    if lhs.light != rhs.light {return false}
    if lhs.steps != rhs.steps {return false}
    if lhs.particulateObstructed != rhs.particulateObstructed {return false}
    if lhs.particulateOutsideDetectionLimits != rhs.particulateOutsideDetectionLimits {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AckPacket: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "AckPacket"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: AckPacket, rhs: AckPacket) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RadioInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "RadioInfo"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "rssi"),
    2: .same(proto: "snr"),
    3: .standard(proto: "rssi_est"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.rssi) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.snr) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.rssiEst) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.rssi != 0 {
      try visitor.visitSingularInt32Field(value: self.rssi, fieldNumber: 1)
    }
    if self.snr != 0 {
      try visitor.visitSingularInt32Field(value: self.snr, fieldNumber: 2)
    }
    if self.rssiEst != 0 {
      try visitor.visitSingularInt32Field(value: self.rssiEst, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RadioInfo, rhs: RadioInfo) -> Bool {
    if lhs.rssi != rhs.rssi {return false}
    if lhs.snr != rhs.snr {return false}
    if lhs.rssiEst != rhs.rssiEst {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AccAxis: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "AccAxis"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "x"),
    2: .same(proto: "y"),
    3: .same(proto: "z"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.x) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.y) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.z) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.x != 0 {
      try visitor.visitSingularUInt32Field(value: self.x, fieldNumber: 1)
    }
    if self.y != 0 {
      try visitor.visitSingularUInt32Field(value: self.y, fieldNumber: 2)
    }
    if self.z != 0 {
      try visitor.visitSingularUInt32Field(value: self.z, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: AccAxis, rhs: AccAxis) -> Bool {
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.z != rhs.z {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AccStats: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "AccStats"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "ODBA_mean_x100"),
    2: .standard(proto: "ODBA_max_x100"),
    3: .standard(proto: "VeDBA_mean_x100"),
    4: .standard(proto: "VeDBA_max_x100"),
    5: .standard(proto: "StdDev_x100"),
    6: .standard(proto: "Mean_x100"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.odbaMeanX100) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.odbaMaxX100) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.veDbaMeanX100) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.veDbaMaxX100) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._stdDevX100) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._meanX100) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.odbaMeanX100 != 0 {
      try visitor.visitSingularUInt32Field(value: self.odbaMeanX100, fieldNumber: 1)
    }
    if self.odbaMaxX100 != 0 {
      try visitor.visitSingularUInt32Field(value: self.odbaMaxX100, fieldNumber: 2)
    }
    if self.veDbaMeanX100 != 0 {
      try visitor.visitSingularUInt32Field(value: self.veDbaMeanX100, fieldNumber: 3)
    }
    if self.veDbaMaxX100 != 0 {
      try visitor.visitSingularUInt32Field(value: self.veDbaMaxX100, fieldNumber: 4)
    }
    try { if let v = self._stdDevX100 {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._meanX100 {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: AccStats, rhs: AccStats) -> Bool {
    if lhs.odbaMeanX100 != rhs.odbaMeanX100 {return false}
    if lhs.odbaMaxX100 != rhs.odbaMaxX100 {return false}
    if lhs.veDbaMeanX100 != rhs.veDbaMeanX100 {return false}
    if lhs.veDbaMaxX100 != rhs.veDbaMaxX100 {return false}
    if lhs._stdDevX100 != rhs._stdDevX100 {return false}
    if lhs._meanX100 != rhs._meanX100 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension EnvData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "EnvData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "temperature_x10"),
    2: .standard(proto: "humidity_x10"),
    3: .same(proto: "gas"),
    4: .same(proto: "pressure"),
    5: .same(proto: "light"),
    6: .same(proto: "timestamp"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._temperatureX10) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self._humidityX10) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self._gas) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self._pressure) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self._light) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self._timestamp) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._temperatureX10 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._humidityX10 {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._gas {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._pressure {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._light {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._timestamp {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: EnvData, rhs: EnvData) -> Bool {
    if lhs._temperatureX10 != rhs._temperatureX10 {return false}
    if lhs._humidityX10 != rhs._humidityX10 {return false}
    if lhs._gas != rhs._gas {return false}
    if lhs._pressure != rhs._pressure {return false}
    if lhs._light != rhs._light {return false}
    if lhs._timestamp != rhs._timestamp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ParticulateData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ParticulateData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "pm1"),
    2: .standard(proto: "pm2_5"),
    3: .same(proto: "pm10"),
    4: .same(proto: "timestamp"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.pm1) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.pm25) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.pm10) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self._timestamp) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.pm1 != 0 {
      try visitor.visitSingularUInt32Field(value: self.pm1, fieldNumber: 1)
    }
    if self.pm25 != 0 {
      try visitor.visitSingularUInt32Field(value: self.pm25, fieldNumber: 2)
    }
    if self.pm10 != 0 {
      try visitor.visitSingularUInt32Field(value: self.pm10, fieldNumber: 3)
    }
    try { if let v = self._timestamp {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ParticulateData, rhs: ParticulateData) -> Bool {
    if lhs.pm1 != rhs.pm1 {return false}
    if lhs.pm25 != rhs.pm25 {return false}
    if lhs.pm10 != rhs.pm10 {return false}
    if lhs._timestamp != rhs._timestamp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ErrorFlags: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ErrorFlags"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "flag"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.flag) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.flag != 0 {
      try visitor.visitSingularUInt32Field(value: self.flag, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ErrorFlags, rhs: ErrorFlags) -> Bool {
    if lhs.flag != rhs.flag {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Deployment: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Deployment"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "particulateData"),
    2: .same(proto: "envData"),
    3: .standard(proto: "space_remaining_mb"),
    4: .standard(proto: "battery_percentage_x10"),
    5: .same(proto: "accStats"),
    6: .same(proto: "steps"),
    7: .standard(proto: "gps_data"),
    8: .same(proto: "errorFlags"),
  ]

  fileprivate class _StorageClass {
    var _particulateData: ParticulateData? = nil
    var _envData: EnvData? = nil
    var _spaceRemainingMb: UInt32? = nil
    var _batteryPercentageX10: UInt32 = 0
    var _accStats: AccStats? = nil
    var _steps: UInt32? = nil
    var _gpsData: GPSData_2? = nil
    var _errorFlags: ErrorFlags? = nil

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _particulateData = source._particulateData
      _envData = source._envData
      _spaceRemainingMb = source._spaceRemainingMb
      _batteryPercentageX10 = source._batteryPercentageX10
      _accStats = source._accStats
      _steps = source._steps
      _gpsData = source._gpsData
      _errorFlags = source._errorFlags
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._particulateData) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._envData) }()
        case 3: try { try decoder.decodeSingularUInt32Field(value: &_storage._spaceRemainingMb) }()
        case 4: try { try decoder.decodeSingularUInt32Field(value: &_storage._batteryPercentageX10) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._accStats) }()
        case 6: try { try decoder.decodeSingularUInt32Field(value: &_storage._steps) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._gpsData) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._errorFlags) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._particulateData {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._envData {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._spaceRemainingMb {
        try visitor.visitSingularUInt32Field(value: v, fieldNumber: 3)
      } }()
      if _storage._batteryPercentageX10 != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._batteryPercentageX10, fieldNumber: 4)
      }
      try { if let v = _storage._accStats {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._steps {
        try visitor.visitSingularUInt32Field(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._gpsData {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._errorFlags {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Deployment, rhs: Deployment) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._particulateData != rhs_storage._particulateData {return false}
        if _storage._envData != rhs_storage._envData {return false}
        if _storage._spaceRemainingMb != rhs_storage._spaceRemainingMb {return false}
        if _storage._batteryPercentageX10 != rhs_storage._batteryPercentageX10 {return false}
        if _storage._accStats != rhs_storage._accStats {return false}
        if _storage._steps != rhs_storage._steps {return false}
        if _storage._gpsData != rhs_storage._gpsData {return false}
        if _storage._errorFlags != rhs_storage._errorFlags {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension MessagePacket: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "MessagePacket"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "header"),
    2: .standard(proto: "system_info_packet"),
    3: .standard(proto: "config_packet"),
    4: .standard(proto: "ack_packet"),
    5: .standard(proto: "system_deployment_packet"),
    6: .standard(proto: "radio_info"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._header) }()
      case 2: try {
        var v: SystemInfoPacket?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .systemInfoPacket(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .systemInfoPacket(v)
        }
      }()
      case 3: try {
        var v: ConfigPacket?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .configPacket(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .configPacket(v)
        }
      }()
      case 4: try {
        var v: AckPacket?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .ackPacket(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .ackPacket(v)
        }
      }()
      case 5: try {
        var v: Deployment?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .systemDeploymentPacket(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .systemDeploymentPacket(v)
        }
      }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._radioInfo) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._header {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    switch self.payload {
    case .systemInfoPacket?: try {
      guard case .systemInfoPacket(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .configPacket?: try {
      guard case .configPacket(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .ackPacket?: try {
      guard case .ackPacket(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .systemDeploymentPacket?: try {
      guard case .systemDeploymentPacket(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try { if let v = self._radioInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: MessagePacket, rhs: MessagePacket) -> Bool {
    if lhs._header != rhs._header {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs._radioInfo != rhs._radioInfo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
